### ISSUE TITLE
KeepassXC-browser extension - "Key exchange was not successful."

### ISSUE THREAD

**Issue by PritishParihar** [keeweb/keeweb#1845] opened 2021-06-17 15:00 UTC
Randomly KeepassXC-browser extension disconnect on restart Edge browser. I'm new to the KeepassXC-extension and as well Keeweb, so kindly let me know if this is right place for issue, since keeweb don't have issues option on github repo I guess.

Current Behavior
Key exchange was not successful.

Inspecting extension > "Console" tab output

[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://oboonakemofpalcgghocfoadofidjkkk/fonts/forkawesome-webfont.woff2?v=1.1.7

DevTools failed to load source map: Could not load content for chrome-extension://oboonakemofpalcgghocfoadofidjkkk/fonts/fork-awesome.min.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

Steps to Reproduce (for bugs)
Since error is random, I can barely connect very few times, most times end up disconnecting.

Debug info
KeePassXC-Browser - 1.7.8.1
Operating system: Win64
Browser: Microsoft Edge 91.0.864.48
Edge Version 91.0.864.48 (Official build) (64-bit)
KeeWeb v1.18.6 (070573e, 2021-05-19)
Environment: electron v12.0.7
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.18.6 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by antelle** [comment] 2021-06-17 16:03
That's the right place, yes. I'll look into this issue, thank you for reporting!

**Comment by PritishParihar** [comment] 2021-06-18 05:05
Update: 
Tried to replicate on fresh machine
I have same setup [KeeWeb + KeepassXC-browser extension] installed  on fresh machine. I wasn't able replicate this on it.


So maybe it can be conflict due to previously installed KeepassXC. So I have uninstalled KeepassXC and rebooted the old machine back, also re-installed the extension just to clean up any residual files but still have this issue. 

What steps do you recommended which I can take to make this troubleshooting faster? Or do you need need any more insights?

**Comment by PritishParihar** [comment] 2021-06-18 05:29
Update: 

I was able to reproduce same error in older machine. 

While using Edge browser, I created a new profile and installed the extension from Microsoft Store, initially it worked like a charm. But when I close the KeeWeb app to disconnect and tried to reload then extension reported "Key exchange was not successful" and that was fine since I closed the app itself. But when I reopen and tried to make connection again same error. 
Tried restarting both keeweb and browser itself but no luck in exchanging keys, same error. 

I then downloaded Google chrome and did the same process, it worked for me same as creating new profile in edge browser, but once connection gets disconnect it hard to reconnect.

**Comment by PritishParihar** [comment] 2021-06-25 13:36
![image](https://user-images.githubusercontent.com/22941460/123432801-5f201880-d5e8-11eb-9a8d-8edd4fccd014.png)
From few days, this error started poping up, can this have any relation ?

**Comment by antelle** [comment] 2021-06-25 15:59
Interesting, haven't seen it before. Do you see keeweb-native-messaging-host in the task manager?

**Comment by PritishParihar** [comment] 2021-06-28 09:30
![Keewebtasks](https://user-images.githubusercontent.com/22941460/123613974-87df2280-d821-11eb-8523-7b4cbd31d1c2.jpg)

**Comment by PritishParihar** [comment] 2021-06-28 09:31
I have created a dump file as well, letme know if you like to look over on it. Size ~360MB

**Comment by PritishParihar** [comment] 2021-07-07 03:54
Update: JavaScript Error is due to KeepassXC-browser Extension on browser, after switching to Keepass connect & turned off tick on KeepassXC-browser extension integration on Keepass Desktop I haven't seen the error in while. 

2 feature can you consider adding to next release of Keepass Connect: 

- Can add credential from browser itself , like
![image](https://user-images.githubusercontent.com/22941460/124697613-b4bbc580-df04-11eb-835f-e1e35868a111.png)

- Showing KeepassConnect in field of username, so that we can fill with one click like 
![image](https://user-images.githubusercontent.com/22941460/124697808-1845f300-df05-11eb-89ec-b1dd6648dca6.png)

**Comment by antelle** [comment] 2021-07-07 15:45
Just a note, please don't report it to KeePassXC-Browser bug tracker because the errors are very likely to be caused by KeeWeb.

KeeWeb Connect won't have UI inserted to the page, but in future it's possible that we'll consider adding a function to save fields back to KeeWeb. Not sure if this will happen though, it requires some effort.

**Comment by antelle** [comment] 2021-07-07 15:45
(closed by mistake, the issue should be still fixed)

**Closed** 2021-07-18 14:06 UTC
Labels: browser-interaction, bug
