### ISSUE TITLE
URL recognition does not work in Microsoft Edge

### ISSUE THREAD

**Issue by Phreeak** [keeweb/keeweb#342] opened 2016-09-04 14:50 UTC
- what were your actions?
**Click in Keeweb on link and then try to autotype**
- what was wrong?
**Keeweb says "no match found"**
- app Version
**1.3.1 Windows**
- your user-agent (from Settings/Help section)**
**KeeWeb v1.3.1 (234333d, 2016-09-02)**
**Environment: electron v1.3.3**
**User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)** **KeeWeb/1.3.1 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36****

![url](https://cloud.githubusercontent.com/assets/21967882/18231616/462c6e1a-72be-11e6-95b6-11e74ba8da16.PNG)

**Comment by antelle** [comment] 2016-09-04 19:25
Hello,
I just tried and it works ok for me. Please paste logs from browser console. Most probably url was not detected by keeweb.

**Comment by Phreeak** [comment] 2016-09-04 19:50
Hi,

here the log.

2016-09-04T19:49:48.158Z [auto-type] Auto type event null
index.html:13 2016-09-04T19:49:48.158Z [auto-type] Get window title
index.html:13 2016-09-04T19:49:48.225Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 71ms
Sophos und 1 weitere Seite ?- Microsoft Edge
index.html:13 2016-09-04T19:49:48.225Z [auto-type] Window title Sophos und 1 weitere Seite ?- Microsoft Edge undefined
index.html:13 2016-09-04T19:50:05.134Z [auto-type] Entry selected null
index.html:13 2016-09-04T19:50:05.137Z [auto-type] Hide window

**Comment by antelle** [comment] 2016-09-04 19:56
> [auto-type] Window title Sophos und 1 weitere Seite ?- Microsoft Edge **undefined**

This means, there was an error getting URL for Microsoft Edge, and for title, there were no matches. Does url detection works for other urls in Edge for you?

**Comment by Phreeak** [comment] 2016-09-04 20:02
Yes, other URL's work perfekt.
e.g. Winfuture.de, Computerbase.de ....

**Comment by antelle** [comment] 2016-09-04 20:03
Please make sure, that actual url appears in app logs. We could also detect entries by title, so this might work in your case, instead of url.

**Comment by Phreeak** [comment] 2016-09-04 20:10
Hi,

unfortunately the same result

2016-09-04T20:09:04.941Z [auto-type] Auto type event null
index.html:13 2016-09-04T20:09:04.957Z [auto-type] Get window title
index.html:13 2016-09-04T20:09:05.037Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 79ms
Sophos und 1 weitere Seite ?- Microsoft Edge
index.html:13 2016-09-04T20:09:05.037Z [auto-type] Window title Sophos und 1 weitere Seite ?- Microsoft Edge undefined

![title](https://cloud.githubusercontent.com/assets/21967882/18233616/65845ac4-72ec-11e6-89e8-cde4e21f4b67.PNG)
![entry](https://cloud.githubusercontent.com/assets/21967882/18233617/6877c5a4-72ec-11e6-9db6-5cb12f25ab5c.PNG)

**Comment by antelle** [comment] 2016-09-04 20:12
Oh, most probably I expressed thoughts in wrong way, and you have misunderstood me. I mean, please check a website which works for you (e.g. Winfuture.de, Computerbase.de): does KeeWeb really detect URL or just finds entries by title?

**Comment by Phreeak** [comment] 2016-09-04 20:17
Sorry,
now i tested with Computerbase. It recognize the title i think

2016-09-04T20:13:59.494Z [auto-type] Auto type event null
index.html:13 2016-09-04T20:13:59.512Z [auto-type] Get window title
index.html:13 2016-09-04T20:13:59.592Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 80ms
Einloggen - ComputerBase und 2 weitere Seiten ?- Microsoft Edge
index.html:13 2016-09-04T20:13:59.594Z [auto-type] Window title Einloggen - ComputerBase und 2 weitere Seiten ?- Microsoft Edge undefined
index.html:13 2016-09-04T20:13:59.597Z [auto-type] Hide window
index.html:13 2016-09-04T20:13:59.598Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
index.html:13 2016-09-04T20:13:59.599Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
index.html:13 2016-09-04T20:13:59.600Z [auto-type] Resolved [**************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:13 2016-09-04T20:13:59.610Z [auto-type] Obfuscated
index.html:13 2016-09-04T20:14:06.380Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 6765ms
index.html:13 2016-09-04T20:14:06.382Z [auto-type] Complete 6785ms

**Comment by antelle** [comment] 2016-09-04 20:40
It, url is not recognized here. So, the problem is clear now: we cannot get url from Edge. Should be fixed in helper, [here](https://github.com/keeweb/keeweb/blob/master/helper/win32/src/KeeWebHelper/WindowHelper.cs#L47). I'll try to figure it out. If you have a working solution for Edge, suggestions and ideas are always welcome 😉

**Comment by antelle** [comment] 2016-09-05 18:47
Fixed it, it will work in next version

**Comment by Phreeak** [comment] 2016-09-05 19:06
Perfect, Thanks!

**Closed** 2016-09-13 20:44 UTC
Labels: auto-type, browser-interaction, bug, desktop, windows
