### ISSUE TITLE
Install third party plugins

### ISSUE THREAD

**Issue by b3nj5m1n** [keeweb/keeweb#1516] opened 2020-05-23 18:44 UTC
**Is your feature request related to a problem? Please describe.**
Yes, installing a custom plugin in the desktop version of keeweb is very hard to do at the moment, making desktop plugin development a real pain.

**Describe the solution you'd like**

- Manual Installation: The ability to install from files (Download a zip archive containing the relevant files from a third party, open them up in keeweb and install them)
- Automatic Installation: Installing directly from a git repository (Similar to how vim plugin managers handle the installation) by just entering the url to the git repo.

**Describe alternatives you've considered**
See #1515.

**Additional context**
If security is a concern, this feature could be implemented in the form of a plugin itself. This plugin would be added to the official plugin list and users who know what they are doing and are willing to take the risk can manually install this plugin.
It could also be implemented but not activated by default, the setting to activate it could be placed in the advanced section.

**Comment by antelle** [comment] 2020-05-23 19:47
Hi! I'll close this a duplicate of #1254 if you don't mind.
I will add more context and my concerns to that issue, which will also partially answer your questions asked here.

**Closed by antelle** 2020-05-23 19:47 UTC
Labels: enhancement

**Comment by antelle** [comment] 2020-05-23 20:42
Added my concerns and a proposal about custom plugins to #1254.
