### ISSUE TITLE
Can't find Shared drives in files list when using Google Drive

### ISSUE THREAD

**Issue by razielvamp666** [keeweb/keeweb#1782] opened 2021-04-07 10:03 UTC
Is it possible to access files in `Shared Drives`?

![shared_drives](https://user-images.githubusercontent.com/20613106/113848934-f2a93080-97d3-11eb-8f81-09aac9adf6c6.png)

I can see only `Shared with me` in file list.

![files_list](https://user-images.githubusercontent.com/20613106/113849385-64817a00-97d4-11eb-9ca1-4b242108e2f5.jpg)

Looks like Google API allows to do that

```javascript
// Find all shared drives without an organizer and add one.
// Note: This example does not capture all cases. Shared drives
// that have an empty group as the sole organizer, or an
// organizer outside the organization are not captured. A
// more exhaustive approach would evaluate each shared drive
// and the associated permissions and groups to ensure an active
// organizer is assigned.
string pageToken = null;
var newOrganizerPermission = new Permission()
{
    Type = "user",
    Role = "organizer",
    EmailAddress = "user@example.com"
};

do
{
    var request = driveService.Drives.List();
    request.UseDomainAdminAccess = true;
    request.Q = "organizerCount = 0";
    request.Fields = "nextPageToken, drives(id, name)";
    request.PageToken = pageToken;
    var result = request.Execute();
    foreach (var drive in result.Drives)
    {
        Console.WriteLine(string.Format(
               "Found abandoned shared drive: {0} ({1})",
               drive.Name, drive.Id));
        // Note: For improved efficiency, consider batching
        // permission insert requests
        var permissionRequest = driveService.Permissions.Create(
          newOrganizerPermission,
          drive.Id
        );
        permissionRequest.UseDomainAdminAccess = true;
        permissionRequest.SupportsAllDrives = true;
        permissionRequest.Fields = "id";
        var permissionResult = permissionRequest.Execute();
        Console.WriteLine(string.Format(
               "Added organizer permission: {0}", permissionResult.Id));

    }
    pageToken = result.NextPageToken;
} while (pageToken != null);
```

**Comment by antelle** [comment] 2021-04-07 16:10
Duplicate of #618

**Closed by antelle** 2021-04-07 16:10 UTC
Labels: enhancement
