### ISSUE TITLE
Improve user flow when AutoType finds no matching entry

### ISSUE THREAD

**Issue by h-nes** [keeweb/keeweb#500] opened 2017-01-25 20:48 UTC
I was wondering if the selection process for a login that is not directly matched with AutoType could be improved. 

Currently, I get an empty window telling me that nothing was found. I can then hit "show all entries" and only then I'm back in the beloved land of "find as you type" where I find and select the wanted login.

I find it particularly anoying because the "show all entries" button requires me to get back to the mouse and hit a rather small target.

My suggestion:
- make this button much larger and maybe center it (not preferred but maybe easier solution)
- Is this empty screen necessary at all? Why not go to the full list if no entry matches? You could place a message somewhere saying that "nothing was found and all entries are shown instead"?

KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment] 2017-01-25 21:17
I think, the second option makes sense. Additionally, we may should show this warning somewhere, to make it clear, why we show all entries.

**Comment by taggstarops** [comment] 2017-01-31 01:26
Hi,

I think it can be even more sophisticated. My understanding is that the resolution is based on the page/app title which must exactly match the password entry title in the Keeweb. I can image two improvements which can be very helpful here:

1. If exact match is not found then list any entries which title contains any word from the page/app title sorted by matching occurrences.
Example:
Web page title = Amazon Web Service Sign-In
Entries
1. Amazon account
2. Amazon Service account
3. Another entry
4. Amazon Web Service account

The result (displayed entries):
1. Amazon Web Service account
2. Amazon Service account
3. Amazon account

Reason:
This can be very useful in two cases. The first is that the password entries don't need to match exactly. The second is that someone can have several logins to the same app (QA, prod, user, admin, etc.) so for example a suffix can be used for that.

2. Having a new password entry attribute which would be use for searching of the matching entry together with the title itself. Something like _auto-type title_. 

Reason: I found using the title attribute for the auto-type matching quite limiting as I would like to have entries named differently then is their login page title. Or maybe the URL attribute can be used for this as well. Also this can be helpful for the new users. For me it took time to understand how it works. It would be easier for me if I see something like _auto-type title_ attribute.

Thanks for the consideration!

Stan

**Comment by antelle** [comment] 2017-01-31 06:43
1. that would be confusing, we don't want to **auto-type** anything based on fuzzy search. But it's a great idea for search **order**.
2. there's such attribute in mode detailed auto-type configuration, but we don't support it yet.

**Comment by StanSvec** [comment] 2017-01-31 11:30
Hi Antelle,

Regarding the first point I'm sorry for the unclear explanation. This is what I meant. That if there is not exact entry then ordered entries would come up in the list sorted by relevance. I can imagine it can be also graphically separated like Relevant Matches section for entries with at least one word match and No Matches section.

However I submitted the comment, because I thought that exact match is always required. But now I can see that Keeweb offers relevant entries for some web sites already even when title doesn't match strictly. But for the majority cases the list is still empty even when I have relevant password entries (containing words from the web page or application title) stored in KeeWeb. I'm still bit confused about how it works.

**Comment by benzkji** [comment] 2017-02-22 08:11
It is already the case, that multiple (fuzzy searched) entries are presented if there are multiple matches, or am I wrong? The "no match at all" is important to me - as @StanSvec pointed out, one must get back to the mouse, and click "show all". Having just the whole list, ready to "find as you type" would be a real time saver in IMHO.

**Comment by StanSvec** [comment] 2017-03-02 10:51
benzkji - Sometimes there are multiple matches listed as well, but at least for me the most of the time it's not precise. The worst thing is that few times keeweb entered incorrect credentials and I even didn't know which one. I think the safest would be always showing list/confirmation first.

**Comment by antelle** [comment] 2017-03-02 17:57
@StanSvec when the match is not precise, it will be displayed in this list. Only entries, which are (almost) certainly matching, will be auto-typed automatically.

**Comment by StanSvec** [comment] 2017-03-04 22:42
@antelle I found out the cause of the issue. I have entry named Firefox (Firefox Account) in one of my files so when there was no match KeeWeb automatically used it. I will rename it.

**Comment by h-nes** [comment] 2017-03-11 10:25
@antelle thanks a lot for implementing this so quickly. KeeWeb is now my #1 suggestion to anyone asking for password management!

Small suggestion for (visual) improvement:
The URL column (most right one) in the "matching screen" is usually far too narrow for the URL strings, at least for my entries. Therefore, the string wraps several times, creating a rather high table row. 
One option could be to place the URL into a separate line below title and login fields.

As the find-as-you-type works so well and relevant entries are always at the top of the list (at least for me), this is not functionally necessary but would be aesthetically cleaner.

**Comment by antelle** [comment] 2017-05-20 20:33
Fixed with v1.5.

**Closed by antelle** 2017-05-20 20:33 UTC
Labels: auto-type, desktop, enhancement, ux
