### ISSUE TITLE
Java script error at update from 1.9.3 to 1.10.0

### ISSUE THREAD

**Issue by bastos77** [keeweb/keeweb#1256] opened 2019-09-10 08:55 UTC
**Describe the bug**
After update out of v1.9.3 the app (ubuntu 18.04) closes but instead of re-opening this error message appeared.
Without restarting the whole system after update I am not able to open KeeWeb, but after restart, the updated app launches 
The same situation I had yesterday after updateing to 1.9.3 

**To Reproduce**
1. General Settings only check updates not installing
2. If update is mentioned, click on the bell
3. click update

**Expected behavior**
app reloads in new version again

**Screenshots**
![keeweb](https://user-images.githubusercontent.com/12494783/64598602-4feebd00-d3b8-11e9-9df3-5734dc03fd30.png)

**Environment**
KeeWeb v1.10.0 (1b64dd6d, 2019-09-09)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.0 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

**Comment by antelle** [comment] 2019-09-10 15:45
Weird, looks like the same as #1158, however I don't yet understand why, but I have an idea, will try to reproduce it.

**Comment by antelle** [comment] 2019-09-20 18:35
I think I have an idea why it happens. Changed the code so that it doesn't read the file from an updated archive.

**Comment by bastos77** [comment] 2019-09-23 06:43
Thank you @antelle . Has not happened again by updating from 1.10.0 to 1.10.1

**Comment by antelle** [comment] 2019-09-23 06:45
It’s not fixed in this version yet. This should not happen after updating from 1.11.x to future versions, for now it’s still there.

**Closed** 2019-09-28 18:39 UTC
Labels: bug, updater
