### ISSUE TITLE
[Feature Request] Enable web server to pre-populate WebDAV info

### ISSUE THREAD

**Issue by nakedhitman** [keeweb/keeweb#258] opened 2016-07-07 22:39 UTC
I would love to see the ability for the web server hosting the web app to inject the URL, username and password for WebDAV. Such an auto-login capability would enable the development of an OwnCloud/NextCloud app for more convenient access to an already-authenticated user's password database.

**Comment by antelle** [comment] 2016-07-15 07:35
duplicate of #220

**Closed by antelle** 2016-07-15 07:35 UTC
Labels: customization, enhancement
