### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by EnricoMonese** [keeweb/keeweb#611] opened 2017-04-23 12:56 UTC
Branch https://github.com/EnricoMonese/keeweb/tree/theming

Moved appearance settings in new Theming section in app settings.

The plan is to make a theme builder with export-import support through json theme files (similar to export api for settings).
Suggestions for a color picker are welcome.
The plugin-theme should be removed as themes will be independent. Plugins can still be used for theming purposes, they just wont be applied as themes like they are now.

**Comment by antelle** [comment] 2017-04-23 16:47
Themes will be installed only as plugins. We don't need a separate section for this.

**Closed by antelle** 2017-04-23 16:47 UTC

**Comment by EnricoMonese** [comment] 2017-04-23 17:47
So the theme builder ships with Keeweb and exports themes as plugins, is this right?

**Comment by antelle** [comment] 2017-04-23 18:03
No, it won't be a part of core product, so it won't ship with keeweb, because creating a plugin or theme is not something regular user needs.
But we already support CSS in plugins. Creating a theme should be as simple as generating proper css for it. We can begin with (ab)using existing scss and extracting styles generated for theme. Later, I'm planning to get rid of static css generation (aka `th`) and replace it with color classes, which will be included in theme, as well as other css, if required by design.

**Comment by antelle** [comment] 2017-04-23 18:27
So, the basic migration plan:
1. replace `@include th { color: theme-color(); }` with `var(--theme-color)`
2. separate borders and other stuff from themes, assign theme variables to `body.theme`
3. create a generator

Hm, step 1 can be done with simple find'n'replace, step2 is also not that hard, because we have about 30 styles total. I'll think about implementing it in the upcoming version.

**Comment by EnricoMonese** [comment] 2017-04-23 18:59
There could be some general options for colors of text and things. Sections already have usable names like _app__menu_, each section could then have options for color of buttons, labels, input fields etc. that are inside them. If not defined the general colors would be used.

**Comment by EnricoMonese** [comment] 2017-04-23 19:10
Also if theming uses variables, the plugin-theme could just define the variables, is this how it works? Haven't really used css variables until recently

**Comment by antelle** [comment] 2017-04-23 19:26
> each section could then have options for color of buttons, labels

CSS variables is easier to implement and support. Browsers without CSS variables will support only default theme, and it won't be possible to change it. It's now only Edge 14, which is decreasing as Edge 15 is already released, but still has 50% of total Edge traffic.
> Also if theming uses variables, the plugin-theme could just define the variables, is this how it works? 

Example of plugin css with variables:
```css
.th-dark-brown {
  /* basic theme colors */
  --background-color: #342F2E;
  --medium-color: #FED9D8;
  --text-color: #FFEAE9;
  --action-color: #2C9957;
  --error-color: #FD6D67;
  /* other colors created by theme generator, about 20 colors */
  /* but it's still possible to customize them */
  --base-border-color: ...;
  --accent-border-color: ...;
}
```

**Comment by antelle** [comment] 2017-04-23 20:58
Actually, I just found a way to mix, shade and tint colors with `hsla` and `calc`, so I'll try to make it even without the need to specify additional colors, with default dependent colors calculated automatically. Not sure about performance, but probably it shouldn't be calculated only once, I'll check it.

**Comment by EnricoMonese** [comment] 2017-04-24 12:04
Also right now it seems pretty hard to make a plugin add something in the settings so maybe that will need some work too.

**Comment by antelle** [comment] 2017-04-24 16:26
Yes, plugins should have their own settings page and api to configure these settings, like in Atom. Will be there in future releases.

**Comment by antelle** [comment] 2017-04-24 21:56
Pushed css variables support. Now creating a theme is as easy as overriding variables.
I tried to implement transformations with calc(var()), but it's too early: I managed to do it for Chrome, but id didn't work smoothly everywhere. So, we'll have to generate themes now. I'll create a simple page for theme generation later, it should just include all controls we have and color pickers for 5 basic colors.

**Comment by antelle** [comment] 2017-04-26 20:17
Here's a real-life working example of theme: https://github.com/keeweb/keeweb/blob/develop/plugins/examples/rainbow-theme/plugin.css

**Comment by EnricoMonese** [comment] 2017-04-26 22:24
Maybe for now the _theme builder_  could be integrated in the keeweb-plugin cli. And later on the cli functionality could be integrated in the plugins section allowing users to easily get started with their own plugin.

**Comment by antelle** [comment] 2017-04-27 05:49
Oh, we can create a plugin which allows to build plugins. And add a button 'build your own plugin', which will download it.
It's a good idea to integrate theme builder with cli.
They can be calculated, right, I'm thinking, how to do it better, to:
1. avoid calculation for known themes
2. allow to override calculated colors
3. don't duplicate scss code in js
4. support all browsers

I have some ideas and will try to validate them tonight, maybe it will work.

**Comment by antelle** [comment] 2017-04-27 10:12
Pushed runtime property calculation.
Updated theme example: https://github.com/keeweb/keeweb/blob/develop/plugins/examples/rainbow-theme/plugin.css

**Comment by antelle** [comment] 2017-04-29 14:56
Here's a plugin creator with theme designer: https://plugins.keeweb.info/create-plugin.html

![theme](https://cloud.githubusercontent.com/assets/633557/25556438/d2741668-2cfc-11e7-9427-5509c034f1df.png)
