### ISSUE TITLE
SCP support

### ISSUE THREAD

**Issue by Enlightments** [keeweb/keeweb#1624] opened 2020-11-07 18:04 UTC
Hi guys

First, I want to thank you for your awesome product (it really solved my conspiracy theory problem).

I would like to request a feature in which the keeweb can remotely read from an SSH server using SCP or something similar.
So that we can simply host our password files on a private VPS without needing to set up a WebDav.

Thank you all and keep going

**Comment by antelle** [comment] 2020-11-07 18:06
Hi! For now that's not planned and most likely won't be. You can create a plugin with this feature though.

**Comment by antelle** [comment] 2020-12-31 18:14
Duplicate of #103

**Closed by antelle** 2020-12-31 18:14 UTC
Labels: plugin-request, storage
