### ISSUE TITLE
Disable auto-type for a specific entry

### ISSUE THREAD

**Issue by nnjeremy** [keeweb/keeweb#377] opened 2016-09-21 11:56 UTC
- what were your actions?
  option . Enable auto-type for this Entry
- what was wrong?
  Auto-type is disable be still used in the "Auto-type: Select" interface

![keeweb1](https://cloud.githubusercontent.com/assets/1242162/18709800/24772be2-8002-11e6-8a93-4fd8d20e0249.png)

![keeweb2](https://cloud.githubusercontent.com/assets/1242162/18709798/217619e4-8002-11e6-89bf-7e84245e885e.png)

Important note : auto-type use the title and in this title we have "- Google Chrome" for Google Chrome (" - Mozilla Firefox" for firefox, etc...) but this is not the title of the current web page. Is it possible to remove this (" - Google Chrome") for the auto-type detection ?
This is why I want to disable auto-type for my google entry, because I have " - Google Chrome" in the title so I always have to choose manually the correct entry.
- app version
  KeeWeb v1.3.2 (fb3b741, 2016-09-13)
  Environment: electron v1.3.3
  User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.2 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
- please, open dev tools in your browser and attach output log from Console tab 
  [DEBUG] 2016-09-21T11:47:00.611Z [auto-type] Auto type event 
  [DEBUG] 2016-09-21T11:47:00.616Z [auto-type] Get window title
  [INFO ] 2016-09-21T11:47:00.667Z [launcher] spawn xdotool: 0, 49ms
  123456 - Google Chrome
  [DEBUG] 2016-09-21T11:47:00.667Z [auto-type] Window title 123456 - Google Chrome 
  [DEBUG] 2016-09-21T11:47:04.452Z [auto-type] Entry selected [object Object]
  [DEBUG] 2016-09-21T11:47:04.457Z [auto-type] Hide window
  [DEBUG] 2016-09-21T11:47:04.563Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
  [DEBUG] 2016-09-21T11:47:04.564Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
  [DEBUG] 2016-09-21T11:47:04.565Z [auto-type] Resolved [*******_,key:tab,[_,_,_,_,_,_,_,*],key:enter]
  [INFO ] 2016-09-21T11:47:04.760Z [launcher] spawn xdotool: 0, 193ms
  [INFO ] 2016-09-21T11:47:04.855Z [launcher] spawn xdotool: 0, 94ms
  [INFO ] 2016-09-21T11:47:04.941Z [launcher] spawn xdotool: 0, 86ms
  [INFO ] 2016-09-21T11:47:05.026Z [launcher] spawn xdotool: 0, 85ms
  [INFO ] 2016-09-21T11:47:05.107Z [launcher] spawn xdotool: 0, 81ms
  [INFO ] 2016-09-21T11:47:05.188Z [launcher] spawn xdotool: 0, 81ms
  [INFO ] 2016-09-21T11:47:05.268Z [launcher] spawn xdotool: 0, 80ms
  [INFO ] 2016-09-21T11:47:05.350Z [launcher] spawn xdotool: 0, 82ms
  [INFO ] 2016-09-21T11:47:05.432Z [launcher] spawn xdotool: 0, 82ms
  [INFO ] 2016-09-21T11:47:05.466Z [launcher] spawn xdotool: 0, 33ms
  [DEBUG] 2016-09-21T11:47:05.466Z [auto-type] Complete 903ms

**Comment by Narvey** [comment] 2016-10-28 17:47
Also note that many websites just have "Login" as the title of the login page (as dumb as that sounds, it does happen) and there is no way to make global auto-type work for those (naming my entry "Login" sure wouldn't make sense).

This combined with the OP's problem means you **ought to use the URL field rather than the window title** to perform auto-type.

I'll just use Ctrl-T for now because it is more flexible and more accurate.

**Comment by antelle** [comment] 2016-10-28 17:58
We do use URL for auto-type matching.
The problem is, there's no standard way to get URL from browser, so sometimes we have only title available.

**Comment by Narvey** [comment] 2016-10-31 21:08
yeah, you could use xdotool to do Ctrl-L and then Ctrl-C, but that is pretty ugly (I would be OK with it, but others might not like their clipboard stomped on).

**Comment by nopivnick** [comment] 2016-10-31 22:59
> The problem is, there's no standard way to get URL from browser, so sometimes we have only title available.

I rely on browser plugins that append the domain name to the title of the tab for better use of auto-type in KeePass:

- [Url in title](https://chrome.google.com/webstore/detail/url-in-title/ignpacbgnbnkaiooknalneoeladjnfgb)

- [Add URL to Window Title](https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/?src=userprofile)

they seem to help some with KeeWeb at times though not as reliably because, unlike KeePass, there doesn't seem to be any way to add additional auto-type targets and/or modify them with wildcards in KeeWeb.

so by way of example, login prompts don't always reside at the root of the domain, may reside at a different subdomain, or some other variation thereof.

to address this I make it a habit to create an auto-type target in KeePass that includes just the domain name with the tld and '*' wildcards on either side (e.g., *github.com*). that way the auto-type target is a lot more forgiving.

perhaps the best solution to @nnjeremy 's use case would be a new feature request: the use of auto-type targets -- separate from the standard url field -- with the ability to add wildcards.

![screenclip](https://cloud.githubusercontent.com/assets/688639/19874234/1b3a2e28-9f9a-11e6-9aa4-0f658e022f4e.png)

**Comment by antelle** [comment] 2016-11-01 04:14
> Ctrl-L and then Ctrl-C

No, we don't execute any actions.
On Windows and Mac, we [get url](https://github.com/keeweb/keeweb/blob/master/helper/win32/src/KeeWebHelper/WindowHelper.cs) using accessibility API and this works almost everywhere, with the only exception when the user has denied access to this API (there's a rather confusing request on mac, looking like 'Allow KeeWeb to rule the world and burn your computer?'), or browser doesn't implement this API (Firefox on Mac). Unfortunately, due to platform priorities and extra complexity, we don't use accessibility API on Linux. It's available but I don't know if browsers implement, i.e. could we get url this way. If there's any public tool (like xdotool) which allows to get url, please let me know.

**Comment by nnjeremy** [comment] 2016-11-07 09:55
@nopivnick It's a good idea to add this extension to the browser when keeweb can't get current URL...
It's a good alternative for linux users ;)  !!!

**Comment by antelle** [comment] 2016-11-07 10:22
yes, extension would be the best way to do this, but its development and integration to all browsers requires a considerable amount of work.

**Comment by nnjeremy** [comment] 2016-11-07 10:37
I have try to use "Url in title" in Google Chrome during 3h and it's seems to work perfectly.
So if you don't have the time to create a specific keeweb extension (yes this is an other project and a lot of work) 
An extension like this already exist and can help users ;)

But this trick do not resolve the initial issue (disable auto-type for a specific entry)

Thanks for your work, have a good day

**Comment by antelle** [comment] 2016-11-07 10:41
Yes, original issue will be fixed in the next release, of course (url discussion is just offtopic for this issue). Not everyone would be glad to see url in title. Ideal extension would work in chrome / firefox / other browsers and provide api for keeweb to get url.

**Closed** 2017-02-04 15:22 UTC
Labels: auto-type, bug, desktop, enhancement
