### ISSUE TITLE
KeeWebHTTP doesn't search by base domain name

### ISSUE THREAD

**Issue by Akeboshiwind** [keeweb/keeweb#741] opened 2017-09-23 13:57 UTC
I'm having a problem with KeeWeb where I'll have the website set to the base domain name (e.g. riotgames.com) on the KeeWeb entry but the login page will have a different subdomain (e.g. auth.riotgames.com) and when chromeIpass searches for it nothing shows up unless I change the website to the full subdomain.

This isn't too annoying for most cases, but in some cases the same username and password get's used for multiple subdomains (like my uni website).

Steps to reproduce:
1. Setup an account with riotgames.com
2. Add account to keeweb with the website being 'riotgames.com'
3. Visit the login page.
4. The password isn't auto-filled
5. Change the website to 'auth.riotgames.com'
6. Refresh the page
7. The password is auto-filled

There's also another more minor case when a website will use the same username and password over multiple base domains. A solution to that might be to add in references like keepass, or possibly the website field could be comma separated.

**Comment by antelle** [comment] 2017-09-23 14:05
Duplicate of #648

**Closed by antelle** 2017-09-23 14:05 UTC

**Comment by Akeboshiwind** [comment] 2017-09-23 14:07
Ah, should have searched harder.

Glad this is being looked into :)
