### ISSUE TITLE
Global shortcut for Auto-type

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#259] opened 2016-07-11 20:25 UTC
I just checked 1.2 and Auto-type (the most longed-for feature for me) works great. It would actually be nice if there would be the chance do define a global keyboard shortcut to use Auto-type. It's what really makes KeePass fast and easy to use everywhere.

I know we had a short discussion about detecting programs/URLs for Auto-type usage in the [original issue](194). Did that feature just not make it into the release or has it been abandoned entirely?

(And thanks for the great work with 1.2 again!)

**Comment by antelle** [comment] 2016-07-11 20:29
Hello,
This will be implemented in v1.2, and it's already done partly.
I planned to include it in v1.2 release before but unfortunately, I hadn't enough time. So I decided to release v1.2 faster and improve auto-type later in v1.3.

**Comment by Loilo** [comment] 2016-07-11 20:55
That's amazing news, thanks. :)

**Comment by benzkji** [comment] 2016-07-14 08:10
Hi, just to clear things up(forgive me if I mix and match or whatever, just downloaded keeweb): Autotype with system wide keyboard shortcut is not implemented in 1.2, but will be in 1.3 (as described here: https://github.com/keeweb/keeweb/wiki/Auto-Type).

There is a cmd-T shortcut (when in keeweb), but it just opens Safari with my homepage? What was this intended to do?

Copying data from keeweb when it's in background works perfect, btw...!

**Comment by antelle** [comment] 2016-07-14 10:38
Global shortcut will be <kbd>Ctrl+Alt+T</kbd> on mac and <kbd>Shift+Alt+T</kbd> on other os.

**Comment by antelle** [comment] 2016-08-07 18:29
Status update: global shortcuts for auto-type have been implemented, v1.3 will have it. If the app was locked, there will be unlock window, after which entry list will pop up.

**Comment by Loilo** [comment] 2016-08-08 08:37
That will be an amazing improvement. :)
It also indicates though that any kind of automatic selection of an entry (after the global shortcut) will not be in 1.3, right?

**Comment by antelle** [comment] 2016-08-08 08:49
> automatic selection of an entry 

what do you mean?

**Comment by Loilo** [comment] 2016-08-08 10:37
Sorry, I'm repeatedly referring to KeePass without mentioning it.
KeePass' AutoType allows to assign Entries to programs (via their title if I'm not mistaken) resp. if no assignments are made it matches the entry data against the currently focused window's title to pick the right entry without even having to ask the user.

Since there already was some discussion about [how to detect URLs](https://github.com/keeweb/keeweb/issues/194#issuecomment-213773690) I assume that some kind of feature in that direction is planned, but your announcement sounds like for 1.3 there's no implementation of this idea and the global shortcut rather shows a list of all KeeWeb entries.

**Comment by antelle** [comment] 2016-08-08 10:46
It works in this way: it tries to find matching entries by url and title. If there are no (or more than one) matching entries show entry selection window, with entries sorted by best match ([more details about sorting and filtering](https://github.com/keeweb/keeweb/issues/285#issuecomment-237031202)). If exactly one entry has been found, there will be no selection window. I'm thinking about 'I'm feeling lucky' setting which will always select the best match, we'll see if we need it, I don't know for now.

**Comment by jhass** [comment] 2016-08-08 11:01
015785769575

**Comment by Loilo** [comment] 2016-08-08 11:08
Wow - sounds great that this will already be implemented. 👍

**Comment by antelle** [comment] 2016-08-08 18:21
Auto-type is finished for v1.3.
If you would like to test it, please let me know, I'll make a beta build.

**Comment by Loilo** [comment] 2016-08-08 18:25
I'd love to test it on my Windows machine.

**Comment by antelle** [comment] 2016-08-09 02:57
Here's the beta: http://antelle.net/files/KeeWeb-1.2.4-beta.win.x64.zip

**Comment by pwFoo** [comment] 2016-08-09 09:36
I have some problems with the entry detection. Entry isn't identified by title or url an suggestions seems to start with "a" instead of best hit (maching title or url).
But I'll do some more testing :+1:

**Comment by antelle** [comment] 2016-08-09 09:39
@pwFoo you can look in log, to check the reason of this. most probably url was not detected

**Comment by pwFoo** [comment] 2016-08-09 09:54
Yes, thanks. Your right. 

I think You should ignore url parameters like `?return=%2F` (referer page for example) and browser title extensions like `- Google Chrome`. 
Could you add domain match instead of full url only? And a partial title match (because browser add the browser name string...).

**Comment by antelle** [comment] 2016-08-09 09:56
It's already matching by domain.
Please write here: 
- tab url (as returned to keeweb. from dev console)
- tab title (as returned to keeweb. from dev console)
- entry url (which you expect to be matched)
- entry title (which you expect to be matched)

**Comment by pwFoo** [comment] 2016-08-09 10:08
No selection window / match with the downloaded beta package. No action with global auto type. Changed inside the app to dev / beta version and there is a auto type action, but without matching entry, just a manual select list.

No url field (domain only, proto + domain and full domain with path / params) or title match. Verified browser and entry title is the same. Strange... Tested with Chrome @ Windows 10.

**Comment by Loilo** [comment] 2016-08-11 21:00
I'm testing the Beta you posted for Windows right now. Auto Type works kind of, but the Detection of the URL (which worked fine on OS X) does not. The app does not even seem to try:

> 2016-08-11T20:58:44.951Z [auto-type] Auto type event null
> 2016-08-11T20:58:44.953Z [auto-type] Get window title
> 2016-08-11T20:58:45.565Z [launcher] spawn C:\Program Files\KeeWeb\resources\app\helper\win32\KeeWebHelper.exe: 0, 613ms
GMX: Email-Adresse, FreeMail, De-Mail & Nachrichten – Opera
https://www.gmx.net/
> 2016-08-11T20:58:45.566Z [auto-type] Window title GMX: Email-Adresse, FreeMail, De-Mail & Nachrichten – Opera https://www.gmx.net/

**Comment by antelle** [comment] 2016-08-11 21:06
Hm, what in the log you posted above makes you think that the app does not try to detect url?
I see that the url is detected ok, which is gmx.net.
Or you mean, it detects url and after it, no auto-type is performed? What's going on in the log after 'Window title:' record?

**Comment by Loilo** [comment] 2016-08-11 21:11
...obviously seeing the literal URL printed out didn't prevent me from thinking it was not detected. Meh. I'm probably to tired to write bug reports. :)
The logs are complete, no other ones are shown and the App will tell me that there are no matches (though there clearly are).

**Comment by antelle** [comment] 2016-08-11 21:15
So, the url and title were both detected in your case (otherwise they wouldn't have appeared in keeweb logs). Are you viewing logs from dev console or from app Settings/Advanced? Dev console can sometimes have errors which are absent in Settings/Advanced, maybe it's your case.
Hmmm, that's really strange that Window title is the last record, could you please paste title and url of the entry which should have been matched by these parameters? I'll check calculated rank value for this entry. Something definitely went wrong here.

**Comment by Loilo** [comment] 2016-08-11 21:29
I view the logs in dev tools. I just took a look into Settings/Advanced logs as well (after changing the app theme since in "White" theme logs are unreadable due to a really light font color) and they don't tell anything the dev tools wouldn't.

The entry's title is "GMX", its URL is "gmx.net". It does not matter too much though since the issue happens with every single webpage I visit (also in any Browser) with the same kind of logs.

Just to add that, I'm on Windows 10 (installed Anniversary Update) and used the .zip file from above.

(btw it would be great if you could provide another zip with the fixed #308 since that would allow for much further Auto Type testing :+1:)

**Comment by benzkji** [comment] 2016-08-12 12:51
how can I test auto type on mac? do you need to make a MAC build? @antelle

**Comment by antelle** [comment] 2016-08-12 18:34
Uploaded new beta build for [windows](http://antelle.net/files/KeeWeb-1.2.4-beta.win.x64.zip) and [mac](http://antelle.net/files/KeeWeb-1.2.4-beta.mac.dmg).

**Comment by benzkji** [comment] 2016-08-13 07:05
I cannot open Files from Dropbox in the Beta build, if I click the Icon, it turns, and nothing happens. Is this because the "AppId" (or whatever it is called, dont know the Dropbox API) has changed for beta, or a regression?

**Comment by benzkji** [comment] 2016-08-13 07:05
And thanks, will test with a local file anyway !

**Comment by pwFoo** [comment] 2016-08-14 07:54
Tested latest beta build. It triggers auto type, but it doesn't fill the form inside the active browser window. Instead KeeWeb will be maximized (from minimized / background) and the website passwpord is filled in the KeeWeb search field.
auto type shouldn't change the window focus ;)

**Comment by antelle** [comment] 2016-08-14 08:05
> KeeWeb will be maximized

It is maximized when it shows entry selection dialog, not when there's one matching entry. Is it different for you?

**Comment by antelle** [comment] 2016-08-14 08:19
Oh yes, this appeared in last beta, fixed wrong window focus. Fixed, uploaded new beta build.
We have to create beta channel... it's hard to download and update them manually.

**Comment by pwFoo** [comment] 2016-08-14 08:25
No selection dialog. App gets maximized and matching entry is filled in the KeeWeb search field instead of the browser / form.


Beta channel is a good idea!

**Comment by antelle** [comment] 2016-08-14 08:34
Yes, thanks for that, I've found the reason and fixed, new beta doesn't have this bug.

**Comment by pwFoo** [comment] 2016-08-14 08:43
Great! All will test it as soon as the new beta is available :)

**Comment by antelle** [comment] 2016-08-14 08:54
It's already deployed

**Comment by pwFoo** [comment] 2016-08-14 09:00
Auto type works fine on Win10 with the latest beta! :+1:

**Comment by pwFoo** [comment] 2016-08-14 11:02
auto type entry detection based on domain works fine, but it looks like title doesn't work?

**Comment by antelle** [comment] 2016-08-14 11:07
Please paste window title and url (from keeweb logs, starting with `[auto-type] Window title`) and entry title and url.
A simple case works: e.g. when I'm in a text editor titled Untitled, and there's and entry Untitled, it's matched.

**Comment by pwFoo** [comment] 2016-08-14 11:30
Browser title bar: "My Domain Title"
KeeWeb detects: "My Domain Title - Google Chrome" 

Could "[...] - Google Chrome" a problem to match an entry?

I have a entry with changed domain. Old domain redirects to the new one. So no domain match is possible.
So it should match title "DSA-Forum" I think...
```DSA-Forum • Persönlicher Bereich • Anmelden - Google Chrome
www.dsaforum.de/ucp.php?mode=login
[DEBUG] 2016-08-14T11:26:56.665Z [auto-type] Window title DSA-Forum • Persönlicher Bereich • Anmelden - Google Chrome www.dsaforum.de/ucp.php?mode=login```

I get an empty selection window instead of the matching one. 
Changed the domain (dsa4forum.de) match the new domain name (dsaforum.de) and auto type works again.

So it should by a problem with title match?

**Comment by antelle** [comment] 2016-08-14 11:34
> I have a entry with changed domain.

Yes, this is by design. If you remove the domain, it will match. If we can detect the url and domain in entry and this url mismatch, we think that it would be potentially dangerous to perform auto-type for such entry automatically. To enable auto-type for this entry on this domain, add url into any entry field.

**Comment by pwFoo** [comment] 2016-08-14 11:37
Hm, you're right! It's dangerous to perform auto type for such a entry... 
Domain match should be fine for most cases. 

It isn't a bug it's a (security) feature!!!

Thanks!

**Comment by Loilo** [comment] 2016-08-14 17:19
Okay, this also solved my problem of not finding matching entries. I used "gmx.net" in the "Website" field but it actually was "www.gmx.net".
While I actually agree with the security feature you mentioned, wouldn't it be worth thinking about an exception for www aliases?

**Comment by antelle** [comment] 2016-08-14 17:26
Yes, sure we must add an exception for www.
Added, deployed to beta. If you click `use beta for one time` button in beta build, it should work.

**Comment by Loilo** [comment] 2016-08-14 17:32
Works like a charm. :+1:

**Comment by antelle** [comment] 2016-08-14 20:42
> @benzkji
> I cannot open Files from Dropbox in the Beta build

Fixed it, Dropbox is working in latest beta.

**Comment by rholloway** [comment] 2016-08-31 15:35
For me when trying beta I get 'helper not found' when I run auto type. Not sure what is going on there.

**Comment by antelle** [comment] 2016-08-31 16:25
It requires native helper, so Beta button won't work. Latest beta: [mac](http://antelle.net/files/KeeWeb-1.3.0-beta.mac.dmg), [win](http://antelle.net/files/KeeWeb-1.3.0-beta.win.x64.zip).

**Closed** 2016-09-01 18:36 UTC
Labels: auto-type, desktop, enhancement

**Comment by Tephnos** [comment] 2016-11-19 05:32
Hi. Saw this recently when looking for a new app to replace 1Pass, and having been used to 1Password's autofill, I noticed on KeeWeb that if you're on the right page, you need to have the login box highlighted first, or nothing will happen (or click some random thing).

Is this normal Keepass auto type behaviour? Presuming in order to 'locate' the correct boxes for password entry it would probably require a browser extension? Just making sure.

**Comment by antelle** [comment] 2016-11-19 06:21
Yes, login box must have focus, it's not searched automatically.

**Comment by Tephnos** [comment] 2016-11-19 06:24
Thanks man, noted.

Since we're here and this is already closed, I do have a couple more questions I'm not seeing when looking around, unrelated to this issue.

1.) Downloading/Uploading favicons always leaves them on the selectable list. This gets pretty cluttered and I see no way of deleting them from that list. Is it possible?

2.) Any way to stop new entries trying to suggest autofills for 'User'? Not dealbreaking, but a bit annoying when you have a lot of different Users and it is trying to suggest them all.

Very impressed with this so far though.

**Comment by antelle** [comment] 2016-11-19 06:28
Why do you post it here? Everything subscribed to this issue will be notified about your comments.
1. will be deleted automatically, when the icon is not used
2. but it's not inserted automatically, it's just a hint. also, it will disappear once you start typing. It should not be annoying.
