### ISSUE TITLE
Auto-Type issues on application windows 

### ISSUE THREAD

**Issue by lescar** [keeweb/keeweb#426] opened 2016-10-30 06:01 UTC
Version: 1.3.3 (52701af)

I'm not sure if I should raise an issue for each. Apologies if this format is wrong.

When I auto-type into the steam login window:
1. keeweb does not find my steam entry. Works fine on macpass.
2. Once I select the Steam-Login entry, keeweb does not apply {tab} and pastes everything in the username field.
3. If a username string is already selected, keeweb does not overwrite it on auto-type.
4. Auto-Type into terminals/ssh does not work (potentially because it would need feature 1, see below)

Features:
1. Linking a window in focus to a password entry is not implemented - which might be a workaround.
2. Presenting auto-type config per entry by default, especially as this is one of the most important uses of the tool, would be appreciated.

**Comment by antelle** [comment] 2016-10-30 07:04
Hello,
1. please provide logs, what do we get from target window: title, url?
2. that's strange, perhaps tab key is processed specially on this website, needs investigation. you mean steam website, right?
3. it's by design. you can add {clearfield} to the beginning of the auto-type sequence, then it should clear old value
4. need logs

features:
1. I didn't get it, sorry. What's linking?
2. we don't have any auto-type configs, what do you mean?

**Comment by lescar** [comment] 2016-10-30 10:41
Hi antelle, 

Thanks for your reply.

1. It's not a website, it's the actual software.
2. I mean the software.
3. Ah, thanks!
4. Where do I find the logs on mac osx?

Features:
1. It's a KeePass / MacPass functionality. You can select a window where it should auto-type in and it remembers the window title. So once it's setup, it always works regardless of the window title. It goes that far, that I can auto-type into programs running in my VM. 
2. The by default collapsed auto-type settings of the entry.

**Comment by antelle** [comment] 2016-10-30 10:48
2. then it would be tough to fix, help is appreciated. I'm pretty sure, it's related to app processing keyboard events
3. app settings &rarr; advanced &rarr; show dev tools &rarr; console tab

features:
1. we should add a button into window title field, once we support per-window auto-type settings
2. no, we'll not show auto-type settings by default, most probably you won't need to modify them at all. Also, once setup is done, you won't change it. Also, there are group- and file-level settings, so you can change global auto-type sequence, for example. Maybe this will work for you.

**Comment by Krzywusek** [comment] 2017-02-14 21:32
Is there any ETA regarding per window auto type? I would love to move to KeeWeb from KeePass, but currently this feature is preventing me from moving. Also steam app issue reported by @lescar seems to be related to KeeWeb only, as on KeePass it is working just fine. What's the difference in auto-type managing in compare to KeePass?

**Comment by antelle** [comment] 2017-02-14 21:41
I guess, per-window auto-type won't help here. There's a huge difference: KeePass has [lots of](https://github.com/dlech/KeePass2.x/blob/VS2015/KeePass/Util/SendInputExt/SiEngineWin.cs#L217) (disclaimer: this is a link to keepass source code github mirror, not official source, but it's the same) auto-type hacks for different apps, we don't go that far and just apply the same logic. Also auto-type methods are different.

**Comment by Phreeak** [comment] 2017-05-25 18:06
Hi, 
i have also problems with steam login.
When i change the autotype sequence to "{USERNAME}{TAB}"
everything works... username is filling and the cursor jumps in the password field.

+++ Username = *MyUsername* +++
+++ Password = *empty* +++

###############################################
Steam-Login
[DEBUG] 2017-05-25T18:01:09.659Z [auto-type] Window title Steam-Login undefined
[DEBUG] 2017-05-25T18:01:14.762Z [auto-type] Entry selected {"id":"0b10a722-5f09-3a3b-84b0-9e7ab311ffc1:qPv5OfXgPnEtClFzYECJPA==","uuid":"qPv5OfXgPnEtClFzYECJPA=="}
[DEBUG] 2017-05-25T18:01:14.764Z [auto-type] Hide window
[DEBUG] 2017-05-25T18:01:14.872Z [auto-type] Start {USERNAME}{TAB}
[DEBUG] 2017-05-25T18:01:14.872Z [auto-type] Parsed [op:USERNAME,op:TAB]
[DEBUG] 2017-05-25T18:01:14.873Z [auto-type] Resolved [****************,key:tab]
[INFO ] 2017-05-25T18:01:14.948Z [launcher] spawn C:\Users\*Username*\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 75ms
[DEBUG] 2017-05-25T18:01:14.949Z [auto-type] Complete 76ms
#########################################

When i take this sequence "{USERNAME}{TAB}{PASSWORD}" Keeweb fills my username and password directly in the username field ?!

+++ Username = *MyUsernameUWFi8h39fh87wgb5923g54h032hj5g03* +++
+++ Password = *empty* +++

#########################################
Steam-Login
[DEBUG] 2017-05-25T18:02:05.737Z [auto-type] Window title Steam-Login undefined
[DEBUG] 2017-05-25T18:02:12.706Z [auto-type] Entry selected {"id":"0b10a722-5f09-3a3b-84b0-9e7ab311ffc1:qPv5OfXgPnEtClFzYECJPA==","uuid":"qPv5OfXgPnEtClFzYECJPA=="}
[DEBUG] 2017-05-25T18:02:12.708Z [auto-type] Hide window
[DEBUG] 2017-05-25T18:02:12.818Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}
[DEBUG] 2017-05-25T18:02:12.818Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD]
[DEBUG] 2017-05-25T18:02:12.818Z [auto-type] Resolved [****************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*]]
[INFO ] 2017-05-25T18:02:12.891Z [launcher] spawn C:\Users\*Username*\AppData\Roaming\KeeWeb\helper\win32\KeeWebHelper.exe: 0, 73ms
[DEBUG] 2017-05-25T18:02:12.891Z [auto-type] Complete 74ms
##################################################

strange.....

@antelle 
is there a solution for this?

**Comment by antelle** [comment] 2017-05-25 18:08
There's no known solution for now, I need some help with it...

**Comment by antelle** [comment] 2021-03-08 17:56
This may be fixed in v1.17, please reopen if it still repeats.

**Closed by antelle** 2021-03-08 17:56 UTC
Labels: auto-type, bug, desktop, enhancement, help wanted
