### ISSUE TITLE
Auto-type doesn't work properly when triggering from full page mode in Mac.

### ISSUE THREAD

**Issue by tobefound** [keeweb/keeweb#401] opened 2016-10-06 07:51 UTC
When in Mac using the auto-type command (ctrl+alt+t) from the website login page and there are multiple viable options that match, KeeWeb presents the options dialog as it should. However, if the browser is in full page mode, on a Mac, this full page mode is on a "different" screen making KeeWeb fail to know where to auto-type the selected entry. It instead uses the topmost window in the "original" screen where KeeWeb itself is running. Which clearly is a problem. :)

**Comment by antelle** [comment] 2016-10-06 07:57
duplicate of #307

**Closed by antelle** 2016-10-06 07:57 UTC
Labels: auto-type, bug, desktop, duplicate
