### ISSUE TITLE
Can't access KDBX4 file if Argon2 memory setting is higher than a particular value

### ISSUE THREAD

**Issue by onyhow** [keeweb/keeweb#532] opened 2017-02-17 07:34 UTC
- what were your actions?
Trying to open KDBX4 file
- what was wrong?
If the memory setting for Argon2 is 123MB or higher, the program throws error and you cannot access the file even with the right password. Use AES encryption in all cases.

Initially I tried to access my 256MB setting personal database, but it throws error. Reducing memory requirement to 128MB still throws error, but I can access it when memory is down to 64MB. So I got this idea to try creating several databases with 1 pass and 2 parallelism with various memory requirements (all of them are newly created via mainline KeePass). Initially thought it's 100MB that's the breakpoint...turns out that if memory is 122MB I can still open KDBX4 file normally, but file with 123MB setting or higher immediately throws error when trying to access. Also, said error appears whether the password you entered is right or not.

- app version
1.4.0

- your user-agent (from Settings/Help section)
KeeWeb v1.4.0 (c651343, 2017-02-04)
Environment: electron v1.4.15
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36

- does it happen on Demo or New database?
New database

- if you are using a test db without your personal data, please attach it

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)
[INFO ] 2017-02-17T07:31:47.740Z [updater] Next update check will happen in 85270s
[INFO ] 2017-02-17T07:31:53.295Z [open:test123] File open request
[INFO ] 2017-02-17T07:31:53.296Z [open:test123] Open file from supplied content
[DEBUG] 2017-02-17T07:31:53.314Z [argon2] Loading asm.js fallback runtime
[DEBUG] 2017-02-17T07:31:53.372Z [argon2] Fallback runtime loaded 57ms
[ERROR] 2017-02-17T07:31:53.378Z [file] Error opening file   abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:17586)
    at stackTrace (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:17757)
    at abort (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:12:3776)
    at abortOnCannotGrowMemory (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:18639)
    at enlargeMemory (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:19084)
    at Wa (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:68191)
    at Ra (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:57250)
    at ya (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:13627)
    at Ga (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:18195)
    at sa (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:11647)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
[ERROR] 2017-02-17T07:31:53.379Z [open-view] Error opening file abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:17586)
    at stackTrace (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:17757)
    at abort (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:12:3776)
    at abortOnCannotGrowMemory (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:18639)
    at enlargeMemory (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:1:19084)
    at Wa (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:68191)
    at Ra (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:57250)
    at ya (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:13627)
    at Ga (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:18195)
    at sa (eval at <anonymous> (file:///C:/Users/Test/Desktop/Useful%20stuff/Apps/KeeWeb-1.4.0.win.x64/resources/app/index.html:20:26238), <anonymous>:5:11647)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by antelle** [comment] 2017-02-17 07:47
Duplicate of #513
Quick solution: tweak other parameters, instead of memory.

**Closed by antelle** 2017-02-17 07:47 UTC
