### ISSUE TITLE
'@' sign typed as 'q'

### ISSUE THREAD

**Issue by AxelRHD** [keeweb/keeweb#772] opened 2017-11-04 22:47 UTC
Hi,

I have a problem withe the autofill-function (German keyboard layout). It prints the '@' of Mail-Address as 'q'.

KeeWeb v1.5.6 (10229e7, 2017-08-31)
Environment: electron v1.6.11
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.6 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36

**Comment by antelle** [comment] 2017-11-04 22:50
Hi, this is a duplicate of #441

**Closed by antelle** 2017-11-04 22:50 UTC
