### ISSUE TITLE
No save of changes anymore

### ISSUE THREAD

**Issue by nudeldieb** [keeweb/keeweb#1242] opened 2019-08-25 06:54 UTC
Hi,
it seems that the new version for MacOS doesn't save the password db anymore. Neither with automatical lock after quitting the app in General Prefs, nor with save by hand in the password db itself.
DB resides locally in my home file system and is writable 

KeeWeb v1.9.2 (54430cd8, 2019-08-22)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.1 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Comment by nudeldieb** [comment] 2019-08-25 07:01
.edit.
Saving manually does work, it just takes some time ...

**Comment by antelle** [comment] 2019-08-25 10:47
Hi! I can't reproduce this unfortunately, but it sounds very weird. Could you please check what's there in logs when it should be autosaved?

**Comment by antelle** [comment] 2019-08-25 20:40
I tried closing the app in different ways, but looks like save is working. Could you please share the way you exit it?

**Comment by antelle** [comment] 2019-09-09 06:33
Please feel free to reopen with more info. I don't see any comments from other people, nor can I reproduce it myself.

**Closed** 2019-09-09 06:32 UTC
Labels: bug, desktop, need info
