### ISSUE TITLE
App randomly comes to the front

### ISSUE THREAD

**Issue by Loilo** [keeweb/keeweb#299] opened 2016-08-08 11:15 UTC
From time to time (not actually often) the KeeWeb app on my OS X system randomly comes to the front and gets focus.

I have no idea why or when this happens and how to reproduce that behaviour. Just want to mention that it happens every once in a while.

**Comment by antelle** [comment] 2016-08-08 17:58
Looks similar to #226
But I'm not able to reproduce it... How often does it happen? Does entire app appear, or just a popup? Does it disappear after it?

**Comment by Loilo** [comment] 2016-08-08 18:48
* It's the entire app that just comes to the front.
* The app is not minimized (still using OS X) but only hidden behind other windows.
* It does not happen very often and it happens very inconsistently maybe 0 to 2 times a day.
* It does not disappear after.
* It does not need any user interaction. This is what actually made me open this ticket. I came back from the bathroom and KeeWeb was in front of my other windows where I definitely had not left it.
* I'm not 100% sure but as far as I can tell it only happens if KeeWeb is actually unlocked, I can't remember of an instance where the window came to the front and prompted me to enter my master password.

**Comment by Loilo** [comment] 2016-08-08 18:55
Now that I have posted an issue I'll have a closer eye on this topic. Maybe I'll be able to narrow the cases of this occurence.

**Comment by antelle** [comment] 2016-08-08 19:45
Hm, if it's opened without any interaction, I guess, it's because of #283 
Most probably it tries to sync and shows a popup. Are there sync attempts in logs during that period?

**Comment by Loilo** [comment] 2016-08-08 19:48
That's possible but I don't know. How would I recognize those?

**Comment by antelle** [comment] 2016-08-08 19:55
It would be written in app logs (Settings - General - Advanced - Show dev tools - Console), or just hit ⌘F12.

**Comment by Loilo** [comment] 2016-08-08 22:41
Okay, I'll investigate on that when I'm back at my Mac at work.

**Comment by Loilo** [comment] 2016-08-11 10:47
Your assumptions were right. It happens the moment where the app tries to do a sync.

> 2016-08-11T10:39:36.929Z [storage-onedrive] OAuth popup opened
index.html:13
> 2016-08-11T10:39:39.197Z [storage-onedrive] OAuth success
index.html:13
> 2016-08-11T10:39:39.197Z [storage-onedrive] Repeat request, try #1 https://api.onedrive.com/v1.0/drive/root:/my/path/on/onedrive.kdbx
index.html:13
> 2016-08-11T10:39:39.409Z [storage-onedrive] Stated /drive/root:/my/path/on/onedrive.kdbx someRandomKeyThatMightBePrivacySensitive 2865ms

With the popup also the whole window does come to the front. So as you stated above, it's probably related to #283.

**Comment by antelle** [comment] 2016-08-11 10:57
ok, let's close this as it's a duplicate

**Closed by antelle** 2016-08-11 10:57 UTC
Labels: bug, desktop, duplicate
