### ISSUE TITLE
Entry is not created in the right group when there is more than one file open

### ISSUE THREAD

**Issue by Gorlem** [keeweb/keeweb#470] opened 2016-12-19 15:37 UTC
I noticed that when I want to create an entry in an group, while having multiple files open, it will use the main group instead of the selected group. It works fine if I only have one file open.

When I create the entry it at first looks like it is in the correct folder, but as soon as I go again in the folder the entry is moved to the main group in the file.

```
KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.1 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36
```

**Comment by antelle** [comment] 2017-02-04 22:01
duplicate of #413, which is already fixed

**Closed by antelle** 2017-02-04 22:01 UTC
Labels: bug
