### ISSUE TITLE
[Bug] Can't open old KeePass database

### ISSUE THREAD

**Issue by FilipJaksic** [keeweb/keeweb#371] opened 2016-09-18 18:12 UTC
Hello,

when I try to open my old database (.kdbx file), the loading circle just spins forever and nothing happens. 

I use the offline Mac version (1.3.2) and am able to open the database with other KeePass alternatives.

Here's the log:

> 2016-09-18T17:51:52.258Z [updater] Next update check will happen in 80342s index.html:formatted:33810
2016-09-18T17:52:10.090Z [open:Passwordscopy] File open request index.html:formatted:33810
2016-09-18T17:52:10.090Z [open:Passwordscopy] Open file from supplied content
Uncaught TypeError: a.replace is not a function
_getDisplayUrl	        @	index.html:formatted:36207
_fillByEntry	                @	index.html:formatted:36139
setEntry                          @	index.html:formatted:36122
k.fromEntry	                @	index.html:formatted:36559
(anonymous function)	@	index.html:formatted:35171
setGroup                     	@	index.html:formatted:35168
m.fromGroup	                @	index.html:formatted:35344
(anonymous function)	@	index.html:formatted:35166
setGroup	                        @	index.html:formatted:35163
m.fromGroup	                @	index.html:formatted:35344
(anonymous function)	@	index.html:formatted:37910
readModel                 	@	index.html:formatted:37908
(anonymous function)	@	index.html:formatted:37818
(anonymous function)	@	index.html:formatted:24622
(anonymous function)	@	index.html:formatted:24899

**Comment by antelle** [comment] 2016-09-18 18:19
Added a fix but the issue is not 100% clear for me.
Please test if it helps for you on [beta](https://beta.keeweb.info/).

**Comment by FilipJaksic** [comment] 2016-09-18 21:33
Now I can open the database, but the names of the entries are some random characters. However, the passwords and the group names remain the same. In addition, some entries lack some fields (e.g. notes, website and the "more..." option).

Also, I observed that whenever I click on one of the entry's name (to edit it) and then click on something else, the name of the entry changes and becomes an larger set of random characters. Checked the console and nothing unusual is displayed. Maybe an GIF of the behavior could help?

**Comment by antelle** [comment] 2016-09-18 21:52
No, there's no need for gif, the case is rather clear: all fields in your db are protected, which is very uncommon, usually only password is protected. We have to handle it properly, now there are a lot of cases where we just assume it's a plain string.

**Comment by antelle** [comment] 2016-09-19 17:22
Hm, I cannot the option to encrypt URLs and usernames in KeePass, so this is kind of edge case...

**Comment by antelle** [comment] 2016-09-19 17:33
Added decoding for all fields, deployed to beta. I think, for usernames and URLs it's ok to disregard 'protected' flag and just decode them always.

**Comment by FilipJaksic** [comment] 2016-09-19 20:09
Actually, I don't remember ever turning such an option on (encrypting all fields). Didn't have any problems with the database using other KeePass alternatives, so I didn't assume that anything might be off.

As I have never worked with encryption (or KeePass code) this might sound dumb, but on the KeePass website it it stated that 
> The complete database is encrypted, not only the password fields. So, your user names, notes, etc. are encrypted, too.

Sorry that I am of no help. But I can, if you want, send you my database tomorrow after I change my personal info into some unrelated words.

**Comment by antelle** [comment] 2016-09-19 20:56
There's no need sending your db, I think everything is fixed now. I've replaced other fields usage. Is it ok for you on beta?
Yes, you're absolutely right, everything is stored encrypted, the issue was with in-memory protection: it makes sense for passwords and other fields like cvv, but not that helpful for titles. However, in kdbx format you can protect titles as well (not sure if it's possible in KeePasss gui, most probably already not). The reason of the bug was a fasle assumption that title is never protected, now it's fixed.

**Comment by FilipJaksic** [comment] 2016-09-19 21:59
As far I as I can see everything seems to be working. As I can see this fix will be available in v1.4, do you maybe know when that will be approximately?

Also I would to say thanks for making such an great app 👍

**Comment by antelle** [comment] 2016-09-20 04:35
let's add this to 1.3.3: 1.4 should be released after new KeePass format is finalized, but I don't know when this will happen

**Closed** 2016-09-20 21:06 UTC
Labels: bug

**Comment by antelle** [comment] 2016-09-20 21:31
release uploaded
