### ISSUE TITLE
Linux Auto-type no longer works in 1.15.x series

### ISSUE THREAD

**Issue by opennomad** [keeweb/keeweb#1564] opened 2020-07-14 18:05 UTC
Auto-type (ALT-SHIFT-T) no longer works in linux. I tested with 1.15.5, 1.15.4, and 1.15.0. None of them appear to run auto-type. When I hit the hot-key it focuses KeeWeb and I can select the password. When I hit enter it goes back to where I triggered the hot-key, but then nothing happens.

1.14.3 does not have that issue.

KeeWeb v1.15.5 (62ea631, 2020-06-13)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.5 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by antelle** [comment] 2020-07-14 18:07
Hi! Is there anything interesting in logs?

**Comment by opennomad** [comment] 2020-07-14 18:37
here's what I see:

```
[DEBUG] 2020-07-14T18:33:30.546Z [auto-type] Hide window
[DEBUG] 2020-07-14T18:33:30.653Z [auto-type] Getting window info
[INFO ] 2020-07-14T18:33:30.670Z [launcher] spawn xdotool: 0, 18ms
us-east-1.signin.aws.amazon.com - Amazon Web Services Sign-In - Mozilla Firefox
85983235
[DEBUG] 2020-07-14T18:33:30.671Z [auto-type] Window info 85983235 us-east-1.signin.aws.amazon.com - Amazon Web Services Sign-In - Mozilla Firefox null
[INFO ] 2020-07-14T18:33:30.671Z [auto-type] Active window matches
[DEBUG] 2020-07-14T18:33:30.671Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2020-07-14T18:33:30.672Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2020-07-14T18:33:30.673Z [auto-type] Resolved [********,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2020-07-14T18:33:30.880Z [launcher] spawn xdotool: 0, 207ms
[INFO ] 2020-07-14T18:33:30.927Z [launcher] spawn xdotool: 0, 46ms
[INFO ] 2020-07-14T18:33:31.003Z [launcher] spawn xdotool: 0, 76ms
[INFO ] 2020-07-14T18:33:31.078Z [launcher] spawn xdotool: 0, 74ms
[INFO ] 2020-07-14T18:33:31.152Z [launcher] spawn xdotool: 0, 74ms
[INFO ] 2020-07-14T18:33:31.226Z [launcher] spawn xdotool: 0, 74ms
[INFO ] 2020-07-14T18:33:31.299Z [launcher] spawn xdotool: 0, 72ms
[INFO ] 2020-07-14T18:33:31.374Z [launcher] spawn xdotool: 0, 75ms
[INFO ] 2020-07-14T18:33:31.473Z [launcher] spawn xdotool: 0, 98ms
[INFO ] 2020-07-14T18:33:31.579Z [launcher] spawn xdotool: 0, 106ms
[INFO ] 2020-07-14T18:33:31.674Z [launcher] spawn xdotool: 0, 95ms
[INFO ] 2020-07-14T18:33:31.754Z [launcher] spawn xdotool: 0, 79ms
[INFO ] 2020-07-14T18:33:31.853Z [launcher] spawn xdotool: 0, 99ms
[INFO ] 2020-07-14T18:33:31.936Z [launcher] spawn xdotool: 0, 83ms
[INFO ] 2020-07-14T18:33:32.035Z [launcher] spawn xdotool: 0, 99ms
[INFO ] 2020-07-14T18:33:32.136Z [launcher] spawn xdotool: 0, 101ms
[INFO ] 2020-07-14T18:33:32.238Z [launcher] spawn xdotool: 0, 102ms
[INFO ] 2020-07-14T18:33:32.340Z [launcher] spawn xdotool: 0, 101ms
[INFO ] 2020-07-14T18:33:32.466Z [launcher] spawn xdotool: 0, 127ms
[INFO ] 2020-07-14T18:33:32.551Z [launcher] spawn xdotool: 0, 84ms
[INFO ] 2020-07-14T18:33:32.659Z [launcher] spawn xdotool: 0, 109ms
[INFO ] 2020-07-14T18:33:32.763Z [launcher] spawn xdotool: 0, 103ms
[INFO ] 2020-07-14T18:33:32.857Z [launcher] spawn xdotool: 0, 94ms
[INFO ] 2020-07-14T18:33:32.940Z [launcher] spawn xdotool: 0, 83ms
[INFO ] 2020-07-14T18:33:33.073Z [launcher] spawn xdotool: 0, 133ms
[INFO ] 2020-07-14T18:33:33.179Z [launcher] spawn xdotool: 0, 106ms
[INFO ] 2020-07-14T18:33:33.285Z [launcher] spawn xdotool: 0, 105ms
[INFO ] 2020-07-14T18:33:33.362Z [launcher] spawn xdotool: 0, 78ms
[INFO ] 2020-07-14T18:33:33.441Z [launcher] spawn xdotool: 0, 79ms
[INFO ] 2020-07-14T18:33:33.537Z [launcher] spawn xdotool: 0, 95ms
[INFO ] 2020-07-14T18:33:33.653Z [launcher] spawn xdotool: 0, 116ms
[INFO ] 2020-07-14T18:33:33.790Z [launcher] spawn xdotool: 0, 137ms
[INFO ] 2020-07-14T18:33:33.891Z [launcher] spawn xdotool: 0, 101ms
[INFO ] 2020-07-14T18:33:34.010Z [launcher] spawn xdotool: 0, 118ms
[INFO ] 2020-07-14T18:33:34.045Z [launcher] spawn xdotool: 0, 35ms
[DEBUG] 2020-07-14T18:33:34.045Z [auto-type] Complete 3374ms
```

**Comment by antelle** [comment] 2020-07-15 17:43
Looks like it ran xdotool, but it didn't work. That's weird, what happens if you try sending keys to the window id from logs using xdotool?

**Comment by SeerLite** [comment] 2020-07-22 04:47
I can reproduce this (well, something similar) with v1.15.5 on Arch Linux.

Note: I can use auto-type from the dropdown on each field of an entry. It's the shortcut that doesn't work (Alt + Shift + T) and instead shows the message "Auto-type error; To use a system-wide shortcut, please focus the app where you want to type your password".

I'll be uploading the logs in a bit.

**Comment by SeerLite** [comment] 2020-07-22 05:21
Okay I don't know if it's because it's late but I can't find any way to see the logs on the desktop app nor any instructions in the README. Do I have to build the desktop app in a specific way to access the logs?

Either way, I'll try again tomorrow.

**Comment by antelle** [comment] 2020-07-22 14:44
You can open devtools in app settings (General / Advanced), then the logs will be in the Console tab.

**Comment by SeerLite** [comment] 2020-07-22 20:49
Aha! I completely missed General/Advanced! Thank you!

So I have a completely different output from OP. I only get
```
2020-07-22T20:46:01.489Z [auto-type] Auto type event null
```
everytime I try Alt + Shift + T.
I have xdotool installed and I've tried focusing different programs when trying the shortcut. It just doesn't work.

I wonder if this is the same problem as OP.  I'm gonna try older versions.

**Comment by antelle** [comment] 2020-07-22 20:51
@SeerLite did you try to use the auto-type shortcut while KeeWeb is active? It's supposed to be used in other apps, with KeeWeb running in background.

**Comment by SeerLite** [comment] 2020-07-22 20:59
Wait, does that mean it has to be minimized to the tray? Right now I'm just leaving it open and focusing another program, from the other program I do Alt + Shift + T. That's how I understand it should work, right?

**Comment by antelle** [comment] 2020-07-22 21:01
What you describe should work as well, yes. Which desktop environment is that?

**Comment by SeerLite** [comment] 2020-07-22 21:20
I'm using bspwm without any DE. I'm not missing anything DE-exclusive, right?

I just tried v1.14.3 and I get the same issue, so I guess it's a different issue from OP then.

**Comment by antelle** [comment] 2020-07-22 21:22
That's a different issue, yes

**Comment by SeerLite** [comment] 2020-07-22 21:43
So I was able to get the shortcut itself working in some way (still no auto-type). Putting the windows in the same desktop when using the shortcut makes KeeWeb show the menu with possible passwords. Choosing does nothing though.

Thing is, I had completely misunderstood how it was supposed to work, I thought this was the usage: 
Open an entry in KeeWeb -> focus the window for auto-type -> press Alt + Shift + T -> auto-type happens in the background (no interactive "choosing" menu).

Now I realized that KeeWeb should be opening this menu. So I guess the conflict with how bspwm handles focus. I'll try out a few more things before making a separate issue.

**Comment by SeerLite** [comment] 2020-07-23 02:16
I can't reproduce the issue described here (where only 1.15.x is affected).
I created a new issue for my problem, #1573.

**Comment by antelle** [comment] 2020-08-08 10:22
The issue is not clear to me at the moment, so I need more input here.

**Comment by opennomad** [comment] 2020-09-07 01:06
Apologies for the delayed response. I've been testing some more with 1.15.6 and the issue is still there.

My guess is that this is related to commit:489eb5598ca9dabe59357242d80c83b794e52482

I can auto-type successfully if I'm in the app, select the entry, followed by `ctrl-t`. In that case the auto-type works.

When I `ctrl-shift-t` from another window, select the entry, and hit enter it fails. The original window is not brought to focus.

Not sure how to proceed.

**Comment by opennomad** [comment] 2020-09-07 19:20
Ok, i did some more testing and I believe the issue might be related to [x11 - `xdotool` does not send keys - Unix &amp; Linux Stack Exchange](https://unix.stackexchange.com/questions/214909/xdotool-does-not-send-keys). It seems to mimic my findings, which are:
1. `xdotool <key|type> --window <window_id> ...` does not send d the appropriate keys
2. activating the window via `xdotool windowactivate --sync --window <window_id>` followed by `xdotool <key|type> ....` (note that it's not specifying the window id), works.

given that 2. offers a workaround, I'm going to give a PR a shot to activate and then send things.

**Comment by opennomad** [comment] 2020-09-08 18:46
the PR above :point_up:  should fix the issue I was seeing. Hope I hit the guidelines sufficiently.

**Comment by opennomad** [comment] 2020-09-09 20:43
I had another anecdotal observation. I use Firefox with it's "picture in picture" mode that floats a video on the screen on top of all other windows. With the old version (1.14), which generally worked for me, I had to close this window frequently or the passwords would not be put in the right place. I suspect it hit the "top" window. With the proposed fix, this no longer seems to be an issue and the password gets there perfectly.

**Comment by antelle** [comment] 2020-09-12 10:55
The release is published 🎁

**Closed** 2020-09-12 10:55 UTC
Labels: auto-type, bug, desktop, linux, need info
