### ISSUE TITLE
Saving changes made on 2 different machines to the same records causes data loss

### ISSUE THREAD

**Issue by jaddie** [keeweb/keeweb#541] opened 2017-02-25 16:15 UTC
- what were your actions?
Opened the webdav based keepass database on 2 different machines through the keepass app
Modified 2 records on both machines and then saved the changes on each one
- what was wrong?
The changes were not merged nor was a merge suggested & instead the values in the records that were changed on both machines were instead over-written as if nothing happened with no warning
- app version
1.4

Is this expected behaviour & is this something due to the webdav setup causing this? Is there anything I can do to prevent possible accidental information loss?

**Comment by jaddie** [comment] 2017-02-25 16:26
After having noticed the history section on the items, it appears it is actually maintaining the older records in there, however I still think there should be some kind of popup or mention of it graphically to the user etc and maybe even the option of merging or choosing which changes to keep

**Comment by antelle** [comment] 2017-02-25 17:34
> The changes were not merged 

Yes, the changes are saved to history, we tread record state as single atomic update.
This is by design, and this is how keepass works, together with all forks. We do't behave differently here. The reason for it, that you would not like to merge changed username with changed password, most probably the record will be invalid. Personally I think that it would be useful, to merge other fields, but as long as it will make keeweb incompatible to all other clients, it won't be implemented.

Instead of popup, we could highlight history somehow, if the record has been changed recently, so it will be come more visible. Merge UI, or notifications, won't be created: we merge and save automatically, there are a lot of states and cases when we merge records, adding notifications there will make app logic lots more complex and distract users.

We should think, how to highlight history better (e.g. show something next to field, like 'recently updated'), but it's another story. I don't think it will resolve the initial confusion (understanding that states are atomic, not fields), but we could try. Closing it for now.

**Closed by antelle** 2017-02-25 17:34 UTC
