### ISSUE TITLE
Autotype sends unwanted shortcuts on Linux (Kubuntu)

### ISSUE THREAD

**Issue by ValentinH** [keeweb/keeweb#361] opened 2016-09-12 08:56 UTC
## what were your actions?
I hit the SHIFT+ALT+T keys to auto-type a login/password on Chrome  (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36)

## what was wrong?
Shortcuts are sent automatically based on the characters present in my username.
For instance, if my username is 'valentin', then Chrome will receive the following shortcuts:
- SHIFT+ALT+V
- SHIFT+ALT+A
- SHIFT+ALT+L
- SHIFT+ALT+E
- etc. until I release the SHIFT+ALT keys.

## app version
KeeWeb v1.3.1 (234333d, 2016-09-02)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.1 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

## log output
```
2016-09-12T08:54:31.633Z [auto-type] Auto type event null
index.html:13 2016-09-12T08:54:31.635Z [auto-type] Get window title
index.html:13 2016-09-12T08:54:31.653Z [launcher] spawn xdotool: 0, 17ms
Connexion | ManaTime - Google Chrome
index.html:13 2016-09-12T08:54:31.653Z [auto-type] Window title Connexion | ManaTime - Google Chrome undefined
index.html:13 2016-09-12T08:54:31.655Z [auto-type] Hide window
index.html:13 2016-09-12T08:54:31.657Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
index.html:13 2016-09-12T08:54:31.659Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
index.html:13 2016-09-12T08:54:31.660Z [auto-type] Resolved [******************************,key:tab,[*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*],key:enter]
index.html:13 2016-09-12T08:54:32.141Z [launcher] spawn xdotool: 0, 481ms
index.html:13 2016-09-12T08:54:32.200Z [launcher] spawn xdotool: 0, 57ms
index.html:13 2016-09-12T08:54:32.237Z [launcher] spawn xdotool: 0, 37ms
index.html:13 2016-09-12T08:54:32.308Z [launcher] spawn xdotool: 0, 70ms
index.html:13 2016-09-12T08:54:32.371Z [launcher] spawn xdotool: 0, 62ms
index.html:13 2016-09-12T08:54:32.431Z [launcher] spawn xdotool: 0, 59ms
index.html:13 2016-09-12T08:54:32.481Z [launcher] spawn xdotool: 0, 49ms
index.html:13 2016-09-12T08:54:32.520Z [launcher] spawn xdotool: 0, 39ms
index.html:13 2016-09-12T08:54:32.557Z [launcher] spawn xdotool: 0, 36ms
index.html:13 2016-09-12T08:54:32.603Z [launcher] spawn xdotool: 0, 46ms
index.html:13 2016-09-12T08:54:32.644Z [launcher] spawn xdotool: 0, 40ms
index.html:13 2016-09-12T08:54:32.682Z [launcher] spawn xdotool: 0, 38ms
index.html:13 2016-09-12T08:54:32.728Z [launcher] spawn xdotool: 0, 45ms
index.html:13 2016-09-12T08:54:32.757Z [launcher] spawn xdotool: 0, 28ms
index.html:13 2016-09-12T08:54:32.798Z [launcher] spawn xdotool: 0, 41ms
index.html:13 2016-09-12T08:54:32.840Z [launcher] spawn xdotool: 0, 42ms
index.html:13 2016-09-12T08:54:32.896Z [launcher] spawn xdotool: 0, 55ms
index.html:13 2016-09-12T08:54:32.933Z [launcher] spawn xdotool: 0, 36ms
index.html:13 2016-09-12T08:54:32.958Z [launcher] spawn xdotool: 0, 25ms
index.html:13 2016-09-12T08:54:32.999Z [launcher] spawn xdotool: 0, 40ms
index.html:13 2016-09-12T08:54:33.058Z [launcher] spawn xdotool: 0, 58ms
index.html:13 2016-09-12T08:54:33.085Z [launcher] spawn xdotool: 0, 26ms
index.html:13 2016-09-12T08:54:33.085Z [auto-type] Complete 1428ms
```

**Comment by antelle** [comment] 2016-09-12 08:58
Duplicate of #357

**Closed by antelle** 2016-09-12 08:58 UTC

**Comment by ValentinH** [comment] 2016-09-12 09:08
OK, I thought it was a bit different since in my case, it's not like if the CTRL is pressed but just because the SHIFT+ALT are still pressed....

**Comment by antelle** [comment] 2016-09-12 09:12
It's the same... we have to wait until the key is released or clear modifiers [here](https://github.com/keeweb/keeweb/blob/master/app/scripts/auto-type/emitter/auto-type-emitter-linux.js#L41) but somehow preserve the modifiers which we set ourselves, I haven't found an acceptable solution yet.

**Comment by antelle** [comment] 2016-09-12 19:49
Uploaded the fix to beta. If you verify it before releasing, that would be great.
🎁
