### ISSUE TITLE
Move entry from one database into another?

### ISSUE THREAD

**Issue by orschiro** [keeweb/keeweb#452] opened 2016-11-28 10:09 UTC
Hi all, 

Is it possible to move an entry from one database to another like this?

![image](https://cloud.githubusercontent.com/assets/170947/20664367/29136416-b55b-11e6-80a0-b3acb490203a.png)

**Comment by antelle** [comment] 2016-11-28 10:11
no, it's not possible for now

**Comment by orschiro** [comment] 2016-11-28 17:41
Thank you.

Do you think it is a useful feature?

**Comment by antelle** [comment] 2016-11-28 18:13
Sure, it would be a very useful feature

**Comment by timbru31** [comment] 2017-04-20 12:28
Isn't this a dupe of #336?

**Comment by antelle** [comment] 2017-04-20 16:51
@timbru31, exactly. Thanks!

**Closed by antelle** 2017-04-20 16:51 UTC
Labels: enhancement
