### ISSUE TITLE
Major memory leak in v1.5.5

### ISSUE THREAD

**Issue by adatum** [keeweb/keeweb#722] opened 2017-08-30 23:26 UTC
KeeWeb v1.5.5 (desktop, linux, 32-bit, .deb) is unusable for me. 

- Took ~45 seconds to start up (normally 2-3 seconds).
- Unlocked password db.
- Clicking window's close button to minimize to tray went into 100% cpu usage and seemingly endless memory leak. 

I had to kill it after it ate 2GB+ of RAM and started going into swap.

None of these issues when reverting to KeeWeb v1.5.0.

**Comment by antelle** [comment] 2017-08-31 05:43
Is it the same in 1.5.4?

**Comment by adatum** [comment] 2017-08-31 05:55
1.5.4 is fine. No huge memory leak or long start up time.

I'm not sure if 1.5.4 was an official/standardized release. The copy I have of 1.5.4 is a .zip file that you provided for testing the seg fault issue.

**Comment by antelle** [comment] 2017-08-31 06:05
Releases are here: https://github.com/keeweb/keeweb/releases
I'll check it today, maybe there were some issues with build or tray hotfix.

**Comment by lodart** [comment] 2017-08-31 06:13
Exact same issue here. That plus Windows smart screen telling me it is not safe to install, I worried a bit ^^'

**Comment by antelle** [comment] 2017-08-31 06:22
Windows will complain for some time, because this version has a new certificate. Then it's probably related to the tray fix, will look into it.

**Comment by sainaen** [comment] 2017-08-31 08:19
FWIW, this
```diff
diff --git a/desktop/app.js b/desktop/app.js
index 9206832..c441ab5 100644
--- a/desktop/app.js
+++ b/desktop/app.js
@@ -246,7 +246,7 @@ function mainWindowBlur() {
 function emitBackboneEvent(e, arg) {
     if (mainWindow && mainWindow.webContents) {
         arg = JSON.stringify(arg);
-        mainWindow.webContents.executeJavaScript(`Backbone.trigger('${e}', ${arg});`);
+        mainWindow.webContents.executeJavaScript(`setTimeout(() => Backbone.trigger('${e}', ${arg}), 0);`);
     }
 }
```
seems to completely resolve the problem for me. (In your local installation that's `resources/app/app.js`)
Don't know why. ¯\\\_(ツ)\_/¯

**Comment by fthiery** [comment] 2017-08-31 08:25
Same here, really slow to start.

**Comment by fthiery** [comment] 2017-08-31 08:48
@sainaen thanks i included your patch in https://aur.archlinux.org/packages/keeweb-desktop until it's fixed

**Comment by daincredibleholg** [comment] 2017-08-31 10:12
For me it is not even responding once I opened a database. And it prevents me of using context menus in Firefox as well.
Tried purging and reinstalling it, but it seems like this wasn't helping either.

**Comment by snakyjake1** [comment] 2017-08-31 14:54
After a couple of minutes..this is what the Task Manager is showing:
![image](https://user-images.githubusercontent.com/8312560/29929793-54b3efa6-8e21-11e7-901f-212bf6661adc.png)

I hope this is a high priority bug.

**Comment by jasonlawrencejustice** [comment] 2017-08-31 16:46
Just found out about KeeWeb an hour ago, so I downloaded **1.5.5.win.x64.exe** to give it a shot. After installation, it didn't take long to open, and it responded to mouse input until the window lost focus. Once this happened, the program would no longer respond to mouse input, and I had to force close from Task Manager.

However, upon each attempt to run the program, it stays in memory and consumes between 1.5-2 GB of RAM per instance. Four instances later and I'm looking at roughly 6-8 GB of RAM on my Surface Pro 3 begging for that sweet release that only my Delete key would bring.

Humor aside, I downloaded **1.5.4.win.x64.exe** and installed it. So far everything is peachy, and I'm looking forward to putting KeeWeb to good use as a companion/replacement to KeePass. Thank you, and keep up the good work!

**Comment by antelle** [comment] 2017-08-31 16:48
Actually, this is caused by a large object transferred between main and renderer processes, fixed in ac23f70bb5959f63ab375115785c9bb62c2e127f (but I forgot to merge it with this hotfix). @sainaen's solution is working as well, because it's doing the same, i.e. preventing the function from returning a result to main process.
The fix will be released tonight.

**Comment by antelle** [comment] 2017-08-31 18:35
It's rolled out

**Closed by antelle** 2017-08-31 18:35 UTC
Labels: bug

**Comment by adatum** [comment] 2017-08-31 18:48
Thanks @antelle for the quick turnaround. The fix in v1.5.6 is successful for me.

Side note: I think KeeWeb had the option of checking/installing release updates. Where is that screen and is it available on all builds?

**Comment by antelle** [comment] 2017-08-31 18:50
@adatum cool! Update settings are here (however it's disabled on Linux):
![updates](https://user-images.githubusercontent.com/633557/29939917-d7b61d22-8e8d-11e7-9ac9-86e763a9ddb8.png)

**Comment by adatum** [comment] 2017-08-31 19:18
Ah, that's why. The installations from .deb don't have the option, but the one in a zip file does. Clicking to install the update in the linux/.zip build does "succeed" almost instantly, but the app does not launch the next time.
