### ISSUE TITLE
Port Keeweb to docker using the armhf  architecture 

### ISSUE THREAD

**Issue by mwolfaardt** [keeweb/keeweb#1106] opened 2019-02-06 19:07 UTC
**Is your feature request related to a problem? Please describe.**
I would like to run KeeWeb on Docker on my Raspberry PI using the armhf  architecture 

**Describe the solution you'd like**
Community contribution to make it happen

**Comment by antelle** [comment] 2019-10-27 11:42
Looks like it's a duplicate of #450 642

**Closed by antelle** 2019-10-27 11:42 UTC
Labels: distribution, enhancement, help wanted, self-hosting
