### ISSUE TITLE
[bug] kdbx opened from webdav using short url doesn't sync

### ISSUE THREAD

**Issue by Rurik19** [keeweb/keeweb#440] opened 2016-11-14 09:51 UTC
When I open kbdx from webdav, I can shorten url : instead of `http://domain/path/file.kdbx` I can just write ` /path/file.kdbx`. File opens OK, but then doesn't sync. When i press "Sync" button all messages in console say that sync is OK, but opening from another browser or location shows no changes. When I use full qualified url for webdav, all works fine.

**Comment by antelle** [comment] 2016-11-14 09:56
looks like a duplicate of #435

**Comment by Rurik19** [comment] 2016-11-14 10:05
Difference is that I have no errors at all - file opens from webdav, syncynd think that all ok, writes about it in  console, but really doesn't sync.

**Comment by antelle** [comment] 2016-11-14 10:08
please attach logs and network requests.

**Comment by Rurik19** [comment] 2016-11-14 10:21
logs are:
`2016-11-14T10:18:33.960Z [sync:lp] Saved to cache, saving to storage
(index):13 2016-11-14T10:18:33.961Z [sync:lp] Save data to storage
(index):13 2016-11-14T10:18:33.961Z [storage-webdav] Save:stat /kee/lp.kdbx
(index):13 2016-11-14T10:18:34.330Z [storage-webdav] Save:stated /kee/lp.kdbx Mon, 14 Nov 2016 09:41:55 GMT 368ms
(index):13 2016-11-14T10:18:34.330Z [storage-webdav] Save:put /kee/.lp.kdbx.1479118713961
(index):13 2016-11-14T10:18:34.867Z [storage-webdav] Save:puted /kee/.lp.kdbx.1479118713961 null 536ms
(index):13 2016-11-14T10:18:34.867Z [storage-webdav] Save:stat /kee/lp.kdbx
(index):13 2016-11-14T10:18:35.029Z [storage-webdav] Save:stated /kee/lp.kdbx Mon, 14 Nov 2016 09:41:55 GMT 162ms
(index):13 2016-11-14T10:18:35.030Z [storage-webdav] Save:move /kee/.lp.kdbx.1479118713961
(index):13 2016-11-14T10:18:35.194Z [storage-webdav] Save:moved /kee/.lp.kdbx.1479118713961 null 164ms
(index):13 2016-11-14T10:18:35.194Z [storage-webdav] Save:stat /kee/lp.kdbx
(index):13 2016-11-14T10:18:35.356Z [storage-webdav] Save:stated /kee/lp.kdbx Mon, 14 Nov 2016 09:41:55 GMT 162ms
(index):13 2016-11-14T10:18:35.357Z [sync:lp] Update rev in file info
(index):13 2016-11-14T10:18:35.358Z [sync:lp] Save to storage complete, update sync date
(index):13 2016-11-14T10:18:35.359Z [sync:lp] Sync finished no error`

**Comment by Rurik19** [comment] 2016-11-14 10:25
last 4 network responses

`Request URL:https://*****/kee/.lp.kdbx.1479118713961
Request Method:PUT
Status Code:201 
Remote Address: xxxxxx`

Request URL:https://*****/kee/lp.kdbx
Request Method:HEAD
Status Code:304 
Remote Address:  xxxxxx

Request URL:https://*****/kee/.lp.kdbx.1479118713961
Request Method:MOVE
Status Code:204 
Remote Address: xxxxxxxxxxx

Request URL:https://****/kee/lp.kdbx
Request Method:HEAD
Status Code:304 
Remote Address: xxxxxxx

**Comment by antelle** [comment] 2016-11-14 19:22
There are PUT and MOVE requests in logs... The file should've been saved, most probably it's other device cache problem.

**Comment by Rurik19** [comment] 2016-11-15 04:28
It may be. But why all  this works like a charm with full address? I'll make some experiments with another webdav software and servers.

**Comment by antelle** [comment] 2016-11-15 05:31
we should check it together with #435 (it's fixed but I cannot upload the fix at the moment)

**Comment by TimStallard** [comment] 2016-11-18 22:19
Hmm, I have a suspicion of what's happening here - do you have WebDAV enabled on the /kee directory, with KeeWeb also being served from that directory? That would cause WebDAV writes and moves to still be possible with the incorrect addresses. I guess it's also possible your WebDAV server is returning an incorrect response for a failed move (or that there's another bug we've missed!).

I'd be interested to see the actual move request (you should be able to see the destination as part of the request in your dev tools). I suspect that the path you're using (eg /kee/file.kdbx) is being appended to the path you're using (eg /kee/kee/file.kdbx), so it's possible that your files are being written there? (possibly with one of those slashes being a double, if I remember the bug correctly)

As @antelle mentioned, I think I've fixed this on master, but a full release hasn't been done yet. If you might be able to build a copy from master yourself, and give it a test, then that would be great.

The replacement is also done on the last slash in the URL, so if you're accessing it from /kee, then kee will also be replaced - /kee/ should work fine with my fix.

However, for now, full URL paths should work fine, as you said. IIRC relative paths should be fine, so file.kdbx or ../kee/lp.kdbx would also be fine - it's just root paths that were broken.

**Comment by antelle** [comment] 2016-11-19 06:22
I'll upload your fix to beta today, so it will be possible to test it.

**Comment by antelle** [comment] 2016-11-19 17:41
Deployed to [beta.keeweb.info](https://beta.keeweb.info)

**Comment by Rurik19** [comment] 2016-11-21 09:50
@TimStallard - No, KeeWeb is served from another directory.
@antelle  - Seems that beta works OK.

**Comment by antelle** [comment] 2017-02-04 15:37
released

**Closed** 2017-02-04 15:37 UTC
Labels: bug, storage
