### ISSUE TITLE
Windows can't signin with Google Account

### ISSUE THREAD

**Issue by ajay340** [keeweb/keeweb#956] opened 2018-07-07 22:48 UTC
On Windows 10, when I try login to my google account, I receive an error about how my browser is unable to accept cookies.

**Comment by ajay340** [comment] 2018-07-07 22:52
![7wfdkp](https://user-images.githubusercontent.com/10181135/42415277-e03b6cfe-8216-11e8-8c42-da8af743ffe1.png)

**Comment by antelle** [comment] 2018-07-08 18:09
It can't be a duplicate of an existing issue with gdrive, but maybe it's something new, let's keep it open

**Comment by Eraac** [comment] 2018-07-31 08:41
Same error here
MacOS 10.13.5
KeeWeb 1.6.3

**Comment by aaronburt** [comment] 2018-08-22 13:29
I had this issue too, i logged into the wrong account on Google Drive, So unchecked and rechecked Google Drive and this prompted the login screen. I attempted to sign in with another account and upon signing in i get the above issue.

**Comment by viniciusrdacosta** [comment] 2018-09-04 16:48
Same error on Linux.

Any update on this issue ?

**Comment by Coises** [comment] 2018-09-04 18:52
Probable workaround is in #810:

* Exit KeeWeb if it’s running.

* Find the user data folder for KeeWeb.  (In Windows, type **WindowsKey+R** then enter `%appdata%\KeyWeb` and click **OK**.)

* Rename or delete the `runtime-data.json` file.

* Run KeeWeb again — it should now let you log in to any Google Drive account.

**Comment by ajay340** [comment] 2018-09-05 14:58
Workaround works.

**Comment by Tadaboody** [comment] 2018-10-03 04:18
I had the same bug on my Mac, after changing the password on my Google account.
Like in the workaround, deleting all local app data fixed this

**Comment by antelle** [comment] 2019-01-05 21:52
Closing this duplicate.

**Closed by antelle** 2019-01-05 21:52 UTC
Labels: bug, desktop, windows
