### ISSUE TITLE
[Feature Request] Don't open second instance of KeeWeb from windows menu

### ISSUE THREAD

**Issue by Akeboshiwind** [keeweb/keeweb#835] opened 2018-01-05 23:46 UTC
My usual workflow for opening keeweb is to search for it in the windows search bar as I can do this using only the keyboard. It would be great if this wouldn't open another instance of keeweb as this prevents the keewebhttp plugin from working.

I understand that sometimes people will want to open two instances of keeweb, perhaps there could be an option for this in the right-click menu on the keeweb taskbar icon?

**Comment by tmthrgd** [comment] 2018-01-06 01:36
This looks like a duplicate of #807.

**Comment by antelle** [comment] 2018-01-06 08:03
@tmthrgd yeah exactly.

**Closed by antelle** 2018-01-06 08:03 UTC

**Comment by Akeboshiwind** [comment] 2018-01-06 23:05
Yup, those are the same symptoms I'm getting.
Glad to see this is getting looked into :)
