### ISSUE TITLE
webDAV uses PUT and MOVE

### ISSUE THREAD

**Issue by HalliHalloSchatz** [keeweb/keeweb#604] opened 2017-04-18 13:12 UTC
when I use a database stored on a webDAV (with svn) I see PUT and MOVE commands.
Is it possible only use the PUT command?
And why they use this strange number at the end ob my database: KeePass2.kdbx.**1492515939820**

- what were your actions?
save my changes in database, that stored on a webDAV (with subversioning)
- what was wrong?
PUT and MOVE commands, and afetr that I have no historie of my database, because the old one is delete and the new one is fresh created and moved to the original name.
- app version
latest branch 1.4.1
- apache log
[18/Apr/2017:13:45:38 +0200] "HEAD /svnwebdav/trunk/KeePass2.kdbx HTTP/1.1" 200 352 "https://xxx.de/index.html"
[18/Apr/2017:13:45:39 +0200] "HEAD /svnwebdav/trunk/KeePass2.kdbx HTTP/1.1" 200 352 "https://xxx.de/index.html"
[18/Apr/2017:13:45:40 +0200] "PUT /svnwebdav/trunk/.KeePass2.kdbx.1492515939820 HTTP/1.1" 201 645 "https://xxx.de/index.html"
[18/Apr/2017:13:45:40 +0200] "HEAD /svnwebdav/trunk/KeePass2.kdbx HTTP/1.1" 200 352 "https://xxx.de/index.html"
[18/Apr/2017:13:45:40 +0200] "MOVE /svnwebdav/trunk/.KeePass2.kdbx.1492515939820 HTTP/1.1" 204 199 "https://xxx.de/index.html"
[18/Apr/2017:13:45:40 +0200] "HEAD /svnwebdav/trunk/KeePass2.kdbx HTTP/1.1" 200 352 "https://xxx.de/index.html"

**Comment by antelle** [comment] 2017-04-18 17:00
Duplicate of #514

**Closed by antelle** 2017-04-18 17:00 UTC
