### ISSUE TITLE
Can't Login to Google Drive

### ISSUE THREAD

**Issue by testgoofy** [keeweb/keeweb#1359] opened 2019-11-27 19:58 UTC
**Describe the bug**
If I try to sign in to my Google Account, an error message occupears. The browser seems not to be supported.

**To Reproduce**
1. Start the app and close all open databes
2. In the startscreen click to 'More'
3. Click to 'Google Drive' -> a small windows with the sign - in dialog pops up
4. Insert your google mail address and click to 'next'
5. See the error

**Expected behavior**
I expected to log in and be able to sync with the google drive. Like in the web app (which is really amazing, by the way :1st_place_medal: )

**Screenshots**
![image](https://user-images.githubusercontent.com/55271228/69755056-a9fd5400-1157-11ea-95cb-c3c24c5b5c00.png)
![image](https://user-images.githubusercontent.com/55271228/69755111-cb5e4000-1157-11ea-9ae0-cb42ff0ce587.png)

**Environment**
KeeWeb v1.12.3 (9b07bbd5, 2019-11-06)
Environment: electron v7.0.0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.12.3 Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36

**Logs**
[INFO ] 2019-11-27T19:55:37.275Z [app] Started in 531ms ¯\_(ツ)_/¯
[INFO ] 2019-11-27T19:55:37.340Z [updater] Next update check will happen in 85334s
[DEBUG] 2019-11-27T19:55:40.623Z [storage-gdrive] OAuth: popup opened
[ERROR] 2019-11-27T19:55:53.179Z [storage-gdrive] OAuth error popup closed
[-1574884621402.log](https://github.com/keeweb/keeweb/files/3898597/-1574884621402.log)

**Comment by antelle** [comment] 2019-11-27 20:11
Wow, I actually don't know what to do with it. Google usually says don't mess up with user-agent, so I'd prefer to avoid changing it intentionally.

**Comment by antelle** [comment] 2019-11-27 20:12
https://support.google.com/accounts/answer/7675428 - can be a solution

**Comment by jac1013** [comment] 2019-11-30 22:57
I'm also affected by this one, some interesting points:
1 - I'm able to login with another Google Account
2 - The account with which I get the error is password and 2FA (through clicking a notification in the phone) protected, could it be related to this?

@testgoofy is the Google Account you are trying to use 2FA protected?

**Comment by antelle** [comment] 2019-12-01 11:36
@jac1013 even if it is, it depends on browser (user-agent), now 2FA being used or not (for example, for me it works perfectly with 2FA on macOS and Windows). What is your OS?

**Comment by testgoofy** [comment] 2019-12-02 21:25
> I'm also affected by this one, some interesting points:
> 1 - I'm able to login with another Google Account
> 2 - The account with which I get the error is password and 2FA (through clicking a notification in the phone) protected, could it be related to this?
> 
> @testgoofy is the Google Account you are trying to use 2FA protected?

Yes I'm also using 2FA :)

**Comment by jac1013** [comment] 2019-12-02 21:31
@antelle good question, I didn't specify that in my steps, I'm using the desktop version, I'm not sure which browser the desktop version is trying to use.

I have installed both Chrome and Firefox. I'm in LinuxMint 19.

**Comment by testgoofy** [comment] 2019-12-02 21:32
> @jac1013 even if it is, it depends on browser (user-agent), now 2FA being used or not (for example, for me it works perfectly with 2FA on macOS and Windows). What is your OS?

I'm using Linux Mint

Here are the deatils:
- **kernel-version**: 75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019
- **kernel-release**: 4.15.0-66-generic

**Comment by ab623** [comment] 2019-12-14 18:50
I too am having the exact same issue. I was using Keeweb on Desktop on Ubuntu with an account I signed into months ago, and it was working fine. I then reinstalled Ubunutu, and tried to login to my GDrive account and am getting the same issue. 

I have consulted the link it provides, but that did not solve the solution. Keeweb in the browser worked fine, but I assume that was already using my existing logged in account. 

Happy to provide any other information as required.

**Comment by ab623** [comment] 2019-12-16 00:38
Uncovering an article it seems like Google is blocking multiple browsers. 
https://www.bleepingcomputer.com/news/google/google-now-bans-some-linux-web-browsers-from-their-services/

If it's a user agent thing, can the current implantation support changing user agent? I am not a JS developer but looking at the code which uses xmlhttprequest, it seems like user agents can't be modified. Although as mentioned it not my area, so I could be entirely incorrect.

**Comment by antelle** [comment] 2019-12-16 06:46
We shouldn’t change user-agent for this. Technically it’s possible and very easy, but it’s against Google’s policy, so we may not do it: https://developers.google.com/terms/api-services-user-data-policy

> Do not mislead Google about an application's operating environment. You must accurately represent the environment in which the authentication page appears. For example, don't claim to be an Android application in the user agent header if your application is running on iOS, or represent that your application's authentication page is rendered in a desktop browser if instead the authentication page is rendered in an embedded web view.

**Comment by ab623** [comment] 2019-12-16 10:49
Understood. Assuming we cannot go ahead with he user agent approach, what are the other options here?

I know solutions such as rclone generate a link to validate in any browser and then capture the authentication response. Maybe that could be an option, albeit a bit cumbersome.

**Comment by antelle** [comment] 2019-12-16 18:25
Probably it should open a sign-in page in a browser, like some other apps do. But I haven't checked how it's done and what's required to support it.

**Comment by mikeeq** [comment] 2019-12-16 21:19
I'm having the same issue on latest version of keeweb and fresh install of Win10.

**Comment by ab623** [comment] 2019-12-17 15:41
It's also affecting my windows 10 machine too.

I was already authed with Google, which today failed the sync. Attempting a resolution by selecting my Google account to use, causes the popup to disappear and I get a "did-fail-load" error in the console.

**Comment by Xorhail** [comment] 2019-12-21 14:49
I had the same issue with google login yesterday. Tried it again today and it worked fine for me. This is on a windows 10 machine.

**Comment by Deco** [comment] 2019-12-22 05:28
@antelle, could you not just open the web page in the user's default browser? I've seen a number of applications do it this way -- I don't think you need to provide a web client yourself.

**Comment by antelle** [comment] 2019-12-22 10:41
We can open a page, however the problem is to handle its result. Probably we need to register a custom url scheme, handle it, etc... In other words, it's not a one-line change, unfortunately.

**Comment by gargamon2** [comment] 2019-12-28 12:29
People using Tusk (whatever that is) have a similar issue that may clarify. Here's the discussion:
https://github.com/klaussinani/tusk/issues/243

**Comment by bmehling** [comment] 2020-01-04 17:30
I also have this issue. Same steps to reproduce, however I receive the error after entering my password. The error dialog is slightly different (but I assume same root cause):

![image](https://user-images.githubusercontent.com/838793/71769341-bb631a00-2ed4-11ea-8496-8f4e7297e98a.png)

My gSuite account has 2FA enabled.

Two machines affected, both are MacOS Catalina / Chrome (default browser).

**Comment by Wharenn** [comment] 2020-01-05 19:21
Same issue, windows 10, desktop app, google account with 2FA activated.

**Comment by moka491** [comment] 2020-01-07 14:12
https://github.com/buttercup/buttercup-desktop/issues/850
The guys at buttercup had the same issue 
and fixed it recently by moving google auth to the user's web browser.
Can confirm for buttercup that it fixed the issue completely.

**Comment by bmehling** [comment] 2020-01-07 23:19
This aligns with the suggested solution referenced in the help article when auth fails: https://developers.google.com/identity/protocols/OAuth2InstalledApp

**Comment by jtuffin** [comment] 2020-01-11 01:57
+1 for issues with Google Drive and 2FA. 

I initially thought it was as a result of Catalina upgrade, but can also confirm this still occurs on Mojave.

**Comment by andremann** [comment] 2020-01-14 13:31
Same issue. 2FA is on for me as well. 
If only the app could open the login in another browser tab, it would probably be solved.

**Comment by antelle** [comment] 2020-01-16 17:23
Thanks for your comments and reports, looks like it behaves quite often like this, and now it's becoming a rule rather than exception, so we should fix it by opening Google login in a browser and handling the return url (that's the most complicated part here because we need to configure installers).
I'll lock the issue because:
- it's 100% clear why it happens and how to fix it
- it happens for a lot of users, we already know it
- there's not much can be added here
- no more reports are required
- in the current version of KeeWeb there's no workaround

If you came here to add another comment, please don't. PR's are very welcome, otherwise I'll fix it in the next release of KeeWeb.

**Comment by antelle** [comment] 2020-03-17 19:02
Update
- the issue is **fixed**, now a browser tab will be opened to authenticate, as the [official guide](https://developers.google.com/identity/protocols/oauth2/native-app) suggests
- it should work on all supported desktop **platforms**
- KeeWeb will **listen** on a local TCP port during authentication, again, that's the [officially suggested](https://developers.google.com/identity/protocols/oauth2/native-app#redirect-uri_loopback) way of handling authentication result
- after authentication **refresh_token** will be saved in the app, which means, it will last forever, unless you manually revoke it
- the fix is coming in **v1.13** and not earlier than that (a list of remaining issues for this release can be found [here](https://github.com/keeweb/keeweb/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.13+no%3Aassignee), but that's a soft list, if they tke too much time, it will be released earlier)
- a new release is expected to happen in **April**
- if you would like to give it a **test**, you can try the beta version using the beta button in Settings > Advanced, please [contact me](https://antelle.net) if it doesn't work for you
- since the discussion is a bit hot, I'm not going to reopen **comments** here, basically there's nothing to discuss and there will be no further update before v1.13 release

**Closed** 2020-04-03 19:53 UTC
Labels: bug, storage

**Comment by antelle** [comment] 2020-04-03 20:04
The new release is rolled out! Please give it a test and submit a new issue if it doesn't work for you. Happy Google Driving!
