### ISSUE TITLE
Nondescript Popup

### ISSUE THREAD

**Issue by zQueal** [keeweb/keeweb#226] opened 2016-05-14 19:36 UTC
I, unfortunately, can't be too descriptive here. The steps to replicate are to simply open a database with the Desktop application, and send to the system tray. Once it's there, every XX minutes (not quite sure how long) a window will pop-up for less than a second and gain system focus. It's not a huge deal, but it is very inconvenient.

##### What were your actions?

Normal use, nothing specific. Only happens when minimized to the system tray on Windows.

##### What was wrong?

Nondescript popup which shows for less than a second--but gains focus--then disappears. 

##### App Version?

1.1.4

##### Your user-agent?

    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.1.4 Chrome/49.0.2623.75 Electron/0.37.4 Safari/537.36

##### Does it happen on Demo or New database?

As far as I can tell, yes. But only does so in the desktop client.

##### Logs

    2016-05-14T19:27:19.152Z [updater] Next update check will happen in 3554s
    2016-05-14T19:27:19.155Z [updater] Checking for update...
    2016-05-14T19:27:19.156Z [transport] GET https://antelle.github.io/keeweb/manifest.appcache
    2016-05-14T19:27:22.623Z [transport] Request to https://antelle.github.io/keeweb/manifest.appcache without proxy
    2016-05-14T19:27:23.787Z [transport] Response from https://antelle.github.io/keeweb/manifest.appcache: 301
    2016-05-14T19:27:23.787Z [transport] GET http://app.keeweb.info/manifest.appcache
    2016-05-14T19:27:23.797Z [transport] Request to http://app.keeweb.info/manifest.appcache without proxy
    2016-05-14T19:27:23.895Z [transport] Response from http://app.keeweb.info/manifest.appcache: 301
    2016-05-14T19:27:23.896Z [updater] Update check error Too many redirects
    2016-05-14T19:27:23.900Z [updater] Next update check will happen in 86400s
    2016-05-14T19:27:34.953Z [updater] Checking for update...
    2016-05-14T19:27:34.954Z [transport] GET https://antelle.github.io/keeweb/manifest.appcache
    2016-05-14T19:27:34.970Z [transport] Request to https://antelle.github.io/keeweb/manifest.appcache without proxy
    2016-05-14T19:27:35.011Z [transport] Response from https://antelle.github.io/keeweb/manifest.appcache: 301
    2016-05-14T19:27:35.012Z [transport] GET http://app.keeweb.info/manifest.appcache
    2016-05-14T19:27:35.016Z [transport] Request to http://app.keeweb.info/manifest.appcache without proxy
    2016-05-14T19:27:35.087Z [transport] Response from http://app.keeweb.info/manifest.appcache: 301
    2016-05-14T19:27:35.087Z [updater] Update check error Too many redirects

**Comment by antelle** [comment] 2016-05-14 19:39
Hello,
That's strange. You have 'auto-lock on timeout' setting switched on, right?

**Comment by zQueal** [comment] 2016-05-14 20:28
I actually don't! This is a private PC, so I have my library protected with a password to enter on startup, but after that it doesn't lock--basically I've disabled anything to do with database locking. The following are my settings;

![qtxdgq](https://cloud.githubusercontent.com/assets/239193/15270526/d98201b0-19f0-11e6-9849-4da085450a8f.png)

**Comment by antelle** [comment] 2016-05-14 20:30
Thanks for the settings screen, I'll investigate the issue

**Comment by antelle** [comment] 2016-08-14 16:46
Found a reason: duplicate of #283

**Closed by antelle** 2016-08-14 16:46 UTC
Labels: bug, desktop, duplicate, windows
