### ISSUE TITLE
[FeatureRequest] Ability to change shortcuts

### ISSUE THREAD

**Issue by saksmt** [keeweb/keeweb#483] opened 2016-12-27 21:23 UTC
It's really awkward when exist collision between user-defined system shortcut and KeeWeb shortcuts. It leads to following (#482)

**Comment by antelle** [comment] 2016-12-27 21:24
duplicate of #348

**Closed by antelle** 2016-12-27 21:24 UTC

**Comment by saksmt** [comment] 2016-12-27 21:27
@antelle, That issue already closed and also mention auto-type, so I've opened this one

**Comment by antelle** [comment] 2016-12-27 21:28
> That issue already closed

no, it's open
basically it is for auto-type...

**Comment by saksmt** [comment] 2016-12-27 21:29
@antelle Sorry, missed that it was open
