### ISSUE TITLE
[Bug] AutoType doesn't work well with Spaces (aka mac's virtual desktops)

### ISSUE THREAD

**Issue by FilipJaksic** [keeweb/keeweb#393] opened 2016-09-30 08:33 UTC
Hello,
when using KeeWeb with multiple Spaces I have experienced that AutoType doesn't work in every situation. 
When a matching entry can't be found and I manually select one, KeeWeb disappears, switches to the next Space (whichever it might be) and performs autotype (in whatever program is open). 
For example, if I press the autotype shortcut in the 1st Space and have KeeWeb open in the 3rd Space and no matching entry exists and I manual select one, it switches to the 2nd Space and there performs autotype.

But it works normal if a matching entry exists.

Nothing unusual in the console, just the regular autotype message.

KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

**Comment by antelle** [comment] 2016-09-30 08:38
This is a known issue, but I don't know how to fix it, help is appreciated.
Duplicate of #307

**Closed by antelle** 2016-09-30 08:38 UTC

**Comment by FilipJaksic** [comment] 2016-09-30 08:45
Oh, my fault, I thought it might be different as this is a virtual desktop and that is multi-monitor issue.

Sorry, I would gladly help you, but I have never worked with JS or HTML.

**Comment by antelle** [comment] 2016-09-30 08:46
We also have a native [macOS helper](https://github.com/keeweb/keeweb/tree/master/helper/darwin/src/KeeWebHelper) here, it's in Objective C, so it can access all macOS APIs. Some operations could be implemented in it, e.g. get some desktop id and restore it back.

**Comment by FilipJaksic** [comment] 2016-09-30 09:11
Will look into that, but don't expect anything from me as I am just a student.

**Comment by Alph2** [comment] 2017-10-19 15:18
Just throwing an idea out there: you could make keeweb running as a menubar app, so that it would alway be in the right space/desktop. (And it would make sense, since it works as a background app)
