### ISSUE TITLE
[Feature request] Reference other entry's properties inside entry

### ISSUE THREAD

**Issue by dodalovic** [keeweb/keeweb#405] opened 2016-10-12 10:49 UTC
Keepassx has a feature to reference other item's properties inside item. 
This is particularly useful when having something like LDAP credentials, that are used from many applications to login. It would be maintenance nightmare to manually copy values to other items whenever  LDAP credentials change. 

I find this critical feature to have.

**Comment by antelle** [comment] 2016-10-12 10:54
Duplicate of #296
> critical feature to have

For enterprise. It's not so critical for personal usage.

**Closed by antelle** 2016-10-12 10:54 UTC
