### ISSUE TITLE
Uploaded/Downloaded Favicon Icons unable to be removed

### ISSUE THREAD

**Issue by Tephnos** [keeweb/keeweb#445] opened 2016-11-19 06:35 UTC
As per our earlier messages (forgot about the subscription thing, my bad).

I took your suggestion and gave it a try, knocking off the downloaded favicons from use, but they still persist in the list, even after a reboot to see if that would flush it.

App version is latest, v1.3.3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
Happens on new database and web demo, too.

(As for point 2, fair enough. It'd be nice as an option to disable the suggestion but probably not worth the dev time).

**Comment by antelle** [comment] 2016-11-19 06:40
They persist in entry history. Most probably you changed the icon but it's still in history.
We should add icon delete button and a setting for auto-management (as it's now).

**Comment by antelle** [comment] 2017-02-05 14:25
closing as duplicate of #133

**Closed by antelle** 2017-02-05 14:25 UTC
Labels: enhancement
