### ISSUE TITLE
Not possible to host index.html inside existing website within an iframe?

### ISSUE THREAD

**Issue by asmwp** [keeweb/keeweb#1012] opened 2018-10-07 15:58 UTC
I am sure that this is a configuration issue.

I really like the look the look of KeeWeb and I have been trying to see if I am able to self-host the index.html within my existing website. I need to be able to hide access to KeeWeb behind my current website login and make it accessible like any other HTML page.

I have tried hosting the page on its own in my website and this works fine but is not enough security.

I have tried hosting the page within my site which also works BUT it loads the index.html and expands to fill the whole screen and overloads my site navigation so I am unable to see anything of my actual site.

I have tried loading the index.html page inside of an iframe within my site but this does not seem do anything, nothing of KeeWeb loads. I did find an entry for a change made 31/08/2017 with the description "prevent keeweb from working in iframe", what was the reason for preventing it working in an iframe?

I have even tried to download the current latest source code itself and compile it without success as I get all sorts of errors such as;

Local Npm module "grunt-contrib-deb" not found. Is it installed?
Local Npm module "grunt-appdmg" not found. Is it installed?

Warning: Task "bower-install-simple:install" failed. Use --force to continue.

Aborted due to warnings.

Is there any sort of configuration file that can be edited for me to be able to get this to work inside of my existing website?

I am hosting an ASP.NET MVC 5 website on IIS on Windows 2016 Data Centre.

I am trying to compile the source code using Visual Studio Code on WIndows 10 x64

Can you give me any assistance at all as to how I can get the app to run in a iframe, or contained on a page or even to get the source to code so I can make changes myself?

**Comment by antelle** [comment] 2019-10-11 19:45
Hi! Somehow this issue was not noticed. It's basically a duplicate of #1108

**Closed by antelle** 2019-10-11 19:45 UTC
