### ISSUE TITLE
still ongoing > WebDAV Error: network error 

### ISSUE THREAD

**Issue by phenomeus** [keeweb/keeweb#1552] opened 2020-06-26 09:47 UTC
sorry for coming back that late again. I trusted the self signed certificate, I get a download in safari when I do: https://192.168.1.10/webdav/Database.kdbx or I use cmd+k and can connect to https://192.168.1.10/webdav/

the certificate is accepted. but still no luck with webdav, logs are showing: 
…
[INFO ] 2020-06-26T08:31:36.479Z [usb-listener] Starting USB listener
[DEBUG] 2020-06-26T08:31:36.479Z [native-module-connector] Starting native module host
[DEBUG] 2020-06-26T08:31:54.932Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:31:55.114Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 182ms
[DEBUG] 2020-06-26T08:32:12.673Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:12.699Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 25ms
[DEBUG] 2020-06-26T08:32:13.359Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.391Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 31ms
[DEBUG] 2020-06-26T08:32:13.528Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.555Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 27ms
[DEBUG] 2020-06-26T08:32:13.685Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.706Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 21ms
[DEBUG] 2020-06-26T08:32:13.842Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:13.862Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 20ms
[DEBUG] 2020-06-26T08:32:14.000Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:32:14.031Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 31ms
[DEBUG] 2020-06-26T08:35:04.328Z [storage-webdav] Stat https://192.168.1.10/webdav/Database.kdbx
[DEBUG] 2020-06-26T08:35:04.352Z [storage-webdav] Stat error https://192.168.1.10/webdav/Database.kdbx 24ms
any idea?

UPDATE:
can we "save" my input under "webdav". when I switch the windows its losing and I have to write everything again

_Originally posted by @phenomeus in https://github.com/keeweb/keeweb/issues/1471#issuecomment-650059089_

**Comment by antelle** [comment] 2020-06-26 14:36
Hi! What do you see in Network panel?

**Comment by phenomeus** [comment] 2020-06-27 07:54
My setup works with strongbox on iOS with WebDAV. So now let’s dig into Keeweb

**Comment by phenomeus** [comment] 2020-06-27 07:59
> Hi! What do you see in Network panel?

what network panel do you mean?

**Comment by antelle** [comment] 2020-06-27 08:03
The network panel in devtools

**Comment by phenomeus** [comment] 2020-06-27 08:19
<img width="1409" alt="Bildschirmfoto 2020-06-27 um 10 18 36" src="https://user-images.githubusercontent.com/5281493/85918043-9b972800-b85f-11ea-9f3e-5fec30be48e9.png">

**Comment by antelle** [comment] 2020-06-27 08:31
So, if you click one of those failed requests, what do you see in the details?

**Comment by phenomeus** [comment] 2020-06-27 09:03
"failed to load response data" nothing to see

**Comment by antelle** [comment] 2020-06-27 09:08
Does it give more verbose explanation if you try to explore different sections of it?

**Comment by phenomeus** [comment] 2020-06-27 09:32
Stat error https://192.168.1.10/webdav/Database.kdbx 28ms
index.html:1 HEAD https://192.168.1.10/webdav/Database.kdbx net::ERR_CERT_COMMON_NAME_INVALID
_request @ index.html:1
stat @ index.html:1
applyConfig @ index.html:1
s.emit @ index.html:1
apply @ index.html:1
eventListener @ index.html:1
e @ index.html:1

**Comment by antelle** [comment] 2020-06-27 10:34
How did you trust the certificate? Could you please make a screenshot of the certificate in your keychain with its trust settings?
I made a video of the process that demonstrates how to do it, maybe it will be easier this way: https://youtu.be/k5KrOtWKEfY. Try to repeat exactly the same, maybe it will work?

**Comment by phenomeus** [comment] 2020-06-27 11:10
basically like you did but I realized right now that I made one for my local domain: pi.hole (see screenshot)

and even when I input this into keeweb I get the same network error like above. chrome and firefox are warning me correctly about a self signed certificate at https://pi.hole/webdav/Database.kdbx

and how is strongbox app on iOS handling it? my iPhone don't even know about the certificate, its just ignoring it right? 

<img width="711" alt="Bildschirmfoto 2020-06-27 um 12 57 01" src="https://user-images.githubusercontent.com/5281493/85920841-80381700-b877-11ea-8a10-d9b0878c8c6e.png">

**Comment by antelle** [comment] 2020-06-27 11:14
This looks correct
> chrome and firefox are warning me

You mean, you see a warning that it's not trusted? It should not display a warning if everything is ok.
What happens if you restart KeeWeb and open the same url again?

**Comment by antelle** [comment] 2020-06-27 11:28
Another question, I see that your log shows IP address instead of the domain name. If a certificate is issued for a domain name, you cannot use it to access a file by IP. How do you use this file in KeeWeb?

**Comment by phenomeus** [comment] 2020-06-27 11:30
`How do you add this file to KeeWeb? `

Tried both. Ip and Domain

**Comment by antelle** [comment] 2020-06-27 11:38
That's the point, if it's trusted in the keychain, browsers must not show any warning, they must trust it by default. That's why you can't open it in KeeWeb. If you solve this issue and browsers trust the certificate, KeeWeb will accept it as well.

**Comment by antelle** [comment] 2020-06-27 15:51
Closing it, looks like it works as expected. If you manage to reproduce it while Chrome and Firefox don't give a warning, we can look into it further.

**Closed** 2020-06-27 15:51 UTC
Labels: need info, storage
