### ISSUE TITLE
WebDAV sync freezes often

### ISSUE THREAD

**Issue by gruenel** [keeweb/keeweb#624] opened 2017-05-15 13:26 UTC
I'm using a self-hosted KeeWeb on my NAS running Ubuntu Server 16.04 LTS, accessing a WebDAV database located on the same NAS.
apache2 has been configured according to https://github.com/keeweb/keeweb/wiki/WebDAV-Config.

Often when I try to save the database, the "sync" icon just stays there indefinitely (I've waited up to 10 minutes) and CPU usage stays very high until I close the browser tab. The database is not saved in this case. This happens in about 50% of my attempts to save the database. Other times, it works fine.

Usually I'll just re-open the database and try saving it again.

I'm having no problems accessing the WebDAV share with other applications.

The bug might be related to Safari, a quick test with ~10 saves has shown that there are no problems when using Chrome.

Version info:
```
KeeWeb v1.4.1 (df218ae, 2017-03-26)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30
```

The app log's last entry is:
`[DEBUG] 2017-05-15T13:20:49.605Z [storage-webdav] Save:put db/xxx/.db.kdbx.1494854449595`
at which point it doesn't continue.

**Comment by antelle** [comment] 2017-05-15 17:24
Is there anything in Network tab?

**Comment by gruenel** [comment] 2017-05-15 20:03
The console shows an error, but this error is also there when saving actually works, so I'm not sure if it is related:

```
[Error] 2017-05-15T19:50:30.683Z [backup:Password Database] Stat folder error – "bad-key"
	error (keeweb:16:22888)
	(anonymous function) (keeweb:20:23871)
	(anonymous function) (keeweb:22:11038)
	_callAndHandleError (keeweb:17:16719)
	stat (keeweb:17:18141)
	stat (keeweb:22:10874)
	backupFile (keeweb:20:23561)
	scheduleBackupFile (keeweb:20:24589)
	fileOpened (keeweb:20:18604)
	(anonymous function) (keeweb:20:17013)
	(anonymous function) (keeweb:18:21193)
	promiseReactionJob
```

The "Resources" tab shows this:
<img width="299" alt="screen shot 2017-05-15 at 21 58 25" src="https://cloud.githubusercontent.com/assets/28707268/26076746/07a13d4c-39ba-11e7-9159-8f45080a2bbe.png">
In this case synching worked the first 6 times, on the 7th try it froze and the spinner just stayed there forever, same as in the app.

The "Network" tab does not show anything useful, unfortunately.

**Comment by antelle** [comment] 2017-05-15 20:05
Hm, that's weird. Does it show this last request as pending in Network?

**Comment by gruenel** [comment] 2017-05-15 20:07
Yes, screenshot of the network tab:

<img width="1246" alt="screen shot 2017-05-15 at 22 07 25" src="https://cloud.githubusercontent.com/assets/28707268/26076981/e867b662-39ba-11e7-9c03-4cd908251175.png">

**Comment by antelle** [comment] 2017-05-15 20:09
Wait, why are there three PUT requests?
Could you please try to remove the file from keeweb and add it again, but don't enable backups? It looks like, it's trying to make a backup and hangs on it.

**Comment by gruenel** [comment] 2017-05-15 20:22
The PUT requests get added to the list every time I save. In the screenshot above I successfully saved 2 times, then the third one froze.

What I did now:
- Disabled Backups
- Removed file from KeeWeb
- Completely deleted Safari's Local Storage
- Re-added the file

The problem seems to be gone for now.

**Comment by antelle** [comment] 2017-05-15 20:28
Cool then. So, the problem is that backups are enabled, but without storage because you have Dropbox disabled, so they are misconfigured. Pushed the fix, backups checkbox will not be visible in this case.

**Closed by antelle** 2017-05-15 20:28 UTC
Labels: need info

**Comment by antelle** [comment] 2017-05-15 20:30
On the screenshot, btw, server is not responding to PUT, don't know why this could happen.
Next version will have two ways to save to WebDAV, one of them is without MOVE, so if it repeats, you can try it as well with beta, maybe it will help.

**Comment by gruenel** [comment] 2017-05-15 20:34
It's strange indeed. I'll keep you posted in case it happens again.

**Comment by gruenel** [comment] 2017-07-17 12:14
I still have this problem with KeePass occasionally locking up when saving to WebDAV in 1.5.4.

This only happens in Safari (currently using 10.1.1). No problem in Chrome.

Tried both MOVE and PUT methods.

I'm using a password protected WebDAV share, but didn't store the username/password in config.json (where I defined the database locations). When I do it like that, the browser just asks me for the WebDAV credentials after entering my KDBX password and everything seems to work fine. Is this problematic?

I tried enabling anonymous WebDAV access and the problems with Safari seem to have been resolved, however I'm not 100% sure about this as I need to do further testing.

**Comment by antelle** [comment] 2017-07-17 16:52
Basic auth might be a problem, however I'm not sure how to repeat it. Is it still the same, I mean, you see two simultaneous requests in Network?

**Comment by gruenel** [comment] 2017-07-18 09:29
I just reproduced it again.

Here's when I saved the database for the first time, which worked fine:
<img width="1247" alt="bildschirmfoto 2017-07-18 um 11 23 19" src="https://user-images.githubusercontent.com/28707268/28310203-f6e4f2cc-6bab-11e7-85a3-7f41486144e6.png">

After this I made some more changes and wanted to save again, then it hung up again:
<img width="1246" alt="bildschirmfoto 2017-07-18 um 11 24 47" src="https://user-images.githubusercontent.com/28707268/28310225-07283cfc-6bac-11e7-9630-384121d7b403.png">

**Comment by antelle** [comment] 2017-07-18 18:25
I see that you're using PUT+MOVE. Does it repeat if you switch to simple PUT?

**Comment by gruenel** [comment] 2017-07-18 20:17
Been toying around with the PUT option for the last 30 minutes and it didn't freeze so far (20+ saves). However I'm pretty sure I've encountered the problem with PUT in the past too.
