### ISSUE TITLE
Allow change of WebDav password.

### ISSUE THREAD

**Issue by sbluhm** [keeweb/keeweb#1677] opened 2021-01-05 10:40 UTC
**Is your feature request related to a problem? Please describe.**
1. To open a password file via WebDav, you click on "More" --> "WebDav" and fill out the details (url, username, password).
2. The connection gets saved and when you come back, the connection link is stored on the intial screen for reuse.
3. When the webdav password changes during usage, you cannot resync your password file anymore. You have to close the password file, delete the connection link on the initial screen and set up a new Webdav connection.

Issues here are when the WebDav password changes:
1. The user frequently has to re-setup the WebDav connection whenever the password changes (the URL is generally not easy to remember or short).
2. Data is forced to get lost as new Keeweb passwords cannot be synced to WebDav anymore.

**Describe the solution you'd like**
Whenever the WebDav link has different credentials, a pop-up will ask for new username and password. The data is then stored in the connection link. No re-setup of the link is required.
The new link can be used straight away to sync the changes up to Webdav.

**Describe alternatives you've considered**
To prevent data loss, save the file to a different location and then re-create the webdav link to save it back up again.

**Additional context**
If you tell me where and how to add the changes, I will put in some effort for a PR.

**Comment by antelle** [comment] 2021-01-05 17:00
Duplicate of #1540

**Closed by antelle** 2021-01-05 17:00 UTC
Labels: enhancement

**Comment by sbluhm** [comment] 2021-01-06 06:32
Apologies, despite looking for it, I didn't find it. Can you give some pointer or implementation suggestions and I will see what I can do.
