### ISSUE TITLE
ctrl-t not working properly (Linux/Xubuntu/19.04)

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#1234] opened 2019-08-19 15:17 UTC
**Describe the bug**

Pressing ctrl-t hides KeeWeb, but does nothing. As it seems, only when getting back to keeweb, it does actually start with xdotools...as I can guess, because it fills the search with my password.

I cannot tell if it is either: 
- My update to xubuntu 19.04
- Update to KeeWeb 1.9 

**To Reproduce**

Press ctrl-t

**Expected behavior**

As before.

**Environment**

KeeWeb v1.9.0 (64c41785, 2019-08-18)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.0 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Logs**

As one can see, xdotool only started after 5 seconds or so...

[DEBUG] 2019-08-19T15:12:46.666Z [auto-type] Hide window
[DEBUG] 2019-08-19T15:12:46.772Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2019-08-19T15:12:46.772Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2019-08-19T15:12:46.772Z [auto-type] Resolved [********,key:tab,[*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2019-08-19T15:12:51.824Z [launcher] spawn xdotool: 0, 5052ms
[INFO ] 2019-08-19T15:12:51.966Z [launcher] spawn xdotool: 0, 142ms
[INFO ] 2019-08-19T15:12:52.048Z [launcher] spawn xdotool: 0, 81ms
[INFO ] 2019-08-19T15:12:52.119Z [launcher] spawn xdotool: 0, 71ms
[INFO ] 2019-08-19T15:12:52.189Z [launcher] spawn xdotool: 0, 70ms
[INFO ] 2019-08-19T15:12:52.260Z [launcher] spawn xdotool: 0, 71ms
[INFO ] 2019-08-19T15:12:52.328Z [launcher] spawn xdotool: 0, 68ms
[INFO ] 2019-08-19T15:12:52.400Z [launcher] spawn xdotool: 0, 71ms
[INFO ] 2019-08-19T15:12:52.469Z [launcher] spawn xdotool: 0, 69ms
[INFO ] 2019-08-19T15:12:52.541Z [launcher] spawn xdotool: 0, 72ms
[INFO ] 2019-08-19T15:12:52.611Z [launcher] spawn xdotool: 0, 70ms
[INFO ] 2019-08-19T15:12:52.680Z [launcher] spawn xdotool: 0, 69ms
[INFO ] 2019-08-19T15:12:52.700Z [launcher] spawn xdotool: 0, 20ms
[DEBUG] 2019-08-19T15:12:52.700Z [auto-type] Complete 5928ms

**Comment by antelle** [comment] 2019-08-19 18:57
Weird, looks like electron waits until the window comes to foreground when spawning a new process from a renderer process. However it seems to be working well from main process. Unexpected, I would say.

Also it seems to be unstable, so I can't confirm it's 100% fixed, however it works for me now. Please let me know if it solves your issue when it's released.

**Comment by benzkji** [comment] 2019-08-20 08:07
first try works for now! thx for the quick fix!

**Comment by benzkji** [comment] 2019-08-20 08:16
sorry to reopen. now the auto type feature with alt-shift-t is no more working. I prefer 1.9.0 then :||

it only shows this in logs:

```
[DEBUG] 2019-08-20T08:13:28.024Z [auto-type] Auto type event null
[DEBUG] 2019-08-20T08:13:28.027Z [auto-type] Get window title
```

**Comment by antelle** [comment] 2019-08-20 08:55
Interesting, did it work in 1.9.0? Looks like it’s a different thing.

**Comment by benzkji** [comment] 2019-08-20 08:55
yes it works in 1.9.0, switched back for now ;_)

**Comment by benzkji** [comment] 2019-08-20 08:56
does it work for you on 1.9.1 with Linux?

**Comment by antelle** [comment] 2019-08-20 08:56
I haven’t tried alt-shift-t on linux, will test it today

**Comment by antelle** [comment] 2019-08-20 18:23
I just checked, it's working well for me. What do you see?

**Comment by benzkji** [comment] 2019-08-20 19:55
on my other computer/laptop, it was broken first (ctrl-t and alt-shift-t) in both 1.9.0 and 1.9.1. but 1.8.2 is working. After installing 1.8.2 (I had 1.8.1), suddenly ctrl-shift-t works but not ctrl-t, even after installing 1.9.0. and in 1.9.1, not ctrl-shift-t, but ctrl-t. so, it's consistent (with my other computer), somehow, at least...

hope you understand this ;-)

**Comment by antelle** [comment] 2019-08-20 19:57
So, do I understand it right that in 1.9.1 ctrl-t works, but alt-shift-t doesn’t (btw, it’s alt, not ctrl). Do you have logs from this laptop?

**Comment by benzkji** [comment] 2019-08-20 20:30
yes, true. here the logs. first, a ctrl-t, then 3x an alt-shift-t try:

```
[DEBUG] 2019-08-20T20:00:09.968Z [auto-type] Auto type event {"id":"8184b6fc-074c-9f57-538a-85bfdbbb53f0:bhTvedqIUOIe6H6ErLNjOQ==","uuid":"bhTvedqIUOIe6H6ErLNjOQ=="}
[DEBUG] 2019-08-20T20:00:09.968Z [auto-type] Hide window
[DEBUG] 2019-08-20T20:00:10.078Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2019-08-20T20:00:10.079Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2019-08-20T20:00:10.081Z [auto-type] Resolved [********,key:tab,[*,*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2019-08-20T20:00:10.320Z [launcher] spawn xdotool: 0, 238ms
[INFO ] 2019-08-20T20:00:10.471Z [launcher] spawn xdotool: 0, 150ms
[INFO ] 2019-08-20T20:00:10.585Z [launcher] spawn xdotool: 0, 114ms
[INFO ] 2019-08-20T20:00:10.693Z [launcher] spawn xdotool: 0, 108ms
[INFO ] 2019-08-20T20:00:10.801Z [launcher] spawn xdotool: 0, 108ms
[INFO ] 2019-08-20T20:00:10.911Z [launcher] spawn xdotool: 0, 109ms
[INFO ] 2019-08-20T20:00:11.018Z [launcher] spawn xdotool: 0, 107ms
[INFO ] 2019-08-20T20:00:11.133Z [launcher] spawn xdotool: 0, 115ms
[INFO ] 2019-08-20T20:00:11.239Z [launcher] spawn xdotool: 0, 107ms
[INFO ] 2019-08-20T20:00:11.352Z [launcher] spawn xdotool: 0, 113ms
[INFO ] 2019-08-20T20:00:11.461Z [launcher] spawn xdotool: 0, 109ms
[INFO ] 2019-08-20T20:00:11.573Z [launcher] spawn xdotool: 0, 112ms
[INFO ] 2019-08-20T20:00:11.638Z [launcher] spawn xdotool: 0, 64ms
[DEBUG] 2019-08-20T20:00:11.638Z [auto-type] Complete 1560ms
[DEBUG] 2019-08-20T20:00:13.401Z [auto-type] Auto type event null
[DEBUG] 2019-08-20T20:00:13.404Z [auto-type] Get window title
[DEBUG] 2019-08-20T20:00:17.039Z [auto-type] Auto type event null
[DEBUG] 2019-08-20T20:00:17.041Z [auto-type] Get window title
[DEBUG] 2019-08-20T20:28:51.520Z [auto-type] Auto type event null
[DEBUG] 2019-08-20T20:28:51.523Z [auto-type] Get window title
```

KeeWeb v1.9.1 (d16f3356, 2019-08-19)
Environment: electron v6.0.2
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.9.1 Chrome/76.0.3809.110 Electron/6.0.2 Safari/537.36

**Comment by antelle** [comment] 2019-08-20 20:32
Interesting, so it can't get the window title. Which is also using `spawn`. I'll try to understand why.

**Comment by antelle** [comment] 2019-08-20 20:36
In which state was KeeWeb when you ran auto-type with alt-shift-t?

**Comment by benzkji** [comment] 2019-08-20 20:40
not being able to get a window title might be because of the new xubuntu release, that introduces some xfce enhancements/upgrades?!

keeweb was as normal, having loaded a kdbx from webdav, and waiting, pw entries list visible. really nothing special.

**Comment by antelle** [comment] 2019-08-20 20:42
Most likely it's a combination of both. So, the problem is, we try to start `xdotool`, however it doesn't start. Could you please check if `xdotool` is there in the process list after pressing alt-shift-t?

**Comment by antelle** [comment] 2019-08-20 20:56
Would you be able to test beta if I upload a build with more logging and an attempt to fix this?

**Comment by antelle** [comment] 2019-08-20 21:01
Looks like `xdotool` is launched, however it doesn't understand that `stdin` is closed, even if we call `end`. I've additionally added `destroy` and it seems to help. Could you please download 1.9.1 and try beta there?

**Comment by benzkji** [comment] 2019-08-22 07:29
I've tried this. It is not working, logging as before:

```
[DEBUG] 2019-08-22T07:28:42.010Z [auto-type] Auto type event null
[DEBUG] 2019-08-22T07:28:42.012Z [auto-type] Get window title
[INFO ] 2019-08-22T07:28:42.012Z [launcher] spawn:starting
[INFO ] 2019-08-22T07:28:42.053Z [launcher] spawn:waiting

**Comment by benzkji** [comment] 2019-08-22 07:30
I've had the red "beta" banner, that should be enough, right?

**Comment by antelle** [comment] 2019-08-22 07:31
Yes it’s enough. Ok, I’ll try one more thing tonight. It’s weird that such a simple thing as spawn requires so much effort to fix it :(

**Comment by benzkji** [comment] 2019-08-22 07:32
:(. will check for xdotool in processes, did not see this.

**Comment by antelle** [comment] 2019-08-22 07:32
It should be there, waiting for keeweb.

**Comment by benzkji** [comment] 2019-08-22 07:35
like, after alt-shift-t, checking with ps aux | grep xdotool ?

**Comment by antelle** [comment] 2019-08-22 07:35
yes

**Comment by benzkji** [comment] 2019-08-22 07:40
I cant see xdotool. But. How come it works with 1.9.0? This uses new electron as well, no?

**Comment by benzkji** [comment] 2019-08-22 07:40
no xdotool in 1.9.1 neither in beta.

**Comment by antelle** [comment] 2019-08-22 07:41
1.9.0 is launching xdotool from a renderer process, 1.9.1 from main. Which breaks different things in different places.

**Comment by benzkji** [comment] 2019-08-22 09:16
I see. Why the change? Or is this not under your control?

**Comment by antelle** [comment] 2019-08-22 17:13
Uploaded a new build to beta, let's try it again please.

**Comment by benzkji** [comment] 2019-08-22 18:54
sorry, not better. log stays the same.

**Comment by antelle** [comment] 2019-08-22 18:55
Quite bad. Not sure what to do with it yet, I'll try to find something in Electron's bugtacker.

**Comment by antelle** [comment] 2019-08-22 18:56
By the way, could you please paste logs, what do they say about `destroy`?

**Comment by benzkji** [comment] 2019-08-22 18:57
these, nothing special about destroy?
```
[DEBUG] 2019-08-22T18:52:58.287Z [auto-type] Auto type event null
[DEBUG] 2019-08-22T18:52:58.289Z [auto-type] Get window title
[INFO ] 2019-08-22T18:52:58.289Z [launcher] spawn:starting
[INFO ] 2019-08-22T18:52:58.329Z [launcher] spawn:waiting
[DEBUG] 2019-08-22T18:52:59.695Z [auto-type] Auto type event null
[DEBUG] 2019-08-22T18:52:59.698Z [auto-type] Get window title
[INFO ] 2019-08-22T18:52:59.698Z [launcher] spawn:starting
[INFO ] 2019-08-22T18:52:59.738Z [launcher] spawn:waiting

**Comment by antelle** [comment] 2019-08-22 19:02
I see, that's because we don't write anything, and we need to apply hack in another place as well. Rebuilt the beta, let's try it once more.

**Comment by benzkji** [comment] 2019-08-22 19:08
sorry, no luck.

**Comment by antelle** [comment] 2019-08-22 19:08
and what's there about `destroy` in logs?

**Comment by benzkji** [comment] 2019-08-22 19:09
[DEBUG] 2019-08-22T19:09:24.815Z [auto-type] Auto type event null
[DEBUG] 2019-08-22T19:09:24.817Z [auto-type] Get window title
[INFO ] 2019-08-22T19:09:24.818Z [launcher] spawn:starting
[INFO ] 2019-08-22T19:09:24.866Z [launcher] spawn:no-data
[INFO ] 2019-08-22T19:09:24.871Z [launcher] spawn:waiting

**Comment by antelle** [comment] 2019-08-22 19:13
Very interesting. I've prepared another patch, let's give it a try.  
Sorry for taking so much time, the thing is I can't repeat it on my Ubuntu somehow. Maybe because it's running in VirtualBox and the bug seems to be a random one.

**Comment by benzkji** [comment] 2019-08-22 19:20
indeed very strange. I'm on xubuntu/xfce, if this makes a difference for electron? guess not, but...

[DEBUG] 2019-08-22T19:18:35.076Z [auto-type] Auto type event null
[DEBUG] 2019-08-22T19:18:35.078Z [auto-type] Get window title
[INFO ] 2019-08-22T19:18:35.078Z [launcher] spawn:starting
[INFO ] 2019-08-22T19:18:35.120Z [launcher] spawn:no-data
[INFO ] 2019-08-22T19:18:35.125Z [launcher] spawn:no-data-destroy
[INFO ] 2019-08-22T19:18:35.130Z [launcher] spawn:waiting
[INFO ] 2019-08-22T19:18:35.130Z [launcher] spawn:no-data-after-write

**Comment by antelle** [comment] 2019-08-22 19:21
So, with this in logs, does it work?

**Comment by benzkji** [comment] 2019-08-22 19:21
sorry, forgot. no, not yet ;-)

**Comment by antelle** [comment] 2019-08-22 19:22
Weird, I don't have other ideas yet. I'll try to repeat it on my ubuntu.

**Comment by benzkji** [comment] 2019-08-22 19:24
...xubuntu introduced some xfce updates in 19.04 (from xfce 4.13). and in 19.10 it will introduce xfce 4.14. 

the problem is with launching the program that should get the window title, right?

**Comment by antelle** [comment] 2019-08-22 19:25
Yes, for some reason it doesn't get launched.

**Comment by antelle** [comment] 2019-08-22 19:51
So, I installed xubuntu-desktop and xfce, and I can repeat it! Looking into the issue now.

**Comment by antelle** [comment] 2019-08-22 20:04
Got exactly the same thing as you: either getWindowTitle works, or auto-type. Looks like it's fixed in this version, let's give it a go on your machine.

**Comment by benzkji** [comment] 2019-08-22 20:12
strike! works. thx man!

**Comment by antelle** [comment] 2019-08-22 20:13
Nice, thank you so much for spending your time on this!

It's interesting that both v1.19.0 and v1.19.1 work well on:
- default Ubuntu
- Xubuntu / Gnome
- everywhere else (macOS, Windows)

Well, maybe now it doesn't 😆. I'll dive into virtualboxes to test it and make a release soon if everything is okay.

So I assume, it's not even an issue in Electron, but has something to do with xubuntu-desktop + xfce.

**Comment by benzkji** [comment] 2019-08-22 20:16
xubuntu uses xfce by default. it's probably a xfce 4.13 problem? I was updating my computers to 19.04, and only after updating, discovered the bug in 1.19.0 (as 1.18.2 was no more working)...maybe it works on 18.04, that has older xfce components (4.12).

lot of versions ;-)

**Comment by antelle** [comment] 2019-08-22 20:22
I'm actually not sure whose bug is that. What I see that a child process is launched, but it doesn't understand that stdin is finished, so it's just waiting for it. Calling `destroy` probably flushes the stream, however it should do it in `end` instead. So I think it's a bug in Electron, but a very weird one, which manifests itself only on this OS/DM. Electron in its turn is using this via node.js, and node.js calls the API via libuv.

**Closed** 2019-08-22 20:40 UTC
Labels: bug

**Comment by antelle** [comment] 2019-08-22 20:43
Done, it's released

**Comment by benzkji** [comment] 2019-08-22 20:48
#yes
