### ISSUE TITLE
Backup Now gives "Error creating backup folder"

### ISSUE THREAD

**Issue by hameerabbasi** [keeweb/keeweb#391] opened 2016-09-29 06:15 UTC
# Actions Taken
1. Change backup folder to an already existing folder.
2. Click on "Backup Now"

# Expected Behavior
Backup file should appear in folder.

# Actual Behavior
I get an error message, saying "Error creating backup folder" with a header "Error writing backup file"

# Other information
Version 1.3.3, Windows.

Logs:
```
[INFO ] 2016-09-29T06:12:46.157Z [backup:Hameer's Password Storage] Backup folder does not exist
[DEBUG] 2016-09-29T06:12:46.157Z [storage-file] Make dir 
[ERROR] 2016-09-29T06:12:46.157Z [storage-file] Error making local dir  Error: ENOENT: no such file or directory, mkdir ''
[ERROR] 2016-09-29T06:12:46.157Z [backup:Hameer's Password Storage] Error creating backup folder Error: ENOENT: no such file or directory, mkdir ''
```

**Comment by antelle** [comment] 2016-09-29 06:23
duplicate of #382

**Comment by antelle** [comment] 2016-09-29 06:23
duplicate of #382

**Closed by antelle** 2016-09-29 06:23 UTC
Labels: bug, desktop, storage, windows
