### ISSUE TITLE
Popup menus sometimes cause Safari to freeze

### ISSUE THREAD

**Issue by gruenel** [keeweb/keeweb#626] opened 2017-05-15 14:24 UTC
I'm using a self-hosted KeeWeb on my NAS running Ubuntu Server 16.04 LTS, accessing a WebDAV database located on the same NAS.

Not sure how to reproduce this one reliably. Every once in a while, opening a popup context menu (like the one when you click "more..." in the entry view) causes the Safari tab to freeze.

When this happens, it looks like KeeWeb is creating more and more popup menus in an endless loop (I can see this because the "shadow" of the popup menu is becoming more and more opaque). This results in very high CPU usage and the inability to save the database. The only fix at this point is to reload the app.

Version info:
```
KeeWeb v1.4.1 (df218ae, 2017-03-26)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30
```

**Comment by antelle** [comment] 2017-05-15 17:47
I can't reproduce it, but some leaks do exist now. Let's leave it open and try to fix them.

**Comment by antelle** [comment] 2019-09-29 16:23
I believe this is fixed now. In the last version there were some fixed in dropdowns, if it's still there, please open a new issue.

**Closed by antelle** 2019-09-29 16:23 UTC
Labels: bug, performance
