### ISSUE TITLE
D'not build desktop-linux

### ISSUE THREAD

**Issue by SergeyDjam** [keeweb/keeweb#1670] opened 2020-12-30 16:03 UTC
Hi. How can I assemble desktop-linux? I would like to make the rpm package for the ROSA Linux distribution

yarn run desktop-linux output many errors

`yarn run grunt desktop-linux
yarn run v1.22.5
$ /home/builder/rpmbuild/BUILD/keeweb-1.16.6/node_modules/.bin/grunt desktop-linux
>> Local Npm module "grunt-appdmg" not found. Is it installed?
fatal: not a git repository (or any parent up to mount point /home/builder)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Loading "Gruntfile.js" tasks...ERROR
>> Error: Command failed: git rev-parse --short HEAD
>> fatal: not a git repository (or any parent up to mount point /home/builder)
>> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Running "clean:desktop" (clean) task
Verifying property clean.desktop exists in config...ERROR
>> Unable to process task.
Warning: Required config property "clean.desktop" missing. Use --force to continue.

Aborted due to warnings.

Execution Time (2020-12-30 16:02:29 UTC-0)
loading tasks  1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 1.3s

error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Your user-agent (from Settings/Help section)

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

**Comment by antelle** [comment] 2020-12-30 16:07
Hi!

> grunt-appdmg

That's an optional dependency, you can ignore this warning.

> Error: Command failed: git rev-parse --short HEAD

Have you checked out KeeWeb from git? Maybe you don't have git installed? It won't work from a simple folder without it being a git repo.

> Running "clean:desktop" (clean) task

I assume that's because of the git error above, it fails there.

> yarn

Never tried running any of KeeWeb tasks with `yarn`, although there shouldn't be issues, there can be something going wrong.

// you should remove sections not applicable to you, just so that the issue is concise and easy to read.

**Comment by SergeyDjam** [comment] 2020-12-30 16:14
I download released package https://github.com/keeweb/keeweb/archive/v1.16.6.tar.gz 
Unpacking it

**Comment by antelle** [comment] 2020-12-30 16:15
You won't build a desktop app from it

**Comment by SergeyDjam** [comment] 2020-12-30 16:15
Is that because it's not a git?

**Comment by antelle** [comment] 2020-12-30 16:16
yes

**Comment by SergeyDjam** [comment] 2020-12-30 16:18
it’s very sad

**Comment by antelle** [comment] 2020-12-30 16:19
What makes you sad about it, is there a complication cloning a git repo? It's possible to make it work from an archive, but needs a bit of work. But let's see, how does it impact you?

**Comment by antelle** [comment] 2020-12-30 16:58
Fixed in `develop`, now this works:
```
curl -L https://github.com/keeweb/keeweb/archive/develop.zip -o keeweb.zip
unzip develop.zip
cd keeweb-develop
npm ci
grunt default dev-desktop-linux
```

I hope this makes the sadness disappear 😉 🤷‍♀️ , happy new year! 🎄

**Closed by antelle** 2020-12-30 16:58 UTC
Labels: dev, question

**Comment by antelle** [comment] 2020-12-30 17:00
Just a note that `sha` will be set to `0` in case you build without git, so if you're going to redistribute it, it's better to build from a tag in the git repo.

**Comment by antelle** [comment] 2020-12-30 17:14
Added an option `--commit-sha`, by default it will fail if you build it not from git, but you have a possibility to run it like this:
```
grunt default dev-desktop-linux --commit-sha=xxx
```

**Comment by SergeyDjam** [comment] 2021-01-02 09:44
Thank you and Happy New Year! 
I maked patch on develop branch.  Building passed, but there are messages that break the buildings

```
yarn run grunt default desktop-linux --commit-sha=0000 --force
...
Running "csp-hashes:app" (csp-hashes) task
Warning: Expected 1 script(s), found 2 Used --force, continuing.
...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

how i can fix it?

**Comment by antelle** [comment] 2021-01-02 09:51
Don't use `--force`, it will ruin your package because it will miss something important and even if it builds, the app won't work in some way and you won't notice.
I don't think you patched it right. If you try this on `develop`, you will see that it works:
```
grunt default desktop-linux --commit-sha=xxx
```

**Comment by SergeyDjam** [comment] 2021-01-02 10:33
Yes, I started the build without force, but the build break

```
yarn run grunt default desktop-linux --commit-sha=0000
...
Running "csp-hashes:app" (csp-hashes) task
Warning: Expected 1 script(s), found 2 Use --force to continue.

Aborted due to warnings.
....
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by antelle** [comment] 2021-01-02 10:34
Yes that's what I meant, you should stop here and fix the issue, proceeding with `--force` after this will result in harder-to-debug issues. So you need to fix your patch.

**Comment by antelle** [comment] 2021-01-02 10:35
You need pick these three commits: 33763ab865af4f6a561d4206df8575a0252edee0, 014b6b23191a1ce5d0fa983f98e8877539fb98a9, 54a1860398c0bd0f141bcbcabefab78e2ef3612e

**Comment by antelle** [comment] 2021-01-02 10:36
Probably you just copied gruntfile.js which has other incompatible changes, it won't work on the release branch.

**Comment by SergeyDjam** [comment] 2021-01-02 10:38
Hm, i don't know what can be corrected here

```
cat keeweb.patch
*** keeweb-1.16.6/Gruntfile.js  2020-12-30 15:30:11.000000000 +0300
--- keeweb-develop/Gruntfile.js 2020-12-30 20:17:46.000000000 +0300
***************
*** 34,40 ****
      const getCodeSignConfig = () =>
          skipSign ? { identities: {} } : require('./keys/codesign.json');

!     const sha = execSync('git rev-parse --short HEAD').toString('utf8').trim();

      const webpackOptions = {
          date,
--- 34,52 ----
      const getCodeSignConfig = () =>
          skipSign ? { identities: {} } : require('./keys/codesign.json');

!     let sha = grunt.option('commit-sha');
!     if (!sha) {
!         try {
!             sha = execSync('git rev-parse --short HEAD').toString('utf8').trim();
!         } catch (e) {
!             grunt.warn(
!                 "Cannot get commit sha from git. It's recommended to build KeeWeb from a git repo " +
!                     'because commit sha is displayed in the UI, however if you would like to build from a folder, ' +
!                     'you can override what will be displayed in the UI with --commit-sha=xxx.'
!             );
!         }
!     }
!     grunt.log.writeln(`Building KeeWeb v${pkg.version} (${sha})`);

      const webpackOptions = {
          date,
***************
*** 263,269 ****
                  algo: 'sha512',
                  expected: {
                      style: 1,
!                     script: 2
                  }
              },
              app: {
--- 275,281 ----
                  algo: 'sha512',
                  expected: {
                      style: 1,
!                     script: 1
                  }
              },
              app: {
```

**Comment by antelle** [comment] 2021-01-02 10:51
Revert everything below `webpackOptions`

**Comment by SergeyDjam** [comment] 2021-01-02 11:25
Yes, i reverted  below webpackOptions... Build passed, but no good final... 

patch now
```
cat keeweb.patch
*** keeweb-1.16.6/Gruntfile.js  2020-12-30 15:30:11.000000000 +0300
--- keeweb-develop/Gruntfile.js 2020-12-30 20:17:46.000000000 +0300
***************
*** 34,40 ****
      const getCodeSignConfig = () =>
          skipSign ? { identities: {} } : require('./keys/codesign.json');

!     const sha = execSync('git rev-parse --short HEAD').toString('utf8').trim();

      const webpackOptions = {
          date,
--- 34,52 ----
      const getCodeSignConfig = () =>
          skipSign ? { identities: {} } : require('./keys/codesign.json');

!     let sha = grunt.option('commit-sha');
!     if (!sha) {
!         try {
!             sha = execSync('git rev-parse --short HEAD').toString('utf8').trim();
!         } catch (e) {
!             grunt.warn(
!                 "Cannot get commit sha from git. It's recommended to build KeeWeb from a git repo " +
!                     'because commit sha is displayed in the UI, however if you would like to build from a folder, ' +
!                     'you can override what will be displayed in the UI with --commit-sha=xxx.'
!             );
!         }
!     }
!     grunt.log.writeln(`Building KeeWeb v${pkg.version} (${sha})`);

      const webpackOptions = {
          date,
```

```
yarn run grunt default desktop-linux --commit-sha=0000
yarn run v1.22.5
$ /home/builder/rpmbuild/BUILD/keeweb-1.16.7/node_modules/.bin/grunt default desktop-linux --commit-sha=0000
>> Local Npm module "grunt-appdmg" not found. Is it installed?
Building KeeWeb v1.16.7 (0000)

Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "clean:desktop" (clean) task
>> 0 paths cleaned.

Running "eslint:app" (eslint) task

Running "eslint:desktop" (eslint) task

Running "eslint:build" (eslint) task

Running "eslint:plugins" (eslint) task

Running "eslint:util" (eslint) task

Running "copy:html" (copy) task
Copied 1 file

Running "copy:icons" (copy) task
Copied 17 files

Running "copy:manifest" (copy) task
Copied 2 files

Running "webpack:app" (webpack) task
Building fontawesome.woff2... ok: 1218ms, 147 icons, 13.37 KiB
Webpack Bundle Analyzer saved report to /home/builder/rpmbuild/BUILD/keeweb-1.16.7/tmp/stats/analyzer_report.html
Webpack Bundle Analyzer saved stats file to /home/builder/rpmbuild/BUILD/keeweb-1.16.7/tmp/stats/stats.json
asset js/app.js 1.28 MiB [emitted] [minimized] [big] (name: app)
asset css/app.css 119 KiB [emitted] (name: app)
asset js/runtime.js 1.3 KiB [emitted] [minimized] (name: runtime)
Entrypoint app [big] 1.4 MiB = js/runtime.js 1.3 KiB css/app.css 119 KiB js/app.js 1.28 MiB
runtime modules 3.62 KiB 6 modules
orphan modules 19.6 KiB [orphan] 5 modules
modules by path ./app/ 1.37 MiB (javascript) 123 KiB (css/mini-extract)
  modules by path ./app/scripts/ 860 KiB 205 modules
  modules by path ./app/templates/ 519 KiB 51 modules
  modules by path ./app/styles/*.scss 50 bytes (javascript) 123 KiB (css/mini-extract) 2 modules
  2 modules
modules by path ./node_modules/ 489 KiB
  modules by path ./node_modules/handlebars/ 39.3 KiB 22 modules
  modules by path ./node_modules/lodash/*.js 15.6 KiB 13 modules
  modules by path ./node_modules/argon2-browser/dist/ 48.8 KiB
    ./node_modules/argon2-browser/dist/argon2.js 14.6 KiB [optional] [built] [code generated]
      cjs full require argon2 ./app/scripts/util/kdbxweb/kdbxweb-init.js 108:33-58
    ./node_modules/argon2-browser/dist/argon2.wasm 34.2 KiB [built] [code generated]
      cjs require argon2-wasm ./app/scripts/util/kdbxweb/kdbxweb-init.js 110:33-55
      cjs self exports reference ./node_modules/argon2-browser/dist/argon2.wasm 1:0-14
external "null" 42 bytes [built] [code generated]
  cjs require crypto ./node_modules/kdbxweb/dist/kdbxweb.min.js 2:82-99
  cjs require xmldom ./node_modules/kdbxweb/dist/kdbxweb.min.js 2:100-117
moment (ignored) 15 bytes [optional] [built] [code generated]
  cjs require moment ./node_modules/pikaday/pikaday.js 15:23-40
webpack 5.11.1 compiled successfully in 31614 ms

Running "inline:app" (inline) task
Processing tmp/index.html as filetype html...
OK

Running "htmlmin:app" (htmlmin) task
Minified 1 files

Running "csp-hashes:app" (csp-hashes) task
Added CSP hashes: 1 style(s), 2 script(s)

Running "copy:content-dist" (copy) task
Created 1 directory, copied 4 files

Running "string-replace:service-worker" (string-replace) task

1 files created

Running "string-replace:manifest" (string-replace) task

2 files created

Running "copy:dist-icons" (copy) task
Copied 17 files

Running "copy:dist-manifest" (copy) task
Copied 2 files

Running "clean:desktop" (clean) task
>> 0 paths cleaned.

Running "copy:desktop-html" (copy) task
Copied 1 file

Running "copy:desktop-app-content" (copy) task
Created 2 directories, copied 10 files

Running "string-replace:desktop-public-key" (string-replace) task

3 files created

Running "electron:linux" (electron) task
Packaging app for platform linux x64 using electron v11.0.3

Running "chmod:linux-desktop-x64" (chmod) task
>> 1 file had their `chmod` mode set to "4755".

Running "copy:native-modules-linux-x64" (copy) task
Copied 4 files

Running "copy:desktop-update" (copy) task
Copied 1 file

Running "copy:desktop-update-helper" (copy) task
Copied 2 files

Running "sign-desktop-files:desktop-update" (sign-desktop-files) task


Execution Time (2021-01-02 11:12:18 UTC-0)
loading tasks    1.5s  ▇▇▇▇▇ 2%
eslint:app      20.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 32%
eslint:desktop  678ms  ▇▇ 1%
eslint:build    995ms  ▇▇▇ 2%
webpack:app     35.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 54%
htmlmin:app     892ms  ▇▇▇ 1%
electron:linux   4.3s  ▇▇▇▇▇▇▇▇▇▇▇▇ 7%
Total 1m 5.2s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: Bad exit status from /var/tmp/rpm-tmp.86932 (%build)
```
But there are no bugs, I do not understand

**Comment by antelle** [comment] 2021-01-02 11:26
How did you run it? It shouldn't do `sign-desktop-files:desktop-update`, you need a key for this. And I assume, you don't need the desktop update at all.

**Comment by SergeyDjam** [comment] 2021-01-02 11:30
i run 
```
rpmbuild -ba keeweb.spec
```

my spec:
```
cat keeweb.spec 
%define     oname KeeWeb
%define     _optdir /opt
%define     debug %nil
%define     debug_package %nil

Name:       keeweb
Version:    1.16.7
Release:    1
Summary:    Password manager
URL:        https://keeweb.info
Source0:    https://github.com/%{name}/%{name}/archive/v%{version}/%{name}-%{version}.tar.gz
Source1000: %{name}.rpmlintrc
Patch0:     %{name}.patch
License:    MIT
Group:      Development/Other
BuildRequires:  npm
BuildRequires:  yarn
BuildRequires:  nodejs
BuildRequires:  imagemagick
BuildRequires:  git-core
BuildRequires:  pkgconfig(libsecret-1)

%description
Free cross-platform password manager compatible with KeePass

%prep
%setup -q
%patch0 -p1

%build
#npm ci
#./node_modules/.bin/grunt default desktop-linux --commit-sha=0000 --force
yarn
yarn run grunt default desktop-linux --commit-sha=0000
#--force



%install
install -d %{buildroot}%{_optdir}/%{name} %{buildroot}%{_datadir} %{buildroot}%{_bindir}
%ifarch x86_64
cp -a tmp/desktop/%{name}-linux-x64/* %{buildroot}%{_optdir}/%{name}
%else

ls -la tmp/desktop

cp -a tmp/desktop/%{name}-linux/* %{buildroot}%{_optdir}/%{name}
%endif

# install data shares
cp -a package/deb/usr/share/* %{buildroot}%{_datadir}

# install icons
cd graphics

for x in 16 32 24 48 64 96 128 256 512; do
install -d %{buildroot}%{_iconsdir}/hicolor/${x}x${x}/apps/
convert -resize ${x}x${x} 512x512.png %{buildroot}%{_iconsdir}/hicolor/${x}x${x}/apps/%{name}.png
done

# start script
cat > %{buildroot}%{_bindir}/%{name} << EOF
#!/bin/bash
cd %{_optdir}/%{name}
./%{name}
EOF

chmod +x %{buildroot}%{_bindir}/%{name}


# fix setuid perrmissions
chmod 0755 %{buildroot}%{_optdir}/%{name}/chrome-sandbox

%files
%doc README.md LICENSE
%{_bindir}/%{name}
%{_optdir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/appdata/*.xml
%{_datadir}/mime/*
%{_iconsdir}/hicolor/*/apps/%{name}.png
```

**Comment by antelle** [comment] 2021-01-02 11:31
I see, found your command line. Well, you can run `clean:desktop build-desktop-app-content build-desktop-executables-linux` instead of `desktop-linux`.

**Comment by antelle** [comment] 2021-01-02 11:33
The desktop update artifact will disappear in v1.17, so `desktop-linux` will eventually work, but it's not done yet.

**Comment by SergeyDjam** [comment] 2021-01-02 11:35
> I see, found your command line. Well, you can run `clean:desktop build-desktop-app-content build-desktop-executables-linux` instead of `desktop-linux`.

yes, i try it now

**Comment by SergeyDjam** [comment] 2021-01-02 11:43
not, 
```
yarn run grunt build-desktop-app-content --commit-sha=0000
yarn run v1.22.5
$ /home/builder/rpmbuild/BUILD/keeweb-1.16.7/node_modules/.bin/grunt build-desktop-app-content --commit-sha=0000
>> Local Npm module "grunt-appdmg" not found. Is it installed?
Building KeeWeb v1.16.7 (0000)

Running "copy:desktop-html" (copy) task
Warning: Unable to read "dist/index.html" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.


Execution Time (2021-01-02 11:39:52 UTC-0)
loading tasks  1.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 1.5s

error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: Bad exit status from /var/tmp/rpm-tmp.49848 (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.49848 (%build)
```

**Comment by antelle** [comment] 2021-01-02 11:46
It's because the html is not built, so the full command should be: 

`grunt default clean:desktop build-desktop-app-content build-desktop-executables-linux`.

**Comment by SergeyDjam** [comment] 2021-01-03 14:33
> It's because the html is not built, so the full command should be:
> 
> `grunt default clean:desktop build-desktop-app-content build-desktop-executables-linux`.

Fine. It works! Many thanks
