### ISSUE TITLE
"TypeError: Cannot read property 'id' of undefined" on unlock

### ISSUE THREAD

**Issue by PaulAnnekov** [keeweb/keeweb#652] opened 2017-06-03 13:24 UTC
- what were your actions?
Opened my kdbx DB for the first time, enabled keepasshttp plugin, connected to Chrome extension, was working good. Then minimized app/unlocked it several times.
- what was wrong?
On next unlock I see `TypeError: Cannot read property 'id' of undefined` error and can't unlock DB anymore. `keepassx` works OK.
- app version
1.5.3-1
- your user-agent (from Settings/Help section)
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.5.3 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36`
- does it happen on Demo or New database?
My personal DB.
- please, open dev tools in your browser and attach output log from Console tab 
```
2017-06-03T13:07:30.048Z [plugin:keewebhttp] Loading plugin with resources js (local) index.html:formatted:26251
2017-06-03T13:07:30.053Z [storage-plugin-files] Load keewebhttp_plugin.js index.html:formatted:26251
2017-06-03T13:07:30.054Z [storage-plugin-files] Loaded keewebhttp_plugin.js 1ms index.html:formatted:26257
2017-06-03T13:07:30.054Z [plugin:keewebhttp] Installing plugin resources index.html:formatted:26251
2017-06-03T13:07:30.066Z [plugin:keewebhttp] Plugin script installed 2ms index.html:formatted:26257
2017-06-03T13:07:30.067Z [plugin:keewebhttp] Install complete 17ms index.html:formatted:26257
2017-06-03T13:07:30.068Z [plugin-mgr] Loaded 1 plugins 23ms index.html:formatted:26257
2017-06-03T13:07:30.213Z [app] Started in 543ms ¯\_(ツ)_/¯ index.html:formatted:26251
2017-06-03T13:07:30.583Z [keewebhttp] Server running at http://127.0.0.1:19455/ index.html:formatted:26257
2017-06-03T13:07:34.941Z [open:pass] File open request index.html:formatted:26257
2017-06-03T13:07:34.941Z [open:pass] Open file from storage file index.html:formatted:26257
2017-06-03T13:07:34.941Z [open:pass] Stat file index.html:formatted:26251
2017-06-03T13:07:34.942Z [storage-file] Stat /home/file/path/wont/show/pass.kdbx index.html:formatted:26251
2017-06-03T13:07:34.943Z [storage-file] Stat done /home/file/path/wont/show/pass.kdbx 1ms index.html:formatted:26257
2017-06-03T13:07:34.943Z [open:pass] Open file from storage (1496495146793, local 1496495146793) index.html:formatted:26257
2017-06-03T13:07:34.943Z [open:pass] Load from storage index.html:formatted:26251
2017-06-03T13:07:34.943Z [storage-file] Load /home/file/path/wont/show/pass.kdbx index.html:formatted:26251
2017-06-03T13:07:34.944Z [storage-file] Loaded /home/file/path/wont/show/pass.kdbx 1496495146793 1ms index.html:formatted:26257
2017-06-03T13:07:34.944Z [open:pass] Open file from content loaded from storage index.html:formatted:26269
2017-06-03T13:07:35.470Z [file] Error opening file undefined Cannot read property 'id' of undefined TypeError: Cannot read property 'id' of undefined
    at n.<anonymous> (file:///opt/keeweb-desktop/resources/app/index.html:15:2715)
    at Array.forEach (native)
    at n.setGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:2664)
    at Function.c.fromGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:6846)
    at n.<anonymous> (file:///opt/keeweb-desktop/resources/app/index.html:15:2626)
    at Array.forEach (native)
    at n.setGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:2527)
    at Function.c.fromGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:6846)
    at n.<anonymous> (file:///opt/keeweb-desktop/resources/app/index.html:17:13129)
    at Array.forEach (native)o.error @ index.html:formatted:26269
index.html:formatted:26269
2017-06-03T13:07:35.470Z [open-view] Error opening file TypeError: Cannot read property 'id' of undefined
    at n.<anonymous> (file:///opt/keeweb-desktop/resources/app/index.html:15:2715)
    at Array.forEach (native)
    at n.setGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:2664)
    at Function.c.fromGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:6846)
    at n.<anonymous> (file:///opt/keeweb-desktop/resources/app/index.html:15:2626)
    at Array.forEach (native)
    at n.setGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:2527)
    at Function.c.fromGroup (file:///opt/keeweb-desktop/resources/app/index.html:15:6846)
    at n.<anonymous> (file:///opt/keeweb-desktop/resources/app/index.html:17:13129)
    at Array.forEach (native)
```
Screenshot:

![image](https://cloud.githubusercontent.com/assets/1203892/26753873/a264c994-4878-11e7-8e36-624836a44f00.png)

**Comment by antelle** [comment] 2017-06-03 13:31
It looks like, the db is corrupted, weird. Do you know a way to repeat it?

**Comment by PaulAnnekov** [comment] 2017-06-03 13:41
> Do you know a way to repeat it?
No :(.

> Does the error happen if you restart the app?
Yes. I can't unlock it anymore. But `keepassx` works.

**Comment by antelle** [comment] 2017-06-03 13:44
I'm trying to understand how did it end up with entry without uuid.
Could you please inspect this entry (`e` variable, in your case)? Was it added by keewebhttp? 
![entry](https://cloud.githubusercontent.com/assets/633557/26754046/6b0750ca-4873-11e7-89d9-ed12b50e7ab0.png)

**Comment by PaulAnnekov** [comment] 2017-06-03 14:04
wow, looks like somebody (keeweb? keewebhttp?) copied existing entry. Its name now is original entry name + " Copy". And I remember before this bug occurred I opened a website from this entry, but this website didn't have any login feature anymore.

I think duplicate deletion can help. Do you need any additional info or I can delete it?

**Comment by antelle** [comment] 2017-06-03 14:12
Reproduced. Probably you used Make a Copy button. It's broken now. Fixing...
Could you please delete this copy from the db (and from trash as well), e.g. in keepass or keepassx, and check if the db can be opened in keeweb after it?

**Comment by PaulAnnekov** [comment] 2017-06-03 14:22
Ah, yes. I was trying to copy a website url, clicked on it with right mouse button and found nothing related in context menu except "Make a Copy". Clicked on it, nothing appeared in buffer so I forgot about this.

**Comment by antelle** [comment] 2017-06-03 14:23
Yes, that was it. I'm already building the patch... will be released shortly. Do you need help restoring your db?

**Closed** 2017-06-03 14:50 UTC
Labels: bug

**Comment by PaulAnnekov** [comment] 2017-06-03 15:23
No, thank you. Restored already :).

**Comment by antelle** [comment] 2017-06-03 15:26
It got broken in previous hotfixes, sorry for that, forgot to test entry copy 😔

**Comment by PaulAnnekov** [comment] 2017-06-03 17:08
Good moment to start writing integration tests :)

**Comment by davidroeca** [comment] 2019-12-19 03:50
I'm still running into this issue. Mentioned in #678 as well.

**Comment by davidroeca** [comment] 2019-12-19 03:51
However, I guess it may be different from the original issue because it's more related to syncing rather than unlocking.
