### ISSUE TITLE
Cannot autotype to fullscreen windows on OSX

### ISSUE THREAD

**Issue by cttttt** [keeweb/keeweb#430] opened 2016-11-04 21:20 UTC
What did I do?
---

- Start Keeweb and TextEdit (just some other app with a text box focussed).
- Start a Terminal.
- Use the green button in the titlebar to make the terminal window a fullscreen window.
- Hit Command-Space and enter Keeweb<enter> to bring up Keeweb.
- NOTICE: The display slides over to the workspace where Keeweb was running.
- In Keeweb, search for an entry and hit CTRL+T.
- ISSUE: The password is auto-typed into the TextEdit window.

What did I expect?
----

- Since it seems like the last focused window was the Terminal, I'd expect focus to switch to it before the auto-type occurs.

Details
----

Keeweb v1.3.3.

I'll try to dig further and see if I can figure out what's going on here, but ... if it's a hard restriction preventing this sort of AutoType, lemme know :-)

**Comment by antelle** [comment] 2016-11-06 19:21
This is a duplicate of #307

**Closed by antelle** 2016-11-06 19:21 UTC

**Comment by andremann** [comment] 2020-12-07 15:51
It looks like this is working in v1.16.1 (2020-12-04)!!
