### ISSUE TITLE
Keeweb Desktop (Windows) stuck on unplugged monitor

### ISSUE THREAD

**Issue by tbradsha** [keeweb/keeweb#954] opened 2018-07-05 21:58 UTC
I traditionally have a two-monitor setup. After putting the laptop to sleep and unplugging the monitor, the Keeweb window is stuck on the non-existent monitor. Killing the app and restarting it doesn't help; it keeps respawning on the other monitor.

Until this bug is squashed, is there a workaround to somehow reset the preferences (or better yet, edit some config file)?

**Comment by mitcom** [comment] 2018-07-06 08:45
I don't know how KeeWeeb is rendered and displayed, but have you tried to move that window from other monitor to your main one? I mean by using [Win] + [Arrow Left] few times

**Comment by tbradsha** [comment] 2018-07-06 16:38
**Workaround:** [AltKey] + [Space] will activate the shortcut menu, and then selecting "Move" allows you to move the window to the new screen.

Yes, I tried using [WinKey] + [Left Arrow], but to no avail. Also odd is that the [WinKey] + [Tab] doesn't pull up the "Desktop" view (not sure the terminology in Windows 10) unless the app is either closed or in the notification tray (not just minimized).

[AltKey] + [Tab] shows the window thumbnail, so I can at least see if it's prompting me to log in or if there's an error, but I can't drag it around in that mode.

**Comment by Coises** [comment] 2018-09-08 18:00
Probable workaround (I don’t have a second monitor handy, so I can’t test):

* Close KeeWeb by any means necessary.
* Type **WinKey**+**R**, enter `%appdata%\KeeWeb` and click OK.
* Delete the `window-position.json` file.
* Restart KeeWeb.

I see that GitHub has [a similar problem](https://github.com/desktop/desktop/issues/2107) which was reported over a year ago and still hasn’t been fixed. I haven’t looked at the relevant Electron APIs yet... it’s possible that Electron doesn’t expose the information we need to solve this, or maybe the GitHub folks just haven’t had time to fix it.

**Comment by Coises** [comment] 2018-09-08 18:04
@tbradsha: Does it make any difference if you actually disable the second monitor (**WinKey**+**P** and select main screen only) before you disconnect it?

**Comment by tbradsha** [comment] 2018-09-13 02:03
@Coises Removing the window-position.json file does the trick, so that's a great workaround.

I do run a headless (Linux) server, and it does seem it is standard cross-platform behaviour with the first screen/monitor to not care whether or not an initial screen exists, but second monitors do seem to trigger changes in Windows, macOS, and Linux. When I disconnect the monitor in Windows, all other application windows move to the main screen (the laptop screen). So I don't think this is expected behaviour to orphan a window in a non-existent position in this case.

As for WinKey+P, the shortcut still functions on one monitor, but as far as Windows is concerned, there's only one monitor, and selecting "PC screen only" doesn't fix it.

**Comment by tbradsha** [comment] 2018-09-13 02:10
Note too that it definitely is saving as if on the second screen due to the animations shown (just like the GitHub issue referenced above). I'd guess they're related issues.

**Comment by Coises** [comment] 2018-09-13 07:52
@tbradsha:

The next time this happens, before you delete the `window-position.json` file, would you make a copy of its contents (it’s just around 135 characters of plain text) and paste it into a comment?

I have a hunch I know what’s happening, but without a second monitor, I can’t test it. Forgive the geekish that follows, but I want to keep a note of this.

KeeWeb [checks to see if it should restore the old window position](https://github.com/keeweb/keeweb/blob/376c1a9cbc9acf2bad9e407b5475b6db69f039ec/desktop/app.js#L249) by seeing whether the bounds of the display on which the window is to be shown have changed. To do that, it uses an Electron function, which delegates to a Chromium function, which [delegates](https://chromium.googlesource.com/chromium/chromium/+/master/ui/gfx/screen_win.cc#78) to a Windows API (MonitorFromRect) using a flag (MONITOR_DEFAULTTONEAREST) that causes it ultimately to get the bounds of the *nearest* monitor to the specified window position. If KeeWeb happens to save the window position *after* the secondary monitor is disconnected, it will save the bounds of the primary monitor... which of course will match perfectly with the bounds of the primary monitor when it tries to restore. KeeWeb never checks to see that the window it’s about to restore actually is within those bounds.

Another test you could do which could help verify whether my guess is correct is to exit KeeWeb completely (don’t just minimize it or send it to the taskbar) *before* you disconnect the secondary monitor. Then disconnect the secondary monitor, then see if it opens correctly on the primary monitor.

None of this explains, though, why the window doesn’t relocate when the secondary monitor is disconnected, as it appears happens in other Windows applications. Several Electron-based projects have this issue, too: [Atom](https://github.com/atom/atom/issues/6939), [GitHub](https://github.com/desktop/desktop/issues/2107), [RocketChat](https://github.com/RocketChat/Rocket.Chat.Electron/issues/380), probably [Hyper](https://github.com/zeit/hyper/issues/1608) (though they report only the restoring issue). As far as I can tell, some have succeeded in getting the window to *restore* to the correct monitor—which KeeWeb can fix, too, if the cause turns out to be what I guessed above—but no one seems to know why Electron (or Chromium?) windows don’t just move to the primary monitor when the secondary monitor is disconnected.

**Comment by Coises** [comment] 2018-09-21 21:09
I got hold of a second monitor, and I’ve been able to reproduce most of this on Windows 7. Problems occur when KeeWeb is minimized — whether to the taskbar or to the system tray — and the monitor on which KeeWeb was last displayed is disconnected while KeeWeb is still running and still minimized.

Attempting to restore the window causes it to “restore” to the disconnected monitor. I don’t entirely understand why this is happening. Other applications which don’t do anything special to check for this condition come back on the primary monitor, and I don't see anything in the KeeWeb code that would force the window onto the wrong monitor. I can only guess that it’s an Electron peculiarity, and that we need to mitigate that by checking whenever we restore a window that the monitor to which it is to be restored is still active.

Closing KeeWeb in this state (whether you first attempted to restore the window or not) causes inconsistent data to be written to `window-position.json` (as I guessed above).

@antelle: When KeeWeb checks to see if it should restore the saved window position at startup, it does so by determining [whether the bounds of the display nearest to the position at which the window is to be shown have changed](https://github.com/keeweb/keeweb/blob/376c1a9cbc9acf2bad9e407b5475b6db69f039ec/desktop/app.js#L249) from what they were when the window position was last updated. The “obvious” thing to do would have been simply to check whether the window boundaries lie within the boundaries of the nearest display. Do you know/remember why the method KeeWeb uses was chosen?

I’m pretty sure I can work out a commit to fix this problem, but I’m concerned that I don’t understand the rationale behind the method used to determine whether the data in `window-position.json` should be honored when KeeWeb starts.

**Comment by antelle** [comment] 2018-09-21 21:38
> why the method KeeWeb uses was chosen?

Probably it was a copy-pasted from some package (or another electron app) saving window position, which worked quite well.

**Comment by tbradsha** [comment] 2018-09-28 02:35
Thanks! I've been MIA for a bit, and haven't had my monitor available. I'm now available to test/check anything as needed, though it seems perhaps the information requested has been provided.

**Comment by antelle** [comment] 2018-09-28 06:19
@tbradsha there's a PR with a fix: https://github.com/keeweb/keeweb/pull/1002
Testing it on different platforms would be very helpful.
I can build an executable, if you prefer.

**Comment by tbradsha** [comment] 2018-09-28 15:47
If you could build an executable, that'd be great!

**Closed** 2019-01-07 18:17 UTC
