### ISSUE TITLE
Empty UUID in groups

### ISSUE THREAD

**Issue by Platzer** [keeweb/keeweb#1286] opened 2019-10-05 18:52 UTC
**Describe the bug**
When sync with Dropbox the error `Sync error: TypeError: e.uuid is undefined` occurs.

**To Reproduce**
Occurs immediatly in the WebApp when opening key file from Dropbox. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3358663/66259496-f8265480-e7b1-11e9-8a97-0458a351ed61.png)

**Environment**
Firefox 69.0.2

**Comment by antelle** [comment] 2019-10-05 18:59
Hi! Does this happen if you remove the file from keeweb and add it again?

**Comment by Platzer** [comment] 2019-10-05 19:00
Yes, now i cannot open it cause of the same error.

**Comment by antelle** [comment] 2019-10-05 19:01
Looks like the file is corrupted. Could you please describe what happened to this file since it was successfully opened last time?

**Comment by Platzer** [comment] 2019-10-05 19:03
Nothing... just updated Keeweb today and now its not working anymore... I saved the file from cache to disk and tried to open it... same error.

**Comment by antelle** [comment] 2019-10-05 19:07
That's weird, what do you see in the console when you open the file, same error?

**Comment by Platzer** [comment] 2019-10-05 19:12
I downloaded KeeWeb 1.11.5 desktop app... could not open the file. Now i restored to the version before the last change now the file works again... I will have a look into it, maybe i can figure out what went wrong! thx for the quick help!

**Comment by antelle** [comment] 2019-10-05 19:13
I uploaded a build with some more debugging info to https://beta.keeweb.info. Could you please try opening the broken file there? It prints what's get passed to `setGroup`, what I'm interested in, the last record before it fails: does it have `uuid`?

**Comment by Platzer** [comment] 2019-10-05 19:21
Yes the last entry has a uuid... and its a regular entry... I will try to open the file tomorrow in anther app keypas app... maybe i can find out more

**Comment by antelle** [comment] 2019-10-05 19:22
I mean the first thing, does it have uuid here? 
<img width="575" alt="66259736-2194af80-e7b5-11e9-9c8e-749190a4b0bd" src="https://user-images.githubusercontent.com/633557/66259791-302f9680-e7b6-11e9-8d1b-083b9656eb69.png">

**Comment by antelle** [comment] 2019-10-05 19:26
Also what happens if you open it in another browser, for example, Chrome? Which line and column number do you see in the stack trace?

**Comment by antelle** [comment] 2019-10-06 06:10
If you still have the broken file, I'd appreciate your help with debugging it, because the issue seems to be very weird and looks like we can break the file, however I don't understand how.  
If you don't provide info, I'll have to close the issue because I can't reproduce it.

**Comment by Platzer** [comment] 2019-10-07 07:19
The last entry before the fail has the {{uuid}} property. 
I'm not sure if _KeeWeb_ has broken the file. I'm using [KeePass Touch](https://apps.apple.com/de/app/keepass-touch/id966759076) on my phone (sync via _Dropbox_), normally just for reading. Looking into the _Dropbox_ Version history I'm not sure if the broken file was created by _KeeWee_.

**Comment by Platzer** [comment] 2019-10-07 09:07
I used [KeePassLib](https://www.nuget.org/packages/KeePassLib/) to write a little F# script to read all entries in the "corrupted" file. I could not find any entry with a missing `Uuid`.

**Comment by antelle** [comment] 2019-10-07 16:51
What happens if you export the corrupted file as XML and then import it in KeeWeb?

**Comment by antelle** [comment] 2019-10-07 17:09
I made a page where you can convert a file to xml: https://beta.keeweb.info/kdbx-to-xml.html
It doesn't upload it anywhere, you can also save the page to do it locally.
But please remove all passwords from the xml after you export it.

**Comment by Platzer** [comment] 2019-10-08 10:27
I found an entry with an empty `<UUID/>` and I quite sure that I created it with KeePass Touch on my phone. So I think _KeeWeb_ didn't broke the file.

Interesting is that _KeePassLib_ has no problems with the empty `UUID`, it has simply generated a new one.

**Comment by antelle** [comment] 2019-10-08 17:00
Okay, no action required from our side.

**Comment by pappasam** [comment] 2019-10-17 01:48
I just had this exact same issue. I re-saved my keepass file with KeePass Touch and the problem was resolved. Thanks @Platzer for raising this issue, I was tearing my hair out!

**Comment by antelle** [comment] 2019-10-17 16:59
@pappasam do you remember in which app you saved this file last time? I wonder how this happens, is it KeeWeb or other apps that create such files without ids?

**Comment by antelle** [comment] 2019-10-17 17:00
Looks like this happens quite often, so I'm thinking maybe there's a way to do it in KeeWeb? This would be a problem of course.

**Comment by aragos** [comment] 2019-10-21 17:08
I ran into this as well (actually the error from duped issue #1301). Appears to have been caused by adding a password using KeePass Touch. Editing and saving the file in KeePass Touch fixed the problem.

**Comment by antelle** [comment] 2019-10-21 17:31
@aragos could you please describe the steps to reproduce it? I'd like to make sure it's not caused by keeweb.

**Comment by antelle** [comment] 2019-10-26 17:46
I've added a hack for this, so KeeWeb will generate IDs if they're missing, however it's better to ask KeePass Touch developers to fix it, it can introduce sync issues.

**Closed** 2019-10-26 19:50 UTC
Labels: enhancement
