### ISSUE TITLE
WebApp not able to list files on Google drive 

### ISSUE THREAD

**Issue by gynet** [keeweb/keeweb#799] opened 2017-12-08 05:20 UTC
- what were your actions?
Open db file from google drive 
- what was wrong?
After authentication, nothing happen, no option to choose a file

- app version 

https://beta.keeweb.info/

- your user-agent (from Settings/Help section)
KeeWeb v1.6.1 (349320c, 2017-12-07)
Environment: web
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

- does it happen on Demo or New database?
My personal db

- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

(index):1 2017-12-08T05:18:54.906Z [storage-gdrive] OAuth error no token undefined

P.S. I am using Google + phone authentication

**Comment by gynet** [comment] 2017-12-08 05:20
No issue with latest desktop version

**Comment by antelle** [comment] 2017-12-08 18:02
Hi!
Could you please paste app logs? I can't repeat it... works fine for me. Is there anything special about your account? Like, it's a business account, or something else...

**Comment by gynet** [comment] 2017-12-08 18:15
Hi Antelle,

Here is the only log it has, it only repo on web. Tried on a different laptop, the same issue. 

- It's my personal google account, the only special thing I can think is I enabled the two-way authentication. 

- It's not a shared file. even I can not get into google drive to pick up my db, it just silently close the authentication window after I type my account and authenticate with mine phone. 

- Also, the other issue, there is a **pop-up** window for Google authentication each time for login into Keeweb desktop client. Seems a regression since last two builds

- Here are the logs grab from Chrome devtool
```
(index):1 2017-12-08T18:05:00.315Z [app] Started in 967ms ¯\_(ツ)_/¯
(index):1 2017-12-08T18:05:08.777Z [storage-gdrive] OAuth error no token undefined
a.error @ (index):1
(index):1 2017-12-08T18:05:52.729Z [storage-gdrive] OAuth error no token undefined
```

**Comment by antelle** [comment] 2017-12-08 18:17
Interesting, I'll try to investigate.
I also have 2fa enabled on accounts but it can list files.

**Comment by gynet** [comment] 2017-12-08 18:42
**Update**: I checked my account 2fa was off,  

So it not a true "2 way authentication "  

it's "Sign in with your phone instead of a password" 
https://support.google.com/accounts/answer/6361026?co=GENIE.Platform%3DAndroid&hl=en

![untitled](https://user-images.githubusercontent.com/2174522/33780139-8c2e59e0-dc04-11e7-87cf-df0b2f4d9113.png)

**Comment by antelle** [comment] 2017-12-08 18:44
Interesting.
What happens if you log in with your password?
(I won't be able to check phone logins, it seems to be Android-only)

**Comment by gynet** [comment] 2017-12-08 18:48
Wonder if you have interest try it on a VM?

**Comment by antelle** [comment] 2017-12-08 18:48
And if you're logged in?

**Comment by antelle** [comment] 2017-12-08 18:51
> Use password or other options
Could you please paste a screenshot of this popup?

**Comment by gynet** [comment] 2017-12-08 18:52
I was using Chrome incognito mode and having the issue after I type password or authentication with my phone. 

If I use my normal mode with **Google account already login in**, the keeweb website will silently close the popup after I choosing my Google account

**Comment by antelle** [comment] 2017-12-08 18:57
Ok, I'll try to check different login options.

**Comment by jochec** [comment] 2017-12-09 09:24
I also face the issue with pop-up window for Google authentication each time for login . This started with upgrade to v1.6.1, there was no issues in v1.5.6.

`KeeWeb v1.6.1 (09b1c60, 2017-12-03)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.1 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36`

`[INFO ] 2017-12-09T09:19:17.025Z [app] Started in 808ms ¯\_(ツ)_/¯
[INFO ] 2017-12-09T09:19:17.028Z [updater] Next update check will happen in 86215s
[INFO ] 2017-12-09T09:19:21.963Z [open:KeePass] File open request
[INFO ] 2017-12-09T09:19:21.964Z [open:KeePass] Open file from cache, will sync after load gdrive
[DEBUG] 2017-12-09T09:19:21.964Z [storage-cache] Load 5a423fcb-8457-fc23-9e0b-7b73de7c438d
[DEBUG] 2017-12-09T09:19:21.969Z [storage-cache] Loaded 5a423fcb-8457-fc23-9e0b-7b73de7c438d 1ms
[INFO ] 2017-12-09T09:19:21.969Z [open:KeePass] Loaded file from cache null
[INFO ] 2017-12-09T09:19:22.310Z [file] Opened file KeePass: 338ms, 6000 rounds, 18 kB
[DEBUG] 2017-12-09T09:19:22.311Z [app] Add last open file 5a423fcb-8457-fc23-9e0b-7b73de7c438d KeePass gdrive 1NmkBCkAE8AyoDz-qyhD7JS2C6wtfEHMn 0B_4FWO3dzW1CWjZadmJWenJQVkRRQUQ3TWwzbVdzcjVHY09FPQ
[INFO ] 2017-12-09T09:19:22.482Z [open:KeePass] Sync just opened file
[INFO ] 2017-12-09T09:19:22.496Z [sync:KeePass] Sync started gdrive 1NmkBCkAE8AyoDz-qyhD7JS2C6wtfEHMn {}
[INFO ] 2017-12-09T09:19:22.498Z [sync:KeePass] Stat file
[DEBUG] 2017-12-09T09:19:22.499Z [storage-gdrive] OAuth: popup opened
[DEBUG] 2017-12-09T09:20:15.819Z [storage-gdrive] OAuth token received
[DEBUG] 2017-12-09T09:20:15.819Z [storage-gdrive] Stat 1NmkBCkAE8AyoDz-qyhD7JS2C6wtfEHMn
[DEBUG] 2017-12-09T09:20:16.261Z [storage-gdrive] Stated 1NmkBCkAE8AyoDz-qyhD7JS2C6wtfEHMn 0B_4FWO3dzW1CWjZadmJWenJQVkRRQUQ3TWwzbVdzcjVHY09FPQ 441ms
[INFO ] 2017-12-09T09:20:16.262Z [sync:KeePass] Stat found same version, not modified
[INFO ] 2017-12-09T09:20:16.262Z [sync:KeePass] Sync finished no error`

**Comment by antelle** [comment] 2017-12-09 10:01
@jochec but what is the issue? I see it's ok in logs.

**Comment by jochec** [comment] 2017-12-09 10:04
Yes, logs are OK. But there is a pop-up for Google login everytime I open the app. In previous version I just logged once and GDrive synchonization worked without relogging every time.

**Comment by antelle** [comment] 2017-12-09 10:06
@jochec does it just open a popup and close it immediately, or asks you for credentials?

**Comment by jochec** [comment] 2017-12-09 10:09
Asks for credentials each time. Without loging in again synchronization won't work.

**Comment by antelle** [comment] 2017-12-09 10:34
Now I understand why. Previous version allowed to save cookies in webapp, and they're deleted on startup in v1.6.1. I'll think how to solve it.

**Comment by antelle** [comment] 2017-12-09 11:23
@jochec pushed a fix for cookies: 334e439f94e775c5049b18baded612f9e117d648, now Google Drive will remember for credentials.
However, it has nothing to do with the original issue.

**Comment by antelle** [comment] 2017-12-09 11:41
@gynet I've added additional logging to understand it.
Please try on beta again. Now it should say: `Strange OAuth token` and show the token received. Please expand this token object and paste here (but of course remove all data values, i.e. things like "3w4t3$Ts34t"). I'm interested in keys we get, because I don't understand what it is.

**Comment by gynet** [comment] 2017-12-09 19:44
Hi Antelle, I've tried on beta. It's still the same. 

(index):1 2017-12-09T19:43:54.551Z [storage-gdrive] OAuth error no token undefined

**Comment by antelle** [comment] 2017-12-09 19:45
It is of course the same, but it should print the data in `Strange OAuth token`, as mentioned in my message above.
Could you please check what's there?

**Comment by gynet** [comment] 2017-12-09 19:50
No additional logs appear. remain the same. Tried again. Here are all the console output. 


2017-12-09T19:46:20.420Z [app] Started in 1162ms ¯\_(ツ)_/¯
(index):1 2017-12-09T19:46:23.884Z [storage-gdrive] OAuth error no token undefined

**Comment by antelle** [comment] 2017-12-09 19:54
Probably it's because of weird chrome defaults. Please check Verbose here:
<img width="241" alt="logs" src="https://user-images.githubusercontent.com/633557/33798983-05fcd0a2-dd23-11e7-8c46-484fe668513c.png">

I'll change `debug` messages in the next version so that they will appear in `info`.

**Comment by gynet** [comment] 2017-12-09 19:58
here you go: 

(index):1 2017-12-09T19:55:02.352Z [app] Started in 1738ms ¯\_(ツ)_/¯
(index):1 2017-12-09T19:55:18.341Z [storage-gdrive] OAuth: popup opened
(index):1 2017-12-09T19:55:18.355Z [storage-gdrive] Strange OAuth token Objectaction: "showStatus"commandToFrontend: truecontent: ""duration: undefinedid: "vdgpat8ud7r1mpu2XXXX"origin: "https://beta.keeweb.info"position: 0__proto__: Object
(index):1 2017-12-09T19:55:18.355Z [storage-gdrive] OAuth error no token undefined
a.error @ (index):1

**Comment by antelle** [comment] 2017-12-09 20:06
Interesting. Could you please try one more time? Added something else to check.

**Comment by gynet** [comment] 2017-12-09 20:32
2017-12-09T20:28:57.610Z [app] Started in 996ms ¯\_(ツ)_/¯
(index):1 2017-12-09T20:29:00.261Z [storage-gdrive] OAuth: popup opened
(index):1 2017-12-09T20:29:00.277Z [storage-gdrive] OAuth message received {"action":"showStatus","content":"","position":0,"commandToFrontend":true,"origin":"https://beta.keeweb.info","id":"nb1ljezamvc8109gjrXXXXX"}
(index):1 2017-12-09T20:29:00.393Z [storage-gdrive] OAuth message received {"action":"setFrontFrame","pointerEvents":"none","frameHeight":"100%"}
(index):1 2017-12-09T20:29:21.714Z [storage-gdrive] OAuth message received {"access_token":"XXXXXXXXXkyarYWrQXfo90GhC1kKxgMybQl7qd41a9pMHpvsD0TRhokUebBx1RSta7XXXXXX","token_type":"Bearer","expires_in":"3600"}
(index):1 2017-12-09T20:29:21.739Z [storage-gdrive] OAuth message received {"action":"showStatus","content":"","position":0,"commandToFrontend":true,"origin":"https://beta.keeweb.info","id":"vnezz2t1sdqfpvztjXXXX"}
(index):1 2017-12-09T20:29:21.739Z [storage-gdrive] OAuth message received {"action":"showStatus","content":"","position":0,"commandToFrontend":true,"origin":"https://beta.keeweb.info","id":"tmiki04h4pk1w12rzpXXXX"}
(index):1 2017-12-09T20:29:21.824Z [storage-gdrive] OAuth message received {"action":"setFrontFrame","pointerEvents":"none","frameHeight":"100%"}
(index):1 2017-12-09T20:29:21.825Z [storage-gdrive] OAuth message received {"action":"setFrontFrame","pointerEvents":"none","frameHeight":"100%"}

**Comment by antelle** [comment] 2017-12-09 20:33
Cool, got it, working on the fix :)

**Comment by antelle** [comment] 2017-12-09 20:47
Please try on beta now, should be fixed.
I can't verify it because google drive doesn't send these messages for me.

**Comment by gynet** [comment] 2017-12-09 21:01
Verified this issue got fixed.

**Comment by antelle** [comment] 2017-12-09 21:02
Awesome, thanks for your help! 🎁 
These fixes will be released today or tomorrow.

**Comment by gynet** [comment] 2017-12-09 21:03
np, awesome, thank you!  Find an another minor issue. The db file does not show up under the password field after choosing the file in Google driver, but I can still type the password.

**Comment by antelle** [comment] 2017-12-09 21:05
What does it look like?
I don't quite understand it.

**Comment by gynet** [comment] 2017-12-09 21:10
Never mind, I think it's by design. I was thinking the db file will appear in the yellow area for the first time choosing db. 

![beta keeweb info](https://user-images.githubusercontent.com/2174522/33799511-2d889bc4-dce2-11e7-94ea-22a323f4a838.jpg)

**Comment by antelle** [comment] 2017-12-09 21:10
Yes it's by design. The list below this field contains successfully opened files. So, it will appear there once you open and close it.

**Comment by gynet** [comment] 2017-12-09 21:11
Cool, thank you for the quick fix!

**Closed** 2017-12-09 21:40 UTC
Labels: bug

**Comment by antelle** [comment] 2017-12-09 21:50
The fix is rolled out.
