### ISSUE TITLE
Auto Type Error: To use system-wide shortcut, ...

### ISSUE THREAD

**Issue by benzkji** [keeweb/keeweb#309] opened 2016-08-13 07:23 UTC
Auto Type selects my github entry, but then, this message: `Auto Type Error: To use system-wide shortcut, please focus the app where you want to type your password`

Also, it creates for itselfs a new entry in the file, with username and password in the username field. (Because it does the sequence to itself, probably? Also, Chrome only. Very strange). Might be related to #307 (I have two monitors). Nothing special in the log, though?

LOG:
[DEBUG] 2016-08-13T07:20:04.838Z [auto-type] Auto type event 
[DEBUG] 2016-08-13T07:20:04.838Z [auto-type] Get window title
[INFO ] 2016-08-13T07:20:04.906Z [launcher] spawn osascript: 0, 68ms
firefox
[INFO ] 2016-08-13T07:20:04.975Z [launcher] spawn osascript: 0, 68ms
Sign in to GitHub · GitHub
[DEBUG] 2016-08-13T07:20:04.975Z [auto-type] Window title Sign in to GitHub · GitHub 
[DEBUG] 2016-08-13T07:20:04.975Z [auto-type] Start {USERNAME}{TAB}{PASSWORD}{ENTER}
[DEBUG] 2016-08-13T07:20:04.976Z [auto-type] Parsed [op:USERNAME,op:TAB,op:PASSWORD,op:ENTER]
[DEBUG] 2016-08-13T07:20:04.976Z [auto-type] Resolved [*******,key:tab,[*,*,*,*,*,*,*,*,*,*],key:enter]
[INFO ] 2016-08-13T07:20:05.553Z [launcher] spawn /Applications/__own/KeeWeb.app/Contents/Resources/app/helper/darwin/KeeWebHelper: 0, 577ms
[DEBUG] 2016-08-13T07:20:05.553Z [auto-type] Complete 578ms
[DEBUG] 2016-08-13T07:20:05.558Z [auto-type] Auto type event 

AGENT:
KeeWeb v1.2.4 (9963c60, 2016-08-12)
Environment: electron v1.2.6
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.4 Chrome/51.0.2704.106 Electron/1.2.6 Safari/537.36

VERSION: Your beta build from #259

**Comment by antelle** [comment] 2016-08-13 14:09
Looks like, it's multi-display issue, electron tells us that the app is focused. We have to find a workaround...

**Comment by antelle** [comment] 2016-08-13 17:51
Installed WiDisplay, validated the bug, it doesn't happen in multi-display setup, if it does for you - please add more detailed steps and reopen.
Looks like a duplicate of #307, so when there are many Chrome windows, on different displays, we have problems. But I cannot get the message 'To use system-wide shortcut, please focus the app where you want to type your password'. I don't understand how KeeWeb window gets focus, because we don't focus it if there's only one matching entry.

**Closed by antelle** 2016-08-13 17:51 UTC
Labels: auto-type, bug, need info
