### ISSUE TITLE
Unscrollable credentials page

### ISSUE THREAD

**Issue by Tejes** [keeweb/keeweb#516] opened 2017-02-09 18:24 UTC
When providing WebDAV credentials, a higher mobile keyboard covers the password field. The page cannot be scrolled, so one has to close the keyboard and then tap into the password field (or start with that).

![Schreenshot](https://lh3.googleusercontent.com/5sC1IMA8vw6KcP4nzztRUnB7DB3NOkjHYWfAWTuoRiGTzqHYwooI7qLOW0RYQI3QUREZWggYKPQv3mRka-njGTblZA2deXywc_doIUOKCSzggoEQ6tvONtQejdg9C0xYKvgPWQ=w590-h1048-no)

**Comment by antelle** [comment] 2017-02-09 18:28
There's no password field on the page at this moment, this is by design.
Here's how it looks like:
![web](https://cloud.githubusercontent.com/assets/633557/22797264/eaf62470-eefd-11e6-8f8a-407084677a5d.png)
But the field size is weird, we should fix that cosmetic issue.

**Comment by antelle** [comment] 2017-02-09 18:34
Oh, I got what you mean. You cannot scroll to 'WebDAV password' field, not file password.
I just tested it, and it's ok on iOS, but I confirm, that it's not scrollable on Android, you're right. Will be fixed as well.

**Comment by antelle** [comment] 2020-03-15 16:03
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release.

**Comment by Tejes** [comment] 2020-03-17 14:45
Looks nice in both Firefox and Chrome on Android.
Thank you!

**Closed** 2020-04-03 19:53 UTC
Labels: bug, mobile
