### ISSUE TITLE
Empty window on MacOS High Sierra

### ISSUE THREAD

**Issue by dodalovic** [keeweb/keeweb#785] opened 2017-12-02 23:00 UTC
When starting the app, I get an empty window. 

![image](https://user-images.githubusercontent.com/6358061/33520519-e33c85dc-d7bc-11e7-9a80-69c43d3fa9b8.png)

MacOS High Sierra.

**Comment by antelle** [comment] 2017-12-02 23:02
Hi! Did you have earlier KeeWeb version? Anything interesting in logs?

**Comment by antelle** [comment] 2017-12-02 23:03
You can also try to open it from Terminal, i.e.:
`/Applications/KeeWeb.app/Contents/MacOS/KeeWeb`

**Comment by dodalovic** [comment] 2017-12-02 23:05
Yes, removing from `~/Library/Application Support/KeeWeb` solved the issue. That also made all the installed plugins disappear, which is not the nicest thing.

**Comment by facutopa** [comment] 2017-12-02 23:06
Here something similar on mac.
![Screenshot 2017-12-02 a la(s) 20.05.18.png…]()

**Comment by antelle** [comment] 2017-12-02 23:07
@dodalovic which version did you have before? 1.5.x?
I'm downloading it to reproduce...

**Comment by antelle** [comment] 2017-12-02 23:12
Can't repeat with 1.5. It looks like some setting was causing this.
@facutopa could you please check if there's anything special in your settings file? It's here:
```
~/Library/Application Support/KeeWeb/app-settings.json
```
Does the app start if you remove this file?

**Comment by facutopa** [comment] 2017-12-02 23:26
I just restart my Macbook and now my problem disappear.
But now I have the same problem of @dodalovic and when I open the app, only I see a white screen.

**Comment by antelle** [comment] 2017-12-02 23:27
Okay cool, let's try to debug it.
What happens if you delete `app-settings.json` from `Application Support/KeeWeb`?

**Comment by facutopa** [comment] 2017-12-02 23:30
Nothing, the problem persist.
If you need some files or other capture, tell me.

**Comment by antelle** [comment] 2017-12-02 23:33
And if you delete everything in `~/Library/Application Support/KeeWeb` - does it start?
Again, please don't delete it, just rename the directory, we'll need it to understand what's the reason.

**Comment by facutopa** [comment] 2017-12-02 23:38
Ok I solved the problem with the next steps:
1. Go to ~/Library/Application Support/
2. Change the name of the folder "**KeeWeb**" for "**KeeWeb 2**".
3. Open and use the app normally.

KeeWeb v1.6.0 (abd8f6d, 2017-12-02)
Environment: electron v1.7.9
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.6.0 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36

**Comment by antelle** [comment] 2017-12-02 23:40
@facutopa if you don't mind, I'd be glad for some your time to debug it.
Could you please try to put files and folders from `KeeWeb 2` to `KeeWeb`, one by one and check when exactly it doesn't start - this way we'll understand the problem.

**Comment by facutopa** [comment] 2017-12-02 23:48
I just did what you request, copy each file to the main folder.
The problem come from the file:

> ~/Library/Application Support/KeeWeb/**plugins.json**

**Comment by antelle** [comment] 2017-12-02 23:48
Wow, that's interesting! Could you please paste its contents here?

**Comment by facutopa** [comment] 2017-12-02 23:52
Sure!
`{"autoUpdateAppVersion":"1.5.6","autoUpdateDate":1512227934131,"plugins":[{"manifest":{"version":"1.4.0","manifestVersion":"0.1.0","name":"language-spanish","description":"Spanish language","author":{"name":"KeeWeb","email":"antelle.net@gmail.com","url":"https://keeweb.info"},"licence":"MIT","url":"https://plugins.keeweb.info/translations?lang=es-ES","resources":{"loc":"BZHritFmW5VzWU8RP79+6supvJ1zK0Fjys2wYDrfQmXi5lEfvuSr+sGj1quow4ibzJCmSk/q/xcTxFcqzzQRtqrRZnuXwUedsW43ix2zgXoqlx9QEhpNGI5aqqSKCB5etl92lBHhtpqmkhVQSnDm2+ssTnAscdtJcVY9awlVV47J7l7naxVvr9cHvC8UiPVfcqzW1m6jzWA/fID41b/LpjUHaYYx8tLs7Nmt6yZqr95h7vOPnQWuwrdqL7dBcsKozSeLCrIGBGW/DW7VuPoAmh3A8IKyJeXx+pi/ZHrhvDB5iLKoXF1vTKIAD2O2yYwp4eEKcb0BmCOhZdIGXXHC+A=="},"locale":{"name":"es-ES","title":"Español","flag":"🇪🇸"},"publicKey":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0oZB2Kt7AzRFNqf8FuO3C3kepHPAIQYiDPYdQxHcsiaFCwyKVx6K1cE/3vBhb8/2rj+QIIWNfAAuu1Y+2VK90ZBeq6HciukWzQRO/HWhfdy0c7JwDAslmyGI5olj0ZQkNLhkde1MiMxjDPpRhZtdJaryVO5cFJaJESpv3dV6m0qXsaQCluWYOSNfSjP9C8o2zRVjSi3ZQZnZIV5pnk9K2MtlZIPXrN9iJiM5zZ9DTSnqApI6dC9mX4R3LvGN+GTovm9C8Crl+qb106nGRR3LcweicDnPyMtZLa/E0DBpWYxUVLDp6WeLhxoUBr+6+t3Xp9IDnPoANDQXJXD0f1vQxQIDAQAB"},"url":"https://plugins.keeweb.info/translations/es-ES/","enabled":true,"autoUpdate":true},{"manifest":{"version":"0.1.2","manifestVersion":"0.1.0","name":"keewebhttp","description":"KeeWebHttp allows to use browser extensions with KeeWeb","author":{"name":"KeeWeb","email":"antelle.net@gmail.com","url":"http://keeweb.net"},"licence":"MIT","url":"https://plugins.keeweb.info/plugins/keewebhttp","resources":{"js":"xRiIO2Y08FN8Qf/U1I+Ab3WI8UWNnRwVXmV5/XlxKDFUQIoWT1sMLP6pW7IrcUuFJ0zDwag+BlJuutnBt42+WgfRWCAZ2qRV5cRBCQYJ3q4W3JvkWSAfoTulgrmJ5C4ofiN9D8FL567+2eg7ni1BDA0sVrfLsA7SFNRfJ3vULKpeFjJHB6ypwO60v4xm1A8S+Cm3qckmvOA3Bp9WD1M8Gj1t9ULHKT9DYq6QG6rxwGWODqHsQRifFRojp73X5PM2j4GV1tEWASRGYCNmwmA7fCNHFmppk4W7ofpENF1/dbXrxDxqQ/unbHTixPp0oy+6R2Clnb3jOEYw6pnp0wxWLg=="},"publicKey":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0oZB2Kt7AzRFNqf8FuO3C3kepHPAIQYiDPYdQxHcsiaFCwyKVx6K1cE/3vBhb8/2rj+QIIWNfAAuu1Y+2VK90ZBeq6HciukWzQRO/HWhfdy0c7JwDAslmyGI5olj0ZQkNLhkde1MiMxjDPpRhZtdJaryVO5cFJaJESpv3dV6m0qXsaQCluWYOSNfSjP9C8o2zRVjSi3ZQZnZIV5pnk9K2MtlZIPXrN9iJiM5zZ9DTSnqApI6dC9mX4R3LvGN+GTovm9C8Crl+qb106nGRR3LcweicDnPyMtZLa/E0DBpWYxUVLDp6WeLhxoUBr+6+t3Xp9IDnPoANDQXJXD0f1vQxQIDAQAB","desktop":true},"url":"https://plugins.keeweb.info/plugins/keewebhttp/","enabled":true,"autoUpdate":true},{"manifest":{"version":"0.0.2","manifestVersion":"0.1.0","name":"theme-nord","description":"Nord theme","author":{"name":"KeeWeb","email":"keeweb@keeweb.info","url":"https://keeweb.info"},"resources":{"css":"fXPoQUOlM8+vzB7bOrvSSNLO6bRxdBr0KrYC0SStC0x6PiFf0sXAUQB9SQzmo+UHy1EVpsMLmz5YDtx8s0AQDh/x53WHdLeziNev1iwdTdpIq39dWr2SjmR8a0meDTr43Wr8CnARuTaHfrvMB5JnoUirwJiY/KP4RJYa2yd/Np+8BkoT3leOiURKIib1/Z4epZNAsz/QxJQHHdY6g/8czLzRMUPHR285bZ7jKsRqLUz/ujS2XC3QW3i48GCPkTCkv1+pphCw89ic0eKLdE8NMNuKKImmujVcAqVSBSqS2a+LJlbpqmqs4g3r4sRDWnj81hJlVTH9xQW4a9nF998FwA=="},"licence":"","url":"https://plugins.keeweb.info/plugins/theme-nord","publicKey":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0oZB2Kt7AzRFNqf8FuO3C3kepHPAIQYiDPYdQxHcsiaFCwyKVx6K1cE/3vBhb8/2rj+QIIWNfAAuu1Y+2VK90ZBeq6HciukWzQRO/HWhfdy0c7JwDAslmyGI5olj0ZQkNLhkde1MiMxjDPpRhZtdJaryVO5cFJaJESpv3dV6m0qXsaQCluWYOSNfSjP9C8o2zRVjSi3ZQZnZIV5pnk9K2MtlZIPXrN9iJiM5zZ9DTSnqApI6dC9mX4R3LvGN+GTovm9C8Crl+qb106nGRR3LcweicDnPyMtZLa/E0DBpWYxUVLDp6WeLhxoUBr+6+t3Xp9IDnPoANDQXJXD0f1vQxQIDAQAB","license":"MIT","theme":{"name":"nord","title":"Nord"}},"url":"https://plugins.keeweb.info/plugins/theme-nord/","enabled":true,"autoUpdate":false}]}`


[plugins.json.zip](https://github.com/keeweb/keeweb/files/1524370/plugins.json.zip)

**Comment by antelle** [comment] 2017-12-02 23:57
Confirmed, I can repeat it, found the reason, the fix is coming in several minutes...

**Comment by antelle** [comment] 2017-12-03 00:28
Fixed in 9ee10802409771885e8ba2af82a49934b4cc9cc2, new release is rolled out.
@facutopa thank you very much for your help! 🎁

**Closed by antelle** 2017-12-03 00:28 UTC
Labels: bug, desktop, help wanted, need info
