### ISSUE TITLE
Error opening file. Wide characters are not allowed.

### ISSUE THREAD

**Issue by Rakshasas** [keeweb/keeweb#315] opened 2016-08-15 22:55 UTC
- what were your actions? Attempting to open a Keepass 2 DB (Password and Key file)
- what was wrong? Error message is thrown: "There was an error opening file. Error: Wide characters are not allowed."
- app version: v1.2.4
- your user-agent (from Settings/Help section)
```
KeeWeb v1.2.4 (c30e305, 2016-07-20)
Environment: electron v1.2.6
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.2.4 Chrome/51.0.2704.106 Electron/1.2.6 Safari/537.36
```
- does it happen on Demo or New database? No.
- please, open dev tools in your browser and attach output log from Console tab 
    (if you are using desktop app, devtools can be opened from Settings/General/Advanced)

```
2016-08-15T22:51:53.527Z [updater] Next update check will happen in 85598s
index.html:13 2016-08-15T22:52:00.354Z [storage-cache] Remove 68e629d1-9921-db1d-991e-c1c3ac8e39fe
index.html:13 2016-08-15T22:52:00.356Z [storage-cache] Removed 68e629d1-9921-db1d-991e-c1c3ac8e39fe 0ms
index.html:13 2016-08-15T22:52:02.165Z [storage-cache] Remove 6bef2048-f8ef-222a-6a7d-2a6936c9568e
index.html:13 2016-08-15T22:52:02.166Z [storage-cache] Removed 6bef2048-f8ef-222a-6a7d-2a6936c9568e 1ms
index.html:13 2016-08-15T22:52:08.376Z [dropbox] Call readdir
index.html:13 2016-08-15T22:52:09.829Z [dropbox] Result readdir 1454ms Arguments[4]
index.html:13 2016-08-15T22:52:20.823Z [open:________] File open request
index.html:13 2016-08-15T22:52:20.824Z [open:________] Open file from storage dropbox
index.html:13 2016-08-15T22:52:20.824Z [open:________] Load from storage
index.html:13 2016-08-15T22:52:20.824Z [storage-dropbox] Load /________.kdbx
index.html:13 2016-08-15T22:52:20.824Z [dropbox] Call readFile
index.html:13 2016-08-15T22:52:21.176Z [dropbox] Result readFile 352ms Arguments[4]
index.html:13 2016-08-15T22:52:21.176Z [storage-dropbox] Loaded /Documents/________.kdbx 8afa8024d8e74 352ms
index.html:13 2016-08-15T22:52:21.176Z [open:________] Open file from content loaded from storage
index.html:13 2016-08-15T22:52:21.185Z [file] Error opening file Error: Wide characters are not allowed.(…) undefined Wide characters are not allowed. Error: Wide characters are not allowed.(…)f.error @ index.html:13
index.html:13 2016-08-15T22:52:21.185Z [open-view] Error opening file Error: Wide characters are not allowed.(…)f.error @ index.html:13
```

**Comment by antelle** [comment] 2016-08-16 04:56
Hello!
Please click (...) button and paste stack trace inside `index.html:13 2016-08-15T22:52:21.185Z [open-view] Error opening file Error: Wide characters are not allowed.(…)f.error @ index.html:13`

**Comment by Rakshasas** [comment] 2016-08-16 13:40
I did not realise that could be expanded!

An extra bit of information before I give the stack trace. It seems this is an issue with the key file. I was able to reproduce this error message without even typing my password. I only attached the key.
```
2016-08-16T13:31:35.821Z [updater] Next update check will happen in 1s
index.html:13 2016-08-16T13:31:36.321Z [updater] Checking for update...
index.html:13 2016-08-16T13:31:36.321Z [transport] GET https://app.keeweb.info/manifest.appcache
index.html:13 2016-08-16T13:31:37.338Z [transport] Request to https://app.keeweb.info/manifest.appcache without proxy
index.html:13 2016-08-16T13:31:37.695Z [transport] Response from https://app.keeweb.info/manifest.appcache: 200
index.html:13 2016-08-16T13:31:37.697Z [updater] Update check: # 2016-07-20:v1.2.4
index.html:13 2016-08-16T13:31:37.701Z [updater] Next update check will happen in 86400s
index.html:13 2016-08-16T13:31:37.702Z [updater] You are using the latest version
index.html:13 2016-08-16T13:32:30.202Z [dropbox] Call readdir
index.html:13 2016-08-16T13:32:30.617Z [dropbox] Result readdir 415ms Arguments[4]
index.html:13 2016-08-16T13:32:49.929Z [dropbox] Call readdir
index.html:13 2016-08-16T13:32:50.354Z [dropbox] Result readdir 426ms Arguments[4]
index.html:13 2016-08-16T13:33:00.728Z [open:________] File open request
index.html:13 2016-08-16T13:33:00.728Z [open:________] Open file from storage dropbox
index.html:13 2016-08-16T13:33:00.728Z [open:________] Load from storage
index.html:13 2016-08-16T13:33:00.728Z [storage-dropbox] Load /________.kdbx
index.html:13 2016-08-16T13:33:00.729Z [dropbox] Call readFile
index.html:13 2016-08-16T13:33:01.261Z [dropbox] Result readFile 533ms Arguments[4]
index.html:13 2016-08-16T13:33:01.261Z [storage-dropbox] Loaded /Documents/________kdbx 8afa8024d8e74 533ms
index.html:13 2016-08-16T13:33:01.262Z [open:________ Open file from content loaded from storage
index.html:13 2016-08-16T13:33:01.272Z [file] Error opening file Error: Wide characters are not allowed.
    at f (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:5:6094)
    at N.K [as process] (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:5:12226)
    at h.setKeyFile (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:6:24461)
    at new h (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:6:23805)
    at n.open (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:15:30196)
    at n.openFileWithData (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:17:23222)
    at file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:17:22247
    at file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:18:8378
    at file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:14:25874
    at t.callback (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:10:9255) undefined Wide characters are not allowed. Error: Wide characters are not allowed.(…)f.error @ index.html:13
index.html:13 2016-08-16T13:33:01.272Z [open-view] Error opening file Error: Wide characters are not allowed.
    at f (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:5:6094)
    at N.K [as process] (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:5:12226)
    at h.setKeyFile (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:6:24461)
    at new h (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:6:23805)
    at n.open (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:15:30196)
    at n.openFileWithData (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:17:23222)
    at file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:17:22247
    at file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:18:8378
    at file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:14:25874
    at t.callback (file:///C:/Users/________/AppData/Local/KeeWeb/app-1.2.4/resources/app/index.html:10:9255)
```

**Comment by Rakshasas** [comment] 2016-08-16 13:41
I did not mean to close this. Sorry

**Comment by antelle** [comment] 2016-08-16 17:23
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by Rakshasas** [comment] 2016-08-22 18:01
I apologise. I only checked today. I figured I'd try out the beta and give you feedback.

Unfortunately, I am still unable to open my database. It shakes the password box as if I typed my password wrong. I can confirm that I am absolutely entering my password correctly since I am using it in the original KeePass2 desktop application, as well as using the right key file for this reason. As a sanity check, I made sure to attempt this more than once and reattaching the key file should I accidently have chosen the wrong one originally.

There isn't much to give from the logs this time around:

```
[ERROR] 2016-08-22T17:56:30.750Z [file] Error opening file InvalidKey Error InvalidKey KdbxError: Error InvalidKey
[ERROR] 2016-08-22T17:56:30.751Z [open-view] Error opening file KdbxError: Error InvalidKey
```

**Comment by antelle** [comment] 2016-08-22 18:33
So, beta doesn't work for you?
What is your keyfile length, in bytes? 
If you create a new db with the same keyfile - does it work in keeweb?

**Comment by Rakshasas** [comment] 2016-08-22 20:52
The file size is 190 bytes.

I created a brand new database using the password "test" and my key file. It does not open in the beta version. It does seem like there is something special going on with my key file.

As a simple test, I generated a new key file and used that instead and it does open. It seems there is something special about my key file. It is rather old.

**Comment by antelle** [comment] 2016-08-22 20:58
Hm. I'll test it tomorrow with different keyfiles. What's inside your keyfile? There are several types of keyfiles:
- 32-bit with raw hash (not our case definitely)
- 64-bit hex (neither)
- xml with hash
- binary

**Comment by Rakshasas** [comment] 2016-08-23 15:16
I used keepass2 to generate the key file originally. I opened it up and it looks like it is an XML with hash value.

The new key file I generated to test with is also an XML with hash value. So to clarify the older file and the new file were both generated with keepass2 and are both XML files with a hash.

I'm tempted to give you this "bad" key file so you can look into and solve the problem because it should help some other people wanting to use keeweb, and I'll just use a new key file for my database.

**Comment by Rakshasas** [comment] 2016-08-23 15:21
Actually, this might be useful. After opening both files to visual compare them I noticed that both were basically identical. It made me wonder why would be a problem and the other would be fine. I opened them both in "Visual Studio Code" to see if I could find anything and then I saw a slight difference in the encoding.

The older key file causing the problem is "UTF-8 with BOM" and the newer troublefree key file is simply "UTF-8".

**Comment by antelle** [comment] 2016-08-23 15:37
Thanks for making it clear!
We tried to read the file without bom, I didn't know old versions pf KeePass could generate files with bom, and as we failed, the file was interpreted as binary. I'll add a fix.

**Comment by Rakshasas** [comment] 2016-08-23 15:44
Yeah. This little exercise has made me realise how old my key file is, and that is something I am going to address. Still, I'll wait so I can test this out for you.

I suppose the reality is that most people probably would not have experienced this problem if they regularly update their key files.

**Comment by antelle** [comment] 2016-08-23 16:56
Fixed, added a unit test on this, deployed to [beta](https://beta.keeweb.info/). The problem is there's a lot of strange code in KeePass: first it checks the file for 32-byte length and reads this as raw hash, then it tries to read 64-byte hash as hexstring, then tries loading as xml and if it fails, the file is treated as binary. To me, it's absolutely pointless to load raw hash or xml from file.
And you guess what? Here are two different keyfiles attached, both of them allow to open the same file.
[64high.zip](https://github.com/keeweb/keeweb/files/433061/64high.zip)
This bug is still here, after several years of KeePass existence, and bad thing here is we have to repeat this logic as well.

**Comment by antelle** [comment] 2016-08-23 19:22
Posted an issue about 64-byte files with equal hashes to KeePass bugtracker, this will be fixed in next KeePass version, so we'll change it accordingly once it's out.

**Comment by Rakshasas** [comment] 2016-08-25 03:34
Confirmed! I was able to open it. Thank you very much. I'm really glad I could point you in the direction of finding the issue with the 64-byte files. Win win I'd say!

**Closed** 2016-09-01 18:31 UTC
Labels: bug, kdbxweb
