### ISSUE TITLE
Sometimes Keeweb prevents Alfred auto-expansion feature from working

### ISSUE THREAD

**Issue by peczony** [keeweb/keeweb#423] opened 2016-10-26 10:17 UTC
Suddenly the auto-expansion feature of my [Alfred](//alfredapp.com) stopped working. I researched the forums and found this:

> It's likely that you're experiencing the same issue as other users where secure input isn't released correctly by a plugin or app that requires it, and restarting your Mac simply reset the secure input. Next time, instead of rebooting, try quitting browsers to see whether it's a plugin like LastPass at the source of the issue. — from [here](http://www.alfredforum.com/topic/8871-alfred-3-snippets-dont-auto-expand-fix-awaiting-chromium-bug-fix/?page=2)

I started exiting apps one by one and checking whether such and such app was the culprit. Finally I was able to figure out that restarting KeeWeb fixes the problem. Sorry I cannot provide more details as I am unfamiliar with how OS X works in this regard.

But maybe you can check and find the bug without additional information, using just this description. By the way I haven’t even used KeeWeb this time, it just loaded automatically on boot.

**Comment by dploeger** [comment] 2019-01-08 08:10
I can reproduce that.

The problem looks like the this:

* When Keeweb is in lock-mode, it enables secure input (because of the passphrase input I guess)
* When you focus the Keeweb window and hide it again, secure input is disabled
* When you switch screens (without Keeweb getting any focus), secure input is enabled again
* When you lock the screen, return and don't have Keeweb in the foreground, secure input is enabled

It somehow got worse and I really only noticed that after updating to 1.7.1.

@antelle Do you actively (and knowingly) enable secure input somewhere or is it probably some Electron/macOS mechanics?

**Comment by dploeger** [comment] 2019-01-11 12:16
@antelle It is this line: https://github.com/keeweb/keeweb/blob/f18d053cbf396a2c5f6045a688f62e9366af262b/app/scripts/views/open-view.js#L267

and most probably this line, too: https://github.com/keeweb/keeweb/blob/f18d053cbf396a2c5f6045a688f62e9366af262b/app/scripts/views/open-view.js#L273

Keeweb focuses the input field, even if the app or the browser isn't focused. This enables macos Secure Input mode until you select Keeweb and hide it again.

Is it be possible to check, if Keeweb (App/Browser) is currently focused before focussing the input field?

This is a really annoying bug for macOS users - especially with 1.7.1

**Comment by antelle** [comment] 2019-01-11 17:53
@dploeger yeah indeed it's possible: https://electronjs.org/docs/api/browser-window#winisfocused

**Comment by dploeger** [comment] 2019-01-16 15:12
@antelle Can I haz version update? 😉

**Comment by antelle** [comment] 2019-01-16 18:18
@dploeger it's already merged into release-1.7, will be there in the next hotfix.

**Comment by dploeger** [comment] 2019-01-17 07:31
@antelle Great, when is it due? Can I help?

**Comment by antelle** [comment] 2019-01-17 08:02
Probably today. There are no other open issues, just this one

**Comment by dploeger** [comment] 2019-01-17 08:05
Great news. Thanks.

**Closed** 2019-01-17 20:06 UTC
Labels: bug, desktop, help wanted, mac

**Comment by antelle** [comment] 2019-01-17 20:08
It's live now
