### ISSUE TITLE
Force GoogleDrive Sign-In over different browser?

### ISSUE THREAD

**Issue by dominikheinz** [keeweb/keeweb#1411] opened 2020-02-23 01:12 UTC
I am not entirely sure if this should be considered a bug, or rather a feature request.
Please edit the issue, if needed.

**The Problem**
Using Google Drive as sync point for the KeeWeb-file is pretty convenient.
When first opening the password database (aka if no local copy is available), you usually click the Google Drive Logo, sign in, select the database and then you can unlock the KeeWeb file and use it normally.
Now, the sign-in popup seem to opens in a inbuilt-browser popup.
Google prevents sign ins from "unsecure browsers". 
In other words: When logging in to your google account to setup the sync process, after a successful login, the popup shows a google prompt: 

_"This browser or app is probably not secure. Please use a different browser."_

This cancels the sync setup process.

**Possible solution**
Add a setting in KeeWeb to force opening the Google Drive Sign-In Site in a different browser, rather than the popup.

**Environment**
I am using Manjaro x64 with i3 as desktop environment.

**Logs**
Not really any useful logs available, as this is not a problem that is directly related to KeeWeb itself.
The dev console just shows: "OAuth popup opened"

**Comment by antelle** [comment] 2020-02-23 07:18
Hi! It's usually happening in the app (#1359), but not in a browser. We won't be possible to open another browser of course, but we can open it in the same tab instead of a new window. However I don't think it will help because they check the user agent. Most likely, what can help, is changing the user-agent in your browser and then switching it back after signing in, can you please try it?

**Comment by jonatjano** [comment] 2020-02-25 10:45
Hi !
I just read from this post : https://support.google.com/accounts/thread/22873505?hl=en
that you can use : `win.loadURL(`/url/path`, { userAgent: 'Chrome' });` to bypass this "protection" (https://support.google.com/accounts/thread/22873505?hl=en&msgid=24503570)

another comment say you only need to remove chrome version from the user-agent, this may be harder but if you need the user-agent somewhere else this seems to be the way to go (https://support.google.com/accounts/thread/22873505?hl=en&msgid=24817924)

**Comment by antelle** [comment] 2020-02-25 11:24
@jonatjano this issue is only about browser, it’s perfectly clear what to do in the desktop app, that’s described in the linked issue. Let’s not discuss desktop here.

**Comment by antelle** [comment] 2020-02-25 19:10
I just realized that the issue is about the desktop app, not a browser. Closing it, it's indeed a duplicate.

**Closed by antelle** 2020-02-25 19:10 UTC
Labels: need info
