### ISSUE TITLE
Duplicate tray icons when closing the app on Ubuntu

### ISSUE THREAD

**Issue by dbogdanov** [keeweb/keeweb#1708] opened 2021-02-10 00:26 UTC
**Describe the bug**
I have minimize to system tray turned on. Closing the app creates a new icon in the system tray every time resulting in duplicates.

**To Reproduce**
1. Run the application, and close it. A new icon will be created in the system tray.
2. Open the app again, clicking on the icon, "Open KeeWeb".
3. Close again. An additional duplicate icon appears in the system tray.
4. Repeat steps 2 and 3 to get more duplicates.

**Expected behavior**
No duplicate icons should be generated. There should always be only one icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/409668/107446315-76c99980-6b3e-11eb-8067-33b57ee7a6c6.png)

**Environment**
Ubuntu 20.10, Gnome 3.38.1

KeeWeb v1.15.7 (7140a2d, 2020-09-12)
Environment: electron v9.0.4
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.15.7 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by antelle** [comment] 2021-02-10 07:01
Duplicate of https://github.com/keeweb/keeweb/issues/1181

**Closed by antelle** 2021-02-10 07:01 UTC
Labels: bug
