### ISSUE TITLE
"save to" a new file fail

### ISSUE THREAD

**Issue by huashaoxu** [keeweb/keeweb#1334] opened 2019-11-01 07:16 UTC
**Describe the bug**
it can't create a new file to save my computer when i click  the "save to" button.

**To Reproduce**
1. Go to 'new'
2. Click on 'save to '
3. not found file in the local storage

**Expected behavior**
i want to new a key file in my computer

**Comment by antelle** [comment] 2019-11-01 07:27
Hi! Please describe step 3, now it's unclear what is meant by this.

**Comment by huashaoxu** [comment] 2019-11-01 07:30
Click on 'save to 'and 'file', but  nothing happend, i don't found the file in my computer.

**Comment by antelle** [comment] 2019-11-01 07:31
1. Are you using a desktop app or web version?
2. What happens when you click "Save", does it show the file selection dialog?

**Comment by huashaoxu** [comment] 2019-11-01 07:33
![image](https://user-images.githubusercontent.com/35364039/68009418-e191f100-fcbc-11e9-866d-75ff29a86da4.png)

**Comment by huashaoxu** [comment] 2019-11-01 07:34
![image](https://user-images.githubusercontent.com/35364039/68009503-11d98f80-fcbd-11e9-8e6c-ccefb52b10e6.png)

**Comment by antelle** [comment] 2019-11-04 20:48
I don't see any error here, looks like it's working well.

**Comment by ColinMaudry** [comment] 2019-11-06 14:07
I think I have the same issue. It's not about app local storage, it's about saving the database as a new kdbx file.

**Describe the bug**

Using **Save To > File** doesn't create a file.

**To Reproduce**

1. In the desktop app, create a new database
2. Go to **Settings/Database name**
3. Click on **Save To** 
4 . Click on **File**
4. Click on **Open**

**Expected behavior**

A new .kdbx file should be created.

**Screenshots**

None.

**Environment**

Desktop app v1.12.1 installed on Linux Mint 19.

**Kdbx File**

It happens with a new database.

**Logs**

Nothing happens in the logs when I reproduce this bug.

FYI I'm currently working on an accessible and concise [password management guide in French](https://colinmaudry.github.io/password-management/), and KeeWeb is the starring software. I found this bug when debugging my tutorial.

**Comment by antelle** [comment] 2019-11-06 18:35
@ColinMaudry thanks for the detailed description! It's broken indeed, will be fixed soon

**Closed** 2019-11-06 19:12 UTC
Labels: bug, storage

**Comment by antelle** [comment] 2019-11-06 19:13
The fix is released, if you update, it should work.

**Comment by ColinMaudry** [comment] 2019-11-07 15:20
Wow great reactivity, thanks! :+1:

**Comment by byque** [comment] 2020-01-09 16:23
> The fix is released, if you update, it should work.

Confirmed that this fixes the problem in the linux .deb desktop client.
