### ISSUE TITLE
Blank page when saving, also no choice for local file saving.

### ISSUE THREAD

**Issue by chaoticinput** [keeweb/keeweb#1817] opened 2021-05-13 13:00 UTC
**Describe the bug**

I couldn't sync my file with google drive because it has been deleted on google drive from unknow reasons.
But I had this file somewhere on my computer because I open it every day from keeweb with the "load from google drive symbol." This is a strange behavior for a file that was no longer on google drive since days or weeks.
So when I understood there was no sync anymore, I tried the "save to google drive option", in the hope that keeweb will save and sync a new file to google drive. Google drive open and ask my ID. Once done, nothing happen. no new file in google drive. 
So, starting to worry, I choose to save the file localy, with the button "save to file" from keeweb. But no option displayed to save locally in simple .kdbx file.
And the "save" button (I don't really know what is its behavior) just do nothing. or maybe its save a file somewhere but no path is shown.
So I choose to make a backup. (not clear what is the diff with a normal file and a backup file).
Then I restart all clean. I delete all keeweb related thing on my computer exept the backup file, that I open with a fresh istall.
Since I don't quite understand the difference with normal .kdbx and .bak, I choose to re save the bak file to convert it to normal kdbx file.
The "save to" button still not display anything usefull to save locally.
When I choose save to "google drive", the page goes blank. nothing happen and I must close the app to retry something.
So I end up now with a bak file and I can not sync.
Im not an advanced user at all, and I may not quite understand most things, but now it feels so broken.

**To Reproduce**

I don't know, it feels random

**Expected behavior**

expected : upload a file to google drive when clicking on "save to google drive"
also expected : save a file to kdbx format when clicking on "save to" with displayed "file" button.
get : blank page for drive
get : no local option for local file

**Screenshots**

no save to file local
![keeweb no local](https://user-images.githubusercontent.com/84133038/118128878-c5b3f300-b3fb-11eb-955b-2f1b5211450c.PNG)
crash save to google drive
![keeweb crash](https://user-images.githubusercontent.com/84133038/118127687-4ffb5780-b3fa-11eb-84f6-ea549a63f6c5.PNG)

**Environment**
last windows 10 with keeweb app 1.18.4

**Kdbx File**
Does it happen on Demo or New database?  
If you have a test db without your personal data, please attach it.

**Logs**
Please open dev tools in your browser and attach output log from Console tab. If you are using a desktop app, devtools can be opened from Settings/General/Advanced.

**Comment by dpvpro** [comment] 2021-05-13 13:06
Same fo me

**Comment by adamsher** [comment] 2021-05-13 17:36
Having the same issue saving to OneDrive from KDE on Ubuntu 20.04

**Comment by antelle** [comment] 2021-05-13 18:10
For those who can reproduce it, could you please share minimal steps? I tried opening a new file and saving it to Google Drive, but it works.

Or alternatively, what do you see in dev tools?

**Comment by adamsher** [comment] 2021-05-13 18:18
Open KeeWeb. Enter master password. Create or modify any entry. Save. Then screen goes black and data is not saved.
![Screenshot_20210513_141733](https://user-images.githubusercontent.com/1139121/118168680-1b859c80-b3f6-11eb-85bd-77c88b384540.png)

**Comment by adamsher** [comment] 2021-05-13 18:20
Console
![Screenshot_20210513_141948](https://user-images.githubusercontent.com/1139121/118168928-61426500-b3f6-11eb-899a-ab3d174c2595.png)

**Comment by antelle** [comment] 2021-05-13 18:22
Does it happen only in Google Drive or without it as well?

**Comment by adamsher** [comment] 2021-05-13 18:26
For me, only when saving to OneDrive. Downloading the same kdbx file and opening it from local storage works fine.

**Comment by antelle** [comment] 2021-05-13 18:27
Interesting. I can't reproduce it yet, any help would be very welcome. 
Looks like a crash, it's possible that it happens only on Linux, however the original report is also on Windows.

**Comment by adamsher** [comment] 2021-05-13 19:01
Git cloned and ran from source and everything worked. Afterwards, everything started working fine from the binary as well. Not sure if running it from source fixed something in the kdbx file or if it was an issue with OneDrive that cleared up. When I ran from source it also required me to re-authorize the KeeWeb connection to OneDrive. Could be it's necessary to remove the authorization then re-approve.

**Comment by antelle** [comment] 2021-05-13 19:04
Let's see if re-authorization happens for anyone else.  
It's possible that it doesn't crash always.

I don't think it's an issue with kdbx or OneDrive, most likely it's a crash in one of native modules or (less likely but possible, it happened in KeeWeb before) in Electron. It would be good to understand where this crash happens.

**Comment by cryomi** [comment] 2021-05-14 10:06
The same bug at MacOs
```
Darwin cry0m1.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```

<img width="717" alt="image" src="https://user-images.githubusercontent.com/7384006/118255680-d83a3500-b4ac-11eb-85ae-2b84d377b086.png">

**Comment by chaoticinput** [comment] 2021-05-14 13:28
Is the missing option "save to local file" a real bug or it's me having a misundertanding of how it works ? 
What is the difference with .kdbx and .bak ? Because if I rename an extension of .bak to .kdbx it just behave like a normal .kdbx file.

**Comment by antelle** [comment] 2021-05-14 16:12
@cryomi Oops. That doesn't sound good, we don't have native modules in the renderer process, so that's something that causes a crash in Electron / Chromium.  It's not going to be an easy fix 😢  What is crucial here, is the reproduction, so any details (how you're using KeeWeb, which features, and so on) are very welcome.

@chaoticinput you already opened your file from disk, so there's no other save to file option. You can just copy the file wherever you want and open it in KeeWeb. `.bak` is exactly the same as kdbx, it's just a backup of your file that KeeWeb makes from time to time. You can use it as you use a kdbx file. It's strongly recommended to copy a backup file before using it, otherwise there's a risk that your backup will be corrupted. So, if you need to use a `.bak` - copy it somewhere else, rename as `.kdbx`, and that's it.

**Comment by antelle** [comment] 2021-05-14 16:13
Another thing that would help: does it reproduce on the demo file? What if you make a new file in KeeWeb, does the crash happen on a new file?

**Comment by antelle** [comment] 2021-05-14 16:21
It's also strange that the issue is reported only on v1.18.4, does anyone experience this on earlier versions?

**Comment by cryomi** [comment] 2021-05-14 16:25
@antelle I do not know how to describe simply, I am using it as regular password storage, no exotic at all. I have groups/tags/folders, saving .kdbx to iCloud. While saving it crashes.

Just tried 1.18.x and 
created new storage - no issues
added pass to kdbx  - no issues
added key  to kdbx  - no issues

**Comment by antelle** [comment] 2021-05-14 16:27
@cryomi  by 1.18.x you mean something earlier than 1.18.4, right? Same sequence of actions doesn't crash the app?

**Comment by cryomi** [comment] 2021-05-14 16:29
Updated, yes 1.18.4

**Comment by antelle** [comment] 2021-05-14 16:29
How often does it reproduce? For example, if you save it 5 times - it will crash 5 times?

**Comment by cryomi** [comment] 2021-05-14 16:32
I have tried totally 7 times, 100% reproducible.
1.18.4 with my 2 years old password db crashes on save.
1.18.4  with new FS storage - works fine
1.17.6 still  works fine with old.

**Comment by antelle** [comment] 2021-05-14 16:32
What about 1.18.3?

**Comment by antelle** [comment] 2021-05-14 16:34
About the storage: where do you save the file? Because we don't have an iCloud option. I first thought it was iCloud Drive, but since it's also FS, maybe that's not what you meant.

**Comment by cryomi** [comment] 2021-05-14 16:34
Just tested 1.18.3 - same issue.

**Comment by cryomi** [comment] 2021-05-14 16:35
It is FS, where iCloud linked.
```~/Library/Mobile\ Documents/com\~apple\~CloudDocs/```

**Comment by antelle** [comment] 2021-05-14 16:35
Ok, thank you, that's probably something that appeared in v1.18 then

**Comment by antelle** [comment] 2021-05-14 16:37
Just tried opening a file from iCloud Drive - works for me. Not good...

**Comment by cryomi** [comment] 2021-05-14 16:40
Tested demo in 1.18.4 works fine.

**Comment by antelle** [comment] 2021-05-14 16:42
What is the encryption config of any file where it crashes?
<img width="499" alt="enc" src="https://user-images.githubusercontent.com/633557/118302152-2ae31380-b4e4-11eb-8272-a08004cd00f3.png">

**Comment by cryomi** [comment] 2021-05-14 16:56
<img width="555" alt="image" src="https://user-images.githubusercontent.com/7384006/118303762-1d2e8d80-b4e6-11eb-9ea8-cabb4c123f9b.png">

**Comment by cryomi** [comment] 2021-05-14 17:00
Changed to default encryption (like at your screenshot) - now issue has gone :)

**Comment by antelle** [comment] 2021-05-14 17:01
Wow, that's interesting! So, it crashes when it's using WebCrypto, but not Argon2.

**Comment by antelle** [comment] 2021-05-14 17:05
I still can't reproduce it on KDBX3 files. I wonder if this applies to everyone else (that it crashes on KDBX3, but not KDBX4), it can be just a coincidence.

**Comment by antelle** [comment] 2021-05-14 17:14
I managed to crash it, cool, now I can dig into it. With these steps the probability of crash is close to 100%.
1. Create a new file
2. Add an entry there
3. Set the master password and save it
4. Open the file and add an attachment of considerable size, 2..3 MB
5. Save the file
6. Open the file
7. Open file settings and set the format to KDBX3
8. Save the file
9. 💥

**Comment by antelle** [comment] 2021-05-14 18:15
Found the exact place where it fails. No further input needed, thanks to everyone for the help in reproduction! It will be fixed soon.

For those who're curious: it's [here](https://github.com/keeweb/kdbxweb/blob/master/lib/utils/byte-utils.ts#L48), `Buffer::toString(aLotOfData, 'base64')` crashes the renderer process. 
Applied to KeeWeb, it happens when:
- you have a file in KDBX3 format
- there's a relatively large attachment inside

**Comment by adamsher** [comment] 2021-05-14 18:20
Awesome, thanks so much @antelle!

**Closed** 2021-05-14 19:02 UTC
Labels: bug, desktop

**Comment by antelle** [comment] 2021-05-14 19:04
A new release is [building](https://github.com/keeweb/keeweb/actions/runs/843141100), it should be available in ≈half an hour.

**Comment by antelle** [comment] 2021-05-14 19:06
Very similar issue in Electron: https://github.com/electron/electron/issues/28392

**Comment by antelle** [comment] 2021-05-14 19:41
The release is published, for me it fixes the issue.
