### ISSUE TITLE
Virustotal reports JS.Trojan.Kryptik.qi for KeeWeb-1.16.3.html.zip and all versions since 1.16.0

### ISSUE THREAD

**Issue by uli-heller** [keeweb/keeweb#1656] opened 2020-12-16 07:25 UTC
I uploaded the file KeeWeb-1.16.3.html.zip to [virustotal](https://virustotal.com) and got this report:

![image](https://user-images.githubusercontent.com/1677414/102317417-c5f8b100-3f77-11eb-98ef-792d6edea970.png)

Is this an issue? For 1.16.2, I get the same detection. 1.15.2 shows no detection:

![image](https://user-images.githubusercontent.com/1677414/102317680-44555300-3f78-11eb-8a9a-04bc61762a0c.png)

**Comment by uli-heller** [comment] 2020-12-16 07:36
|Version | Status |
|-----------|----------|
|1.16.3| KO  |
|1.16.2| KO  |
|1.16.0| ? |
|1.15.7| ok   |
|1.15.2| ok   |

**Comment by antelle** [comment] 2020-12-16 16:14
Interesting, I see that only `Baidu` gives this false positive, I'll try to understand what it doesn't like.

**Comment by antelle** [comment] 2020-12-16 17:42
So, this root cause is this piece of code:
```
"".replace(/[\n\s]+/g, "")
```
If you save it to a file ([or just download this](https://share.antelle.net/baidu-wtf.js)) and upload it to VirusTotal, you will get [the error you mentioned](https://www.virustotal.com/gui/file-analysis/MzdiMGRlMmYxYTFhNzhhNWJkNGU5YzU4ODBlMGU3NTM6MTYwODE0MDQ4Mg==/detection).

Stupid? Stupid.

I'll add a fix, thanks for flagging this!

**Comment by antelle** [comment] 2020-12-16 19:16
I've also added VirusTotal checks to CI, so that it doesn't happen in future.

**Comment by uli-heller** [comment] 2020-12-17 07:53
Excellent! Shall I close the issue?

**Comment by antelle** [comment] 2020-12-17 08:03
it will be closed automatically when it’s merged

**Closed** 2020-12-17 18:30 UTC
Labels: bug, distribution

**Comment by antelle** [comment] 2020-12-17 20:08
https://www.virustotal.com/gui/file/d1579bf5c53974dfe07f806dca2bc287ae3be62c83c48850fc6366f2c2b54588/detection
✅  clear

**Comment by antelle** [comment] 2020-12-30 11:31
Now another shitty anti-virus came up complaining about all variants of `String.fromCharCode(x.charCodeAt(k) ^ y)`. If they continue like this, I'll just ignore them, this doesn't make any sense.
