### ISSUE TITLE
Option to disable offline storage

### ISSUE THREAD

**Issue by redge76** [keeweb/keeweb#404] opened 2016-10-11 19:09 UTC
Is there a way to easily disable offline storage ?
I think I could use private/incognito session, but it a bit more convenient to have a "disable_offline" option in the configuration.

**Comment by antelle** [comment] 2016-10-11 19:46
There's no way to do it now. The best way is to remove the file from KeeWeb after close.
That would be somewhat hard to add, now we cannot work without storage.

**Comment by redge76** [comment] 2016-10-11 19:59
I understand you can't completely disable storage, but is it possible to delete the local password DB when you close the browser window ? (like a session cookie)

**Comment by antelle** [comment] 2016-10-11 20:42
> you can't completely disable storage

We can, because we always store everything in memory. It would be a bit tough.
It's stored in IndexedDB.

**Comment by aramboi** [comment] 2016-11-08 14:52
Would something like the following work (?):
``` javascript
document.getElementsByTagName('body').onbeforeunload = function(){
  window.indexedDB.deleteDatabase('dbName');
};
```
API described here https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/deleteDatabase

The side-effect of this is that you get a message before closing the tab/window.

**Comment by antelle** [comment] 2016-11-08 14:53
The issue is not technical (sure it's easy to clean storage), but UX: when we should delete files.

**Comment by aramboi** [comment] 2016-11-08 16:24
@antelle I am aware that my example would not work properly because it's an async call. Not really familiar with what happens during the `onbeforeunload` event, hence the (?) mark in my comment above.

Looking a bit more into `onbeforeunload`, seems there is no way to customize the message or the UX when it shows up. Also, from my (light) testing, it does not ream reliable either, sometimes it does not get triggered in FF for some reason.

I see now why this is more of an UX issue than a technical one. :)

**Comment by antelle** [comment] 2016-11-08 19:25
> what happens during the onbeforeunload event

Browser invokes this event, if it returns a message, an alert is shown. Otherwise the tab is closed, and no other scripts will be executed.
This is an UX issue, because instead of using onbeforeunload event logic (imagine that the browser tab has crashed: this event won't be triggered), we should better allow to work with databases without cache/indexeddb at all. And add 'offline' checkbox on 'open' view. But it's a bit hard to implement, because there're many cases to handle. But it can be implemented at some time.

**Comment by antelle** [comment] 2016-11-08 19:25
(closed by mistake)

**Comment by aramboi** [comment] 2016-11-08 22:03
Thanks for taking the time to explain this issue in more detail. I misunderstood the way the IndexedDB is used here and also missed some of the implications this change would have.

**Comment by lil5** [comment] 2019-07-26 06:38
mozilla is finally working on getting this fixed
https://bugzilla.mozilla.org/show_bug.cgi?id=1562669

**Comment by antelle** [comment] 2019-09-09 06:30
The bot was misconfigured, sorry for a wrong notification.

**Comment by gynet** [comment] 2020-04-30 21:25
I think it's also related to security. If keeweb can disable offline storage entirely, and assume the user use google + 2FA, it would be helpful for security purpose

**Comment by thefiredragon** [comment] 2020-05-01 05:16
When someone can access the kdbx . the user can make Screenshots or download the kdbx... it’s my mind

**Comment by redge76** [comment] 2020-05-01 13:12
the idea of eliminating offline storage is to make it harder for a "bad guy"  to get a copy of the database. For sure, it's not perfect. It's just another layer of security.
It many case it won't help. But it may help. 
If you don't need offline storage, there is no need to leave a copy of your database everywhere with possibly a master password that will be later compromised.

**Comment by gynet** [comment] 2020-06-13 21:40
@antelle I think this also related to the Yubikey CR feature added, as the CR is statically paired to one database version, it would be better to have as no file copies of the database on the local disk.

**Comment by antelle** [comment] 2020-06-14 07:46
@gynet now when we have settings encryption in desktop, this threat (getting access to the local filesystem and master key at the same time) can be eliminated simply by encrypting files stored internally. We don't have to implement full support for working without the offline storage for that.

**Closed** 2021-03-07 13:24 UTC
Labels: enhancement, storage
