### ISSUE TITLE
Add this project to Wikipedia article

### ISSUE THREAD

**Issue by bittner** [keeweb/keeweb#1330] opened 2019-10-31 08:39 UTC
Would it make sense to add this project to the [list of password managers on Wikipedia](https://en.wikipedia.org/wiki/List_of_password_managers)?

**Comment by antelle** [comment] 2019-10-31 09:00
Makes sense, I see that other popular KeePass forks are also there.

**Comment by antelle** [comment] 2019-11-03 12:02
The content should be something like:
```
|-
| [[KeeWeb]]
| {{free|[[MIT License|MIT]]}}
| [[Microsoft Windows|Windows]], [[Linux]], [[macOS]], Web version
| {{some|}} through auto-typing
|[[Application software|Local installation]] with [[Software as a service|Cloud sync]], [[Web application|Web version]]
```

**Comment by Coises** [comment] 2019-11-03 23:07
The [Wikipedia page](https://en.wikipedia.org/wiki/List_of_password_managers) mentioned says it is a list of “notable password managers with dedicated Wikipedia articles.” So I take it there would need to be a standalone Wikipedia article for KeeWeb to make it eligible for inclusion in this article. When I look at the list of  [Unofficial KeePass derivatives](https://en.wikipedia.org/wiki/KeePass#Unofficial_KeePass_derivatives) I see that KeeWeb is included; however, aside from KeePassX and KeePassXC, none of the other 26 derivatives have their own articles. I suspect all these are considered not to meet notability guidelines; someone more familiar with Wikipedia protocol might be able to say with more certainty. I know that a standalone article would require references to sources other than KeeWeb’s own pages (such as external reviews or round-ups of password managers) to be considered acceptable (and of course should be written by someone not directly associated with the project).

**Comment by antelle** [comment] 2020-03-21 14:52
The issue is not actionable by project maintainers because the article should not be written by affiliated people. If anyone is willing to help, please let me know.

**Comment by bittner** [comment] 2020-03-23 09:53
I can do that on your behalf. Can you provide me with the details I should fill in into the two tables, please?

**Comment by antelle** [comment] 2020-03-23 15:07
As the article mentions, there should be a separate article about the product first, so probably that should come first.
The content in the table should be something like I posted here above.

**Comment by bittner** [comment] 2020-03-23 20:03
Alright. Then let's start with the dedicated Wikipedia article.

Rhetoric question: Is the project significant enough to make this worthwile? If yes, can you give me a few paragraphs, a link to a logo you want to include, and details for the box on the right side of the article page? I'd suggest we take the [pass (software)](https://en.wikipedia.org/wiki/Pass_(software)) article as an example or role model.

Of course, I will then verify the data provided to me thoroughly and make sure you're reference to original material on the Web makes sense. So, we don't need to be worried about being told to have cheated. -- Does that sound fine for you all?

**Comment by antelle** [comment] 2020-03-23 21:52
> Is the project significant enough to make this worthwile?

No idea, to be honest! The logo can be found here: https://github.com/keeweb/keeweb/blob/master/graphics/icon.icns (I can make a png if you prefer).

I can craft a text this week, it needs some time and effort to prepare.

Sounds fine for me, not sure about Wiki guidelines though, but I guess it should work.

**Comment by antelle** [comment] 2020-03-29 13:40
Something like this.
Disclaimer: I have **absolutely no** experience editing articles on Wikipedia, so I'm not sure about:
- which words must be links;
- if it's ok to publish an article like this, or it needs more authoritative references;
- word choice, I tried to keep it neutral, but may still sound a bit biased and persuasive.

#### Suggested article content

KeeWeb is a free and open-source password manager compatible with KeePass, available as a web version and desktop apps. The underlying file format is KDBX (KeePass database file).

It is written in JavaScript and makes use of WebCrypto and WebAssembly to work with password files directly in browser, without uploading them to a server. It can sync files to popular file hosting services, such as Dropbox, Google Drive or OneDrive.

The same javascript code is also packaged as desktop apps built with Electron. Desktop version however adds some features not available on web:
- auto typing passwords
- ability to open and save local files
- sync to WebDAV without CORS enabled

KeeWeb can be also deployed to an own server or installed as a nextcloud app using nextcloud-keeweb.

Links:
- https://keeweb.info
- https://github.com/keeweb/keeweb
- https://github.com/jhass/nextcloud-keeweb

Icon:
![icon](https://user-images.githubusercontent.com/633557/77850399-8cf29380-71d2-11ea-9ac2-842cdfbbc9c6.png)

Screenshot:
![](https://github.com/keeweb/keeweb/raw/master/img/screenshot.png)

#### Table on the right side

| Type             | Password manager                  |
|------------------|-----------------------------------|
| Operating system | Cross-platform                    |
| Written in       | JavaScript                        |
| Repository       | https://github.com/keeweb/keeweb/ |
| License          | MIT                               |
| Website          | https://keeweb.info               |

**Comment by bittner** [comment] 2020-03-29 14:46
Awesome, your article provides great insights!

Where is the source code of the [Nextcloud app](https://apps.nextcloud.com/apps/keeweb)? I can't see it neither [on GitHub](https://github.com/keeweb?q=nextcloud) nor on the [KeeWeb website](https://keeweb.info/). You're referring to it as "nextcloud-keeweb" though is seems to be called just "keeweb" (or what does _"using nextcloud-keeweb"_ intend to say?).

**Comment by antelle** [comment] 2020-03-29 14:48
Right, better to call it nextcloud-keeweb, it's here: https://github.com/jhass/nextcloud-keeweb

**Comment by bittner** [comment] 2020-03-29 14:56
Is WebCrypto the same as "Web Cryptography API", the W3C's recommendation, or do you refer to a library? I didn't find any.

**Comment by antelle** [comment] 2020-03-29 14:57
Yes: https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

**Comment by bittner** [comment] 2020-03-29 15:21
Can you give me a reference for "The desktop version adds some features not available on web"? Maybe here in the repo, or fro the website?

**Comment by antelle** [comment] 2020-03-29 15:26
There's no such page, so I added it here: https://github.com/keeweb/keeweb/wiki/Supported-Platforms#desktop

**Comment by bittner** [comment] 2020-03-29 15:35
How can I verify that "The underlying file format is KDBX (KeePass database file)"? Is there a good place in the source code where this easy to understand from?

**Comment by antelle** [comment] 2020-03-29 15:42
You can for example create a file in KeePass or KeePassXC and open it in KeeWeb. Not really understandable, but we can create a paragraph about `kdbxweb`:

KeeWeb is using a JavaScript library called `kdbxweb` to work with the underlying file format (KDBX, KeePass database file). The library, according to its author, [is compatible](https://github.com/keeweb/kdbxweb#compatibility) with KDBX version 3 and 4.

https://github.com/keeweb/kdbxweb

**Comment by bittner** [comment] 2020-03-29 15:50
I'm trying to prove the last sentence of the first paragraph. So, I could add a link to [kbdxweb's README](https://github.com/keeweb/kdbxweb#compatibility) and link to a source code location that serves as proof that this library is used. Can you provide me with a URL to such a location? I'm struggling.

**Comment by antelle** [comment] 2020-03-29 15:52
Sure, here's the library included in package.json: https://github.com/keeweb/keeweb/blob/master/package.json#L60, and here's the usage: https://github.com/keeweb/keeweb/blob/master/app/scripts/models/file-model.js#L28

**Comment by bittner** [comment] 2020-03-29 16:05
Voilà, the [first draft](https://en.wikipedia.org/wiki/KeeWeb)! :confetti_ball:

**Comment by antelle** [comment] 2020-03-29 16:11
Thank you ❤️! Let's see if it gets any critics, I see that other articles listed there have some authoritative sources, like for example KeePassXC quotes EFF, that's why I was a bit not sure if it's the right time to add to Wiki now. However since there are products built on KeeWeb by independent developers, could be that it's okay.

**Comment by bittner** [comment] 2020-03-29 16:25
Just a heads-up, I'll release the screenshot as your work with the CC BY-SA 4.0 license (the recommended default on Wikipedia Commons).

**Comment by antelle** [comment] 2020-03-29 16:27
Indeed, please choose any license for it, or you can also make a screenshot if you prefer.

**Comment by bittner** [comment] 2020-03-29 16:32
Voilà! https://commons.wikimedia.org/wiki/File:KeeWeb_Desktop_macOS.png

**Comment by antelle** [comment] 2020-03-29 16:35
What does the approval process look like? I know that everyone can create or edit a page, but when do you think it will make sense the article is mature enough to add it to the list of password managers mentioned in the beginning?

**Comment by bittner** [comment] 2020-03-29 16:39
There are people automatically notified as soon as articles are added or some are modified. I'm pretty sure the article has already been looked at and deemed valuable (or at least "of proper quality", i.e. meeting the standards).

I'll add the logo and screenshot now, and afterwards I'll hop on to edit the list of password managers. There's nothing unethical about this. It's democratic. When someone has a problem with it they will speak up.

**Comment by bittner** [comment] 2020-03-29 16:42
Voilà! The logo. https://commons.wikimedia.org/wiki/File:KeeWeb_logo.png

**Comment by antelle** [comment] 2020-03-29 16:45
Perfect, the content for two tables should be something like this.

First:
```
|-
| [[KeeWeb]]
| {{free|[[MIT License|MIT]]}}
| [[Microsoft Windows|Windows]], [[Linux]], [[macOS]], Web version
| {{some|}} through auto-typing
|[[Application software|Local installation]] with [[Software as a service|Cloud sync]], [[Web application|Web version]]
```

Second:
```
|-
| [[KeeWeb]] || Free/Open Source || {{No}} || {{Yes}} || {{No}} || {{Yes}} || {{Yes}} || {{Yes}} || {{Yes}} || {{Yes}} || {{No}} || {{Yes}} || {{Depends}} || {{Yes}} || {{Yes}} || {{Yes}} || {{Yes}}
```

**Comment by bittner** [comment] 2020-03-29 16:45
You can edit this yourself, and I think I can approve it (if necessary). Want to try?

**Comment by antelle** [comment] 2020-03-29 16:46
Sure, let me try

**Comment by antelle** [comment] 2020-03-29 16:50
Done, added it there

**Comment by bittner** [comment] 2020-03-29 16:57
Nice! I also added a link to KeeWeb to the "Password managers" box at the bottom of the page.

Now we're done, right? Should we close this issue?

**Comment by antelle** [comment] 2020-03-29 17:01
Forgot about the bottom section, thanks for your help!
Yes, I think it's time to close it, probably it makes sense add a page on KeeWeb wiki with a list of external references, projects built on keeweb, etc... everything that can be useful when writing an article like this. I'll try to compile something like this.

**Closed by antelle** 2020-03-29 17:01 UTC
Labels: blocked, docs, help wanted
