### ISSUE TITLE
High memory usage on MacOS

### ISSUE THREAD

**Issue by clustor** [keeweb/keeweb#1580] opened 2020-08-07 20:49 UTC
**Describe the bug**
When I launch KeeWeb the renderer process initially uses ~ 200MB but with usage I have seen it go up as high as 1.8GB. It becomes the second most memory consuming app right below Firefox.  I am happy to provide additional logs. 

**To Reproduce**
Launch KeeWeb and use for few hours. 

**Expected behavior**
I would have expected the GC to kick in and released the stale memory objects. 

**Environment**
KeeWeb v1.14.3 (489eb55, 2020-05-15)
Environment: electron v8.2.5
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.14.2 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36

**Comment by antelle** [comment] 2020-08-07 21:05
Hi! It's not normal of course, expected memory consumption is around 100MB for all processes together.
Does it happen on the demo db?

**Comment by clustor** [comment] 2020-08-07 23:39
Memory consumption with demo db is 144MB
![image](https://user-images.githubusercontent.com/15720802/89696214-d2437200-d8e4-11ea-8e70-3ca27d27dce9.png)

My database is hosted on Google Drive and is 537KB. I do update the DB frequently for one reason or other. After startup, the memory usage is ~290MB. It's always the Renderer process that starts chewing up more memory. 

![image](https://user-images.githubusercontent.com/15720802/89696315-5695f500-d8e5-11ea-950b-d903fb7419d8.png)

**Comment by antelle** [comment] 2020-08-08 07:02
That's very strange. How large is your database and what's special inside? Maybe it's huge with a lot of images?

**Comment by clustor** [comment] 2020-08-10 12:12
The DB size 537KB. I don't think I have lot of images. May be one or two IIRC but I don't know how to find them. The current usage of the Renderer process is 1.16GB. Is there any way to check the memory usage by the Electron framework?

![image](https://user-images.githubusercontent.com/15720802/89781266-01bece00-dae1-11ea-8a1f-2222199e0753.png)

**Comment by antelle** [comment] 2020-08-10 15:03
I also see that the version is KeeWeb is quite old. What if you update it?

**Comment by clustor** [comment] 2020-08-10 16:46
Just updated it. Here is the memory usage right after startup with 1.15.5.  Brew hasn't yet updated the latest rev to 1.15.6.  I will see if this makes a difference. 

![image](https://user-images.githubusercontent.com/15720802/89807912-4eb59b00-db07-11ea-949e-4b3ac27373d0.png)

**Comment by antelle** [comment] 2020-08-10 19:04
What do you see in "Real Private Memory" column?

**Comment by clustor** [comment] 2020-08-12 02:46
This is with 1.15.5. I am beginning to suspect that this could be an underlying Electron framework issue.

![image](https://user-images.githubusercontent.com/15720802/89969414-5454d300-dc24-11ea-81b2-dfb595c3ba40.png)

**Comment by antelle** [comment] 2020-08-12 04:53
Let’s see: download Electron here: https://github.com/electron/electron/releases/download/v8.2.5/electron-v8.2.5-darwin-x64.zip

and launch it. it should show an empty app. How much memory does ut consume?

**Comment by clustor** [comment] 2020-08-12 15:00
That seems reasonable. I will keep it running to see how it changes. 

![image](https://user-images.githubusercontent.com/15720802/90031240-00310980-dc8b-11ea-9d36-b3e12b0fef44.png)

**Comment by antelle** [comment] 2021-03-07 15:41
This may be fixed in v1.17

**Comment by clustor** [comment] 2021-03-09 02:15
I am afraid this issue still exists for me with 1.17.  This is the memory usage after starting Keeweb a day ago. I looked at the change log and nothing popped at me. Was there a change you were expecting to fix this? I can dig deeper into that if needed. 

<img width="981" alt="image" src="https://user-images.githubusercontent.com/15720802/110408173-2701c380-8053-11eb-83ee-41cd2d7fa0ce.png">

**Comment by antelle** [comment] 2021-03-09 17:01
There were small optimizations and Electron was upgraded. But since it's still there, I assume, your file is special in some aspect. What happens if you export it to XML, how large is it?

**Comment by clustor** [comment] 2021-03-10 14:04
XML file is 9150733 bytes. I don't think it will affect anything but I am going to remove the three images to see if it helps. The only thing I can think of is the "Google Drive" integration as the file is stored there. The memory usage goes up with some type of background activity from what I can tell.

**Comment by antelle** [comment] 2021-03-10 15:37
9MB can be quite a lot of data, depending on what's inside.
You can easily verify it by saving a demo file to Google Drive. What happens if you do it without using your file?

**Comment by clustor** [comment] 2021-03-19 11:43
I have actually tried copying the file on Google Drive locally and tried it for few days. The memory consumption goes down a bit compared to using the file from the cloud but I still have the same problem. 

<img width="854" alt="keeweb-local-file" src="https://user-images.githubusercontent.com/15720802/111774517-f1947b80-8885-11eb-9ae9-95a5a85621b4.png">

I will start analyzing why my file is so large now. Are there any dev tools to dump the stats of KeePass entries and understand the memory utilization by the renderer process?

**Comment by antelle** [comment] 2021-03-19 16:42
Well, you can do what I suggested above: save the contents to XML and then inspect what you see inside.

**Comment by antelle** [comment] 2021-03-19 17:07
I made a tool that can help identifying big entries: https://github.com/keeweb/kdbxweb/blob/master/scripts/kdbx-size-profiler.js
How to use it:
1. clone kdbxweb: `git clone https://github.com/keeweb/kdbxweb.git`
2. run `npm i` there
3. save your file to KDBXv4 with AES KDF (not Argon2), with only master password (i.e. no keyfiles, yubikeys, etc...)
4. run `node scripts/kdbx-size-profiler.js your-file.kdbx your-password`

It will print something like this:
```
Binaries: 8185 bytes
Entry: "My MacBook": 83 bytes fields, 0 bytes binaries
Entry: "Windows Tablet": 28 bytes fields, 0 bytes binaries
Entry: "smith@gmail.com": 64 bytes fields, 240 bytes binaries
```

**Comment by clustor** [comment] 2021-03-19 19:46
Really convenient. I just started writing my own script that does this exactly and you just saved some time. I have updated your script to print the total size of the entry (size of current + size of history entries). I have around 2000 entries and the largest entry is around 4K that includes history. I will clear the history to see if it makes a difference.  Honestly, the size of the database still doesn't explain the memory usage to me. It seems like garbage is just getting accumulated. 

Do you know if there is way to clear entire history instead of selecting every history element and clicking on "Delete State"? I always thought this could be nifty.

**Comment by antelle** [comment] 2021-03-19 20:00
I see, 2000 entries with extensive usage of history makes it around 10'000, which is bit extreme. How many entries with history are there in total? I have a test file with 100 groups and 10'000 entries, it consumes around 700MB of memory as well, so I assume that's what's happening in your case.

You can change history garbage collection options in file settings (total MB per file + history length per entry), apart from this there's not much in KeeWeb. I see that KeePassXC doesn't provide any tools either. If I'm not mistaken, there was something in KeePass about history cleanup, you can try it. Just a suggestion (probably that's obvious, but I'll still say it), don't forget to a backup before cleaning up history, and if it doesn't help, you can restore it.

**Comment by clustor** [comment] 2021-03-19 21:40
Total number of entries is 4266 (History entries: 2326 + Current entries: 1940).  Keeweb starts out with consuming 300MB but it grows to GBs in couple of days. I have changed the file settings to keep only 5 entries instead of my current setting of 10.

**Comment by antelle** [comment] 2021-03-19 21:42
Ok, thanks! I think the issue is clear now: files with large amount of entries consume a lot of memory. This is perfectly repeatable and I've just checked, it's been like this since the first version. This can be optimized, I just found one place where we don't clean the XML after loading, removing it saves ≈100MB. I'll remove it and upload to beta to test.

We can also avoid rendering all entries and show them on demand, but that's more complicated of course.

**Comment by clustor** [comment] 2021-03-20 09:45
Yes. I see 70MB saving on startup. That's non-trivial. Good job 👍  Btw, do you render entire file every time an entry is modified? How does memory utilization work with each open after lockout? 

Startup:
![image](https://user-images.githubusercontent.com/15720802/111865724-07b24280-893f-11eb-911d-5b5d8e51eb5b.png)

With Beta:
![image](https://user-images.githubusercontent.com/15720802/111865732-126cd780-893f-11eb-80a9-023c342b1f8b.png)

**Comment by antelle** [comment] 2021-03-20 10:32
It depends on the number of entries you have visible. For example, if you have "Show entries from all subgroups" unchecked, it will display only what you have in the root group. Otherwise it will show all entries in the file, yes.

**Comment by antelle** [comment] 2021-03-20 10:51
I made a first simple version with so-called virtual scrolling (when we render only visible items in the list). But before working on it, I'd like to understand it it makes sense because if it saves 5 MB, it's not worth the price.
Could you please check if there's any difference for you on [beta](https://beta.keeweb.info?new)? I'm afraid, it won't help much if it already consumes 127 MB.

For me, there's a big memory difference (440 MB vs 147 MB) on a file with 10'000 entries, but it's an extreme case, I'd prefer not optimizing for it.

**Comment by clustor** [comment] 2021-03-20 11:51
I am seeing considerable improvement with the latest beta as well.  

<img width="851" alt="image" src="https://user-images.githubusercontent.com/15720802/111868552-fe31d600-8950-11eb-87d9-f07bae906487.png">

**Comment by antelle** [comment] 2021-03-20 11:53
Interesting, 50MB is not bad, then it makes sense to keep it and make it stable.

**Comment by antelle** [comment] 2021-03-20 18:20
I've finished virtual scrolling, now it seems to be working well, it can be tested on [beta](https://beta.keeweb.info).

**Comment by clustor** [comment] 2021-03-20 18:49
Nice work 👍  So far it looks good. This is with the Beta and I have the best memory utilization so far. 

<img width="874" alt="image" src="https://user-images.githubusercontent.com/15720802/111882306-55549c80-898b-11eb-835c-6dcad20213e3.png">

**Comment by antelle** [comment] 2021-03-20 19:02
Good! It's a rather big change for a hotfix, so it will be included in the next major release, v1.18.

**Comment by clustor** [comment] 2021-03-21 23:18
This change looks good to me for the most part. The memory consumption did go up but not at the same rate I noticed before. I think there is still scope for optimization but the latest changes address the major issue. I am happy to wait until v1.18. Thanks for your persistence with this issue. 

<img width="866" alt="image" src="https://user-images.githubusercontent.com/15720802/111924235-d5f1c680-8a79-11eb-81e6-8ff6d8c99491.png">

**Comment by antelle** [comment] 2021-03-27 09:30
I've merged the first, "safe", part of it in v1.17, it's [available](https://github.com/keeweb/keeweb/releases/v1.17.5) for download, the rest will come in v1.18.

**Comment by clustor** [comment] 2021-03-27 16:19
Great. I am going to stay on beta to see if I notice any issues.  

Do you know if it is possible to discard all object references for GC to clean up every time Keeweb locks out? That might be another potential saving. Of course, I am happy and thankful for your recent changes but this much memory to display 9MB XML is a lot 😀

<img width="863" alt="image" src="https://user-images.githubusercontent.com/15720802/112726925-36f42100-8ef6-11eb-9387-0addbc6359e4.png">

**Comment by antelle** [comment] 2021-03-27 16:24
You can try doing it from devtools, to check if it helps:  
<img width="1076" alt="GC" src="https://user-images.githubusercontent.com/633557/112727144-43da3a00-8f21-11eb-85b3-9af6cbe714f6.png">

I assume, it's not garbage collector not working, but rather something in the application. But let's see.

**Comment by clustor** [comment] 2021-04-26 15:09
I didn't mean to say that garbage collector is not working but I was wondering if there are some stale memory references sticking around that are no longer needed.

https://auth0.com/blog/four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them/

**Comment by antelle** [comment] 2021-04-26 16:28
Well, there shouldn't be anything left when you lock KeeWeb, but I'll check once again, perhaps something is not cleaned up.

**Comment by antelle** [comment] 2021-04-26 17:34
Fixed one leak, now it will delete data from memory.

**Closed** 2021-05-08 17:45 UTC
Labels: enhancement, performance
