### ISSUE TITLE
Collapse folders by default

### ISSUE THREAD

**Issue by devozanges** [keeweb/keeweb#1595] opened 2020-09-09 09:39 UTC
Hello, I have in my trunk a dozen folders which themselves contain a dozen sub-folders. When the application opens, all the folders are open. Is there a way to close them by default to avoid it taking up the whole page?

**Comment by antelle** [comment] 2020-09-09 17:13
Right now folders are collapsed if you double-click them and make a change in the file somewhere after it, this can be a workaround. But I can understand why you would like to have this feature. Most likely the root folder should be always expanded, while ones inside can be collapsed.

**Comment by gynet** [comment] 2020-09-16 06:10
Duplicate of #1488

**Closed** 2020-09-16 08:00 UTC
Labels: enhancement
